// Copyright (C) 2026  Braiins Forge s.r.o.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Braiins Systems s.r.o. and Braiins Forge s.r.o. each reserve the right
// to grant any party a license to this program, or any part thereof,
// under any terms, and such a grant shall be considered distinct from
// the grant above.

//! Build script: parse AnySoftKeyboard XML layout files into Rust constants.
//!
//! Layout source: AnySoftKeyboard (Apache 2.0)
//! <https://github.com/AnySoftKeyboard/AnySoftKeyboard/tree/main/addons/languages>

use std::fmt::Write;
use std::path::Path;
use std::{env, fs};

/// AnySoftKeyboard special key codes.
const ASK_CODE_SHIFT: i32 = -1;
const ASK_CODE_DELETE: i32 = -5;

fn main() {
    let out_dir = env::var("OUT_DIR").expect("BUG: OUT_DIR not set");
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("BUG: CARGO_MANIFEST_DIR not set");
    let layouts_dir = Path::new(&manifest_dir).join("assets/layouts");

    println!("cargo:rerun-if-changed=assets/layouts");

    let mut output = String::from(
        "// AUTO-GENERATED by build.rs from AnySoftKeyboard (Apache 2.0)\n\
         // Source: https://github.com/AnySoftKeyboard/AnySoftKeyboard/tree/main/addons/languages\n\
         // Do not edit manually.\n\n",
    );

    let layouts = [
        ("en_qwerty.xml", "QWERTY_US", "US English", "QWERTY"),
        ("de_qwertz.xml", "QWERTZ_DE", "German", "QWERTZ"),
        ("fr_azerty.xml", "AZERTY_FR", "French", "AZERTY"),
        ("fi_qwerty.xml", "QWERTY_FI", "Finnish", "QWERTY"),
        ("fi_qwerty.xml", "QWERTY_SE", "Swedish", "QWERTY"),
        ("da_qwerty.xml", "QWERTY_DA", "Danish", "QWERTY"),
        ("no_qwerty.xml", "QWERTY_NO", "Norwegian", "QWERTY"),
    ];

    for (filename, const_name, display_name, variant) in &layouts {
        let path = layouts_dir.join(filename);
        let xml = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("BUG: failed to read {}: {e}", path.display()));
        println!("cargo:rerun-if-changed=assets/layouts/{filename}");

        let mut rows = parse_layout(&xml, filename, &layouts_dir);
        normalize_top_row_popups(&mut rows);
        dedup_digit_variants(&mut rows);
        generate_layout(&mut output, &rows, const_name, display_name, variant);
    }

    // Generate ALL_LAYOUTS array
    writeln!(output, "/// All available keyboard layouts.")
        .expect("BUG: failed to write generated layout code to String");
    write!(output, "pub static ALL_LAYOUTS: &[&KeyboardLayout] = &[")
        .expect("BUG: failed to write generated layout code to String");
    for (_, const_name, _, _) in &layouts {
        write!(output, "&{const_name}, ")
            .expect("BUG: failed to write generated layout code to String");
    }
    writeln!(output, "];").expect("BUG: failed to write generated layout code to String");

    fs::write(Path::new(&out_dir).join("layouts_generated.rs"), output)
        .expect("BUG: failed to write layouts_generated.rs");
}

/// A parsed key from the XML.
struct ParsedKey {
    code: i32,
    label: Option<String>,
    /// Full popup characters string (unescaped). Shown on long-press.
    popup: Option<String>,
    width_pct: Option<f32>,
}

/// A parsed row from the XML.
struct ParsedRow {
    keys: Vec<ParsedKey>,
    default_width_pct: Option<f32>,
}

/// Parse an AnySoftKeyboard XML layout file into rows of keys.
fn parse_layout(xml: &str, filename: &str, layouts_dir: &Path) -> Vec<ParsedRow> {
    let doc = roxmltree::Document::parse(xml)
        .unwrap_or_else(|e| panic!("BUG: failed to parse {filename}: {e}"));

    let mut rows = Vec::new();

    for node in doc.descendants() {
        if node.tag_name().name() != "Row" {
            continue;
        }

        let row_width = attr(&node, "keyWidth").and_then(parse_percentage);

        let mut keys = Vec::new();

        for key_node in node.children() {
            if key_node.tag_name().name() != "Key" {
                continue;
            }

            let Some(codes_str) = attr(&key_node, "codes") else {
                continue;
            };

            // `parse_code` returns `None` for known-but-unsupported function
            // keys (e.g. `@integer/key_code_smiley`); skip the key in that
            // case rather than panic the whole build.
            let Some(code) = parse_code(codes_str) else {
                continue;
            };
            let label = attr(&key_node, "keyLabel").map(String::from);
            let width_pct = attr(&key_node, "keyWidth").and_then(parse_percentage);

            let popup = attr(&key_node, "popupCharacters")
                .map(unescape)
                .or_else(|| {
                    attr(&key_node, "popupKeyboard")
                        .map(|ref_str| resolve_popup_keyboard(ref_str, filename, layouts_dir))
                });

            keys.push(ParsedKey {
                code,
                label,
                popup,
                width_pct,
            });
        }

        if !keys.is_empty() {
            rows.push(ParsedRow {
                keys,
                default_width_pct: row_width,
            });
        }
    }

    rows
}

/// Resolve a `popupKeyboard="@xml/foo"` reference by loading `foo.xml`
/// from the layouts directory and extracting character codes from its keys.
fn resolve_popup_keyboard(ref_str: &str, parent_filename: &str, layouts_dir: &Path) -> String {
    let xml_name = ref_str.strip_prefix("@xml/").unwrap_or_else(|| {
        panic!("{parent_filename}: unsupported popupKeyboard reference: {ref_str:?}")
    });

    let popup_path = layouts_dir.join(format!("{xml_name}.xml"));
    let popup_xml = fs::read_to_string(&popup_path).unwrap_or_else(|e| {
        panic!(
            "{parent_filename}: popupKeyboard references {ref_str:?} but {path} not found: {e}",
            path = popup_path.display()
        )
    });

    println!("cargo:rerun-if-changed=assets/layouts/{xml_name}.xml");

    let doc = roxmltree::Document::parse(&popup_xml).unwrap_or_else(|e| {
        panic!("{parent_filename}: failed to parse popup keyboard {xml_name}.xml: {e}")
    });

    let mut chars = String::new();
    for node in doc.descendants() {
        if node.tag_name().name() != "Key" {
            continue;
        }
        let Some(codes_str) = attr(&node, "codes") else {
            continue;
        };
        // Unsupported function keys in popup XML get the same skip as in the
        // main layout — they have no meaningful glyph to add to the popup bar.
        let Some(code) = parse_code(codes_str) else {
            continue;
        };
        // Skip control characters (< 32), special key codes (< 0), and ASCII
        // digits (48–57). Popup keyboards include the digit for top-row number
        // popups, but normalize_top_row_popups already handles that — including
        // it here would produce duplicates.
        #[expect(clippy::cast_sign_loss, reason = "guarded by code >= 32")]
        if code >= 32 && !char::from_u32(code as u32).is_some_and(|c| c.is_ascii_digit()) {
            #[expect(clippy::cast_sign_loss, reason = "guarded by code >= 32")]
            if let Some(ch) = char::from_u32(code as u32) {
                chars.push(ch);
            }
        }
    }

    chars
}

/// Get an attribute value by local name, ignoring XML namespaces.
///
/// AnySoftKeyboard uses `android:codes`, `android:keyLabel`, etc.
/// roxmltree's `.attribute()` requires exact namespace match, so we
/// search by local name across all namespaces.
fn attr<'a>(node: &'a roxmltree::Node<'a, '_>, local_name: &str) -> Option<&'a str> {
    node.attributes()
        .find(|a| a.name() == local_name)
        .map(|a| a.value())
}

/// Parse an android:codes value.
///
/// Handles integer literals ("113"), character literals ("q"), negative codes ("-1"),
/// and resource references ("@integer/key_code_shift" → -1).
///
/// Returns `None` for known-but-unsupported `@integer/key_code_*` references
/// (e.g. `key_code_smiley`) and emits a `cargo:warning=` so the dev sees what
/// got skipped. The caller is expected to drop that key from the layout.
/// Genuinely malformed input still panics.
fn parse_code(s: &str) -> Option<i32> {
    // Resource references
    if let Some(rest) = s.strip_prefix("@integer/key_code_") {
        return match rest {
            "shift" => Some(ASK_CODE_SHIFT),
            "delete" => Some(ASK_CODE_DELETE),
            _ => {
                println!(
                    "cargo:warning=keyboard: skipping unsupported function key {s} \
                     (no `KeyCode` mapping in `bmc-render-keyboard`)"
                );
                None
            }
        };
    }

    // Try as integer first (handles negative codes and Unicode codepoints).
    // Validate negative values up front — only the ASK function-key sentinels
    // are recognized — so a malformed layout fails here instead of one step
    // later in `generate_key` where the source attribute is no longer in
    // scope.
    if let Ok(n) = s.parse::<i32>() {
        assert!(
            n >= 0 || n == ASK_CODE_SHIFT || n == ASK_CODE_DELETE,
            "BUG: unsupported negative key code in XML: {n} \
             (only {ASK_CODE_SHIFT} = shift and {ASK_CODE_DELETE} = delete are recognized)"
        );
        return Some(n);
    }

    // Try as single character
    let mut chars = s.chars();
    if let Some(ch) = chars.next()
        && chars.next().is_none()
    {
        return Some(ch as i32);
    }

    // Unicode escape like \u0027
    if let Some(hex) = s.strip_prefix("\\u")
        && let Ok(n) = u32::from_str_radix(hex, 16)
    {
        #[expect(clippy::cast_possible_wrap)]
        return Some(n as i32);
    }

    panic!("BUG: cannot parse code: {s:?}");
}

/// Parse a percentage string like "15%p" or "9.09%p" into a float.
fn parse_percentage(s: &str) -> Option<f32> {
    s.strip_suffix("%p").and_then(|n| n.parse::<f32>().ok())
}

/// Unescape `\uXXXX` sequences in Android XML attribute values.
/// XML entities (`&lt;`, `&amp;`, etc.) are already handled by roxmltree.
fn unescape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars();
    while let Some(ch) = chars.next() {
        if ch == '\\' {
            if let Some('u') = chars.next() {
                let hex: String = chars.by_ref().take(4).collect();
                if let Ok(n) = u32::from_str_radix(&hex, 16)
                    && let Some(c) = char::from_u32(n)
                {
                    out.push(c);
                    continue;
                }
                // Failed to parse — emit literally
                out.push('\\');
                out.push('u');
                out.push_str(&hex);
            } else {
                out.push('\\');
            }
        } else {
            out.push(ch);
        }
    }
    out
}

/// Numbers corresponding to top-row key positions (QWERTY order).
const TOP_ROW_NUMBERS: &[char] = &['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'];

/// Ensure the first row's character keys have number popups.
/// If a key already has popups, prepend the number if missing.
/// If it has no popups, set popup to just the number.
fn normalize_top_row_popups(rows: &mut [ParsedRow]) {
    let Some(first_row) = rows.first_mut() else {
        return;
    };

    // Only process character keys (skip shift/backspace which have negative codes)
    let char_keys: Vec<usize> = first_row
        .keys
        .iter()
        .enumerate()
        .filter(|(_, k)| k.code >= 0)
        .map(|(i, _)| i)
        .collect();

    for (pos, &key_idx) in char_keys.iter().enumerate() {
        let Some(&number) = TOP_ROW_NUMBERS.get(pos) else {
            break;
        };
        let key = &mut first_row.keys[key_idx];
        match &mut key.popup {
            Some(popup) if popup.starts_with(number) => {} // already has it
            Some(popup) => {
                popup.insert(0, number);
            }
            None => {
                key.popup = Some(number.to_string());
            }
        }
    }
}

/// Strip superscript/subscript digit variants from popup strings.
///
/// `normalize_top_row_popups` runs first and guarantees `0`–`9` are reachable
/// via long-press on row-0 character keys, so any `¹²³…` or `₁₂₃…` left in a
/// popup is duplicated noise that just crowds the long-press bar.
fn dedup_digit_variants(rows: &mut [ParsedRow]) {
    const SUPERSCRIPTS: &[char] = &['⁰', '¹', '²', '³', '⁴', '⁵', '⁶', '⁷', '⁸', '⁹'];
    const SUBSCRIPTS: &[char] = &['₀', '₁', '₂', '₃', '₄', '₅', '₆', '₇', '₈', '₉'];

    fn is_super_or_subscript_digit(ch: char) -> bool {
        SUPERSCRIPTS.contains(&ch) || SUBSCRIPTS.contains(&ch)
    }

    for row in rows {
        for key in &mut row.keys {
            if let Some(popup) = &mut key.popup {
                let filtered: String = popup
                    .chars()
                    .filter(|&ch| !is_super_or_subscript_digit(ch))
                    .collect();
                *popup = filtered;
            }
        }
    }
}

/// Generate Rust code for a keyboard layout.
fn generate_layout(
    out: &mut String,
    rows: &[ParsedRow],
    const_name: &str,
    display_name: &str,
    variant: &str,
) {
    // Generate letter rows (base)
    for (i, row) in rows.iter().enumerate() {
        writeln!(out, "static {const_name}_ROW{i}: &[Key] = &[")
            .expect("BUG: failed to write generated layout code to String");

        let default_width = row.default_width_pct.unwrap_or(10.0);

        for key in &row.keys {
            let width = key.width_pct.unwrap_or(default_width) / default_width;
            generate_key(out, key, width);
        }

        writeln!(out, "];").expect("BUG: failed to write generated layout code to String");
    }

    // Generate letter rows (shifted) — uppercase versions
    for (i, row) in rows.iter().enumerate() {
        writeln!(out, "static {const_name}_SHIFTED_ROW{i}: &[Key] = &[")
            .expect("BUG: failed to write generated layout code to String");

        let default_width = row.default_width_pct.unwrap_or(10.0);

        for key in &row.keys {
            let width = key.width_pct.unwrap_or(default_width) / default_width;
            generate_key_shifted(out, key, width);
        }

        writeln!(out, "];").expect("BUG: failed to write generated layout code to String");
    }

    // Generate row arrays
    let row_count = rows.len();
    writeln!(out, "static {const_name}_LETTERS: &[&[Key]] = &[")
        .expect("BUG: failed to write generated layout code to String");
    for i in 0..row_count {
        writeln!(out, "    {const_name}_ROW{i},")
            .expect("BUG: failed to write generated layout code to String");
    }
    writeln!(out, "    BOTTOM_ROW,").expect("BUG: failed to write generated layout code to String");
    writeln!(out, "];").expect("BUG: failed to write generated layout code to String");

    writeln!(out, "static {const_name}_SHIFTED: &[&[Key]] = &[")
        .expect("BUG: failed to write generated layout code to String");
    for i in 0..row_count {
        writeln!(out, "    {const_name}_SHIFTED_ROW{i},")
            .expect("BUG: failed to write generated layout code to String");
    }
    writeln!(out, "    BOTTOM_ROW,").expect("BUG: failed to write generated layout code to String");
    writeln!(out, "];").expect("BUG: failed to write generated layout code to String");

    // The layout struct (symbols layers are shared, defined in layout.rs)
    writeln!(out, "/// {display_name} keyboard layout.")
        .expect("BUG: failed to write generated layout code to String");
    writeln!(
        out,
        "pub static {const_name}: KeyboardLayout = KeyboardLayout {{"
    )
    .expect("BUG: failed to write generated layout code to String");
    writeln!(out, "    name: \"{display_name}\",")
        .expect("BUG: failed to write generated layout code to String");
    writeln!(out, "    variant: \"{variant}\",")
        .expect("BUG: failed to write generated layout code to String");
    writeln!(out, "    letters: {const_name}_LETTERS,")
        .expect("BUG: failed to write generated layout code to String");
    writeln!(out, "    letters_shifted: {const_name}_SHIFTED,")
        .expect("BUG: failed to write generated layout code to String");
    writeln!(out, "    symbols: SYMBOLS,")
        .expect("BUG: failed to write generated layout code to String");
    writeln!(out, "    symbols_shifted: SYMBOLS_SHIFTED,")
        .expect("BUG: failed to write generated layout code to String");
    writeln!(out, "}};").expect("BUG: failed to write generated layout code to String");
    writeln!(out).expect("BUG: failed to write generated layout code to String");
}

/// Whether `width` represents a single keyboard cell.
///
/// `width` is computed as `key_pct / row_default_pct`; for a single-cell key
/// that's `~1.0` mathematically, but XML can carry imprecise percentages
/// (e.g. `9.99%p`) which yield `0.999` after division. Tolerance compare
/// keeps the per-cell path stable against those.
fn approx_unit_width(width: f32) -> bool {
    (width - 1.0).abs() < 1e-3
}

/// Generate a single key definition (base layer).
#[expect(clippy::cast_sign_loss, reason = "guarded by code >= 0 match arm")]
fn generate_key(out: &mut String, key: &ParsedKey, width: f32) {
    match key.code {
        ASK_CODE_SHIFT => {
            writeln!(out, "    Key::action(\"\", {width:.2}, KeyCode::Shift),")
                .expect("BUG: failed to write generated layout code to String");
        }
        ASK_CODE_DELETE => {
            writeln!(
                out,
                "    Key::action(\"\", {width:.2}, KeyCode::Backspace),"
            )
            .expect("BUG: failed to write generated layout code to String");
        }
        code if code >= 0 => {
            let ch = char::from_u32(code as u32).unwrap_or_else(|| {
                panic!("BUG: invalid Unicode codepoint: {code}");
            });
            let label = key.label.as_deref().unwrap_or("");
            let label_str: String =
                if label.is_empty() || label.starts_with(ch) && label.len() == ch.len_utf8() {
                    ch.to_string()
                } else {
                    label.to_string()
                };
            let popup = key.popup.as_deref().unwrap_or("");
            let unit = approx_unit_width(width);
            if !popup.is_empty() && unit {
                writeln!(
                    out,
                    "    Key::char_popup({label_str:?}, {popup:?}, {ch:?}),"
                )
                .expect("BUG: failed to write generated layout code to String");
            } else if unit {
                writeln!(out, "    Key::char({label_str:?}, {ch:?}),")
                    .expect("BUG: failed to write generated layout code to String");
            } else {
                writeln!(
                    out,
                    "    Key::char_wide({label_str:?}, {ch:?}, {width:.2}),"
                )
                .expect("BUG: failed to write generated layout code to String");
            }
        }
        other => panic!("BUG: unhandled key code: {other}"),
    }
}

/// Generate a single key definition (shifted layer — uppercase).
///
/// Uppercases both the character and any popup chars so long-press on a
/// shifted letter still reaches the diacritic variants (e.g. `É È Ê` on `E`).
#[expect(clippy::cast_sign_loss, reason = "guarded by code >= 0 match arm")]
fn generate_key_shifted(out: &mut String, key: &ParsedKey, width: f32) {
    match key.code {
        ASK_CODE_SHIFT => {
            writeln!(out, "    Key::action(\"\", {width:.2}, KeyCode::Shift),")
                .expect("BUG: failed to write generated layout code to String");
        }
        ASK_CODE_DELETE => {
            writeln!(
                out,
                "    Key::action(\"\", {width:.2}, KeyCode::Backspace),"
            )
            .expect("BUG: failed to write generated layout code to String");
        }
        code if code >= 0 => {
            let ch = char::from_u32(code as u32).unwrap_or_else(|| {
                panic!("BUG: invalid Unicode codepoint: {code}");
            });
            let upper = ch.to_uppercase().next().unwrap_or(ch);
            let label_str = upper.to_string();
            let popup_lower = key.popup.as_deref().unwrap_or("");
            let popup_upper: String = popup_lower.chars().flat_map(char::to_uppercase).collect();
            let unit = approx_unit_width(width);
            if !popup_upper.is_empty() && unit {
                writeln!(
                    out,
                    "    Key::char_popup({label_str:?}, {popup_upper:?}, {upper:?}),"
                )
                .expect("BUG: failed to write generated layout code to String");
            } else if unit {
                writeln!(out, "    Key::char({label_str:?}, {upper:?}),")
                    .expect("BUG: failed to write generated layout code to String");
            } else {
                writeln!(
                    out,
                    "    Key::char_wide({label_str:?}, {upper:?}, {width:.2}),"
                )
                .expect("BUG: failed to write generated layout code to String");
            }
        }
        other => panic!("BUG: unhandled key code: {other}"),
    }
}
