import { ConnectQr } from "../templates/connect_qr.slint";
import { Palette } from "../../style/palette.slint";
import { Theme } from "../../style/theme.slint";
import { Images } from "../../style/images.slint";

export component ConnectInfo inherits ConnectQr {
    connect_text: "Access device at";

    VerticalLayout {
        alignment: end;
        padding-bottom: 20px;

        HorizontalLayout {
            alignment: end;
            spacing: 8px;
            padding-right: 20px;

            Text {
                text: "To access the controls, IP and WiFi info";
                color: Palette.gray-40;
                font-size: 24px;
            }

            Text {
                text: "swipe up";
                color: Palette.gray-40;
                font-size: 24px;
                font-weight: Theme.font.weight.bold;
            }

            Image {
                width: 32px;
                height: 32px;
                source: Images.arm-arrow-up;
            }
        }
    }
}
