[package]
name = "bmc-support"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
authors = ["Braiins <braiins@braiins.com>"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bmc-net-diag.workspace = true
# zip crate with 'deflate-flate2' cannot be compiled without 'flate2' with 'rust_backend'
flate2 = { workspace = true, features = ["rust_backend"] }
regex.workspace = true
tracing.workspace = true
walkdir.workspace = true
zip = { workspace = true, features = ["deflate-flate2"] }

[dev-dependencies]
anyhow.workspace = true
tempfile.workspace = true
tracing-subscriber.workspace = true
