import { InitSetupTemplate } from "../templates/init_setup.slint";
import { Images } from "../../style/images.slint";

export component InitSetupSuccess inherits InitSetupTemplate {
    icon_text_header_title: "Initial Setup";
    icon_text_title: "Bitcoin Mining Clock is ready!";
    icon_text_content: "Login to continue.";
    icon_text_image_visible: true;
    icon_text_image: Images.success-big;
}
