import { InitSetupTemplate } from "../templates/init_setup.slint";
import { Images } from "../../style/images.slint";
import { WifiAdapter } from "../../controls/adapters.slint";

export component InitStartConnect inherits InitSetupTemplate {
    icon_text_header_title: "Initial Setup";
    icon_text_title: "Start with connecting to Braiins Deck WiFi";
    icon_text_content: "WiFi SSID";
    icon_text_subtitle: WifiAdapter.ssid;
    icon_text_image_visible: true;
    icon_text_image: Images.wifi-connect;
}
