# Copyright (C) 2025  Braiins Systems s.r.o.

stages:
  - essentials
  - dependencies
  - check
  - apps

##################################
######## Essentials Stage ########
##################################
variables:
  CI_TOOLS_REV: 2295f1d29d8ca3ecd3afeae979cb41fbacfbe339 # This is not accessible inside "include"
include:
  - project: 'nix/ci-tools'
    ref: 2295f1d29d8ca3ecd3afeae979cb41fbacfbe339
    file:
      - '.essentials.yml'
      - '.dependencies.yml'
      - '.check.yml'

############################
######## Apps Stage ########
############################

.app: &app
  extends: [.nix, .artifacts]
  stage: apps
  needs: []
  when: manual

bmc-mock:
  extends: .app
  script:
    - nix build .#bmc-mock

bmc-openwrt:
  extends: .app
  script:
    - nix build .#bmc-openwrt-armv7-release

web-assets:
  extends: .app
  script:
    - nix build .#web-assets
