# Copyright (C) 2025  Braiins Systems s.r.o.

stages:
  - essentials
  - dependencies
  - check
  - apps

##################################
######## Essentials Stage ########
##################################
variables:
  CI_TOOLS_REV: 57c7cd63b3d18abdbb8a57017deae96aece680df # This is not accessible inside "include"
  WORKSPACE_LINTS_IGNORE_PATHS: "./bmc-shared/ii-net ./bmc-shared/ii-net-drv"


include:
  - project: "nix/ci-tools"
    ref: 57c7cd63b3d18abdbb8a57017deae96aece680df
    file:
      - ".essentials.yml"
      - ".dependencies.yml"
      - ".check.yml"

verify-tooling-crates:
  extends: .nix
  stage: essentials
  script:
    - nix develop .#fast --command ./scripts/verify_crate_hash.sh tooling

############################
######## Apps Stage ########
############################

.app: &app
  extends: [.nix, .artifacts]
  stage: apps
  needs: []
  when: manual

bmc-mock:
  extends: .app
  script:
    - nix build .#bmc-mock

bmc-openwrt:
  extends: .app
  script:
    - nix build .#bmc-openwrt-armv7-release

frontend:
  extends: .app
  script:
    - nix build .#frontend
