# Copyright (C) 2025  Braiins Systems s.r.o.

stages:
  - essentials
  - dependencies
  - check
  - apps

##################################
######## Essentials Stage ########
##################################
variables:
  CI_TOOLS_REV: 8850521aa3670e67c5265127e11222de6cf4ec94 # This is not accessible inside "include"
include:
  - project: "nix/ci-tools"
    ref: 8850521aa3670e67c5265127e11222de6cf4ec94
    file:
      - ".essentials.yml"
      - ".dependencies.yml"
      - ".check.yml"

verify-tooling-crates:
  extends: .nix
  stage: essentials
  script:
    - nix develop .#fast --command ./scripts/verify_crate_hash.sh tooling

############################
######## Apps Stage ########
############################

.app: &app
  extends: [.nix, .artifacts]
  stage: apps
  needs: []
  when: manual

bmc-mock:
  extends: .app
  script:
    - nix build .#bmc-mock

bmc-openwrt:
  extends: .app
  script:
    - nix build .#bmc-openwrt-armv7-release

frontend:
  extends: .app
  script:
    - nix build .#frontend
