[workspace]
resolver = "3"
members = [
    "bmc",
    "bmc-audio",
    "bmc-button",
    "bmc-compositor",
    "bmc-display",
    "bmc-gpio",
    "bmc-grpc",
    "bmc-ipc",
    "bmc-kobject",
    "bmc-led",
    "bmc-mock",
    "bmc-mock-display",
    "bmc-openwrt",
    "bmc-platform",
    "bmc-scheduler",
    "bmc-shared/*",
    "bmc-support",
    "bmc-upgrade",
    "bmc-widget",
    "widgets/*",
]

[profile.release]
strip = true

[profile.dev]
opt-level = 3
strip = true

[profile.lto]
inherits = "release"
lto = true

# special profile used in CI, optimized for fast compilation and efficient caching
[profile.fast]
inherits = "dev"
opt-level = 0
debug = false
strip = true
incremental = false
codegen-units = 512

[workspace.lints.rust]
# deny
unused_must_use = "deny"
# warn
explicit_outlives_requirements = "warn"
future_incompatible = { level = "warn", priority = -1 }
macro_use_extern_crate = "warn"
missing_debug_implementations = "warn"
nonstandard_style = { level = "warn", priority = -1 }
rust_2018_idioms = { level = "warn", priority = -1 }
trivial_numeric_casts = "warn"
# allow
deprecated = "allow"
unused_crate_dependencies = "allow"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
# lints from the clippy::pedantic group that are explicitly allowed
doc_markdown = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
needless_continue = "allow"
new_without_default = "allow"
similar_names = "allow"
unreadable_literal = "allow"
# additional useful lints not coveded by clippy::pedantic
allow_attributes = "warn"
get_unwrap = "warn"
integer_division = "warn"
lossy_float_literal = "warn"
modulo_arithmetic = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
str_to_string = "warn"
string_add = "warn"
string_slice = "warn"
string_to_string = "warn"
unneeded_field_pattern = "warn"
unseparated_literal_suffix = "warn"
wildcard_enum_match_arm = "warn"

[workspace.dependencies]
aes = "0.8.4"
anyhow = "1.0.98"
apa102-spi = "0.5.1"
assert_matches = "1.5.0"
async-once-cell = "0.5.4"
async-stream = "0.3.6"
async-trait = "0.1.88"
axum = "0.8.4"
axum-extra = "0.10.1"
backon = { version = "1.5.2", default-features = false, features = ["std"] }
base64 = "0.22.1"
bincode = "2.0.0" # NOTE: check https://docs.rs/bincode/latest/bincode/serde/index.html#known-issues before enabling `serde` feature
bmc = { path = "bmc" }
bmc-audio = { path = "bmc-audio" }
bmc-button = { path = "bmc-button" }
bmc-display = { path = "bmc-display" }
bmc-gpio = { path = "bmc-gpio" }
bmc-grpc = { path = "bmc-grpc" }
bmc-ipc = { path = "bmc-ipc" }
bmc-kobject = { path = "bmc-kobject" }
bmc-led = { path = "bmc-led" }
bmc-mock-display = { path = "bmc-mock-display" }
bmc-platform = { path = "bmc-platform" }
bmc-scheduler = { path = "bmc-scheduler" }
bmc-shared-esp32 = { path = "bmc-shared/esp32" }
bmc-shared-ii-dns = { package = "ii-dns", path = "bmc-shared/ii-dns" }
bmc-shared-ii-net = { package = "ii-net", path = "bmc-shared/ii-net" }
bmc-shared-ii-net-drv = { package = "ii-net-drv", path = "bmc-shared/ii-net-drv" }
bmc-shared-slint = { path = "bmc-shared/slint" }
bmc-shared-time = { path = "bmc-shared/time" }
bmc-shared-utils = { path = "bmc-shared/utils" }
bmc-support = { path = "bmc-support" }
bmc-upgrade = { path = "bmc-upgrade" }
bmc-widget = { path = "bmc-widget" }
bstr = "1.11.3"
bytes = { version = "1.6.0", default-features = false }
bytesize = { version = "2.0.1", features = ["serde"] }
cbc = { version = "0.1.2", default-features = false }
chrono = { version = "0.4.40", features = ["serde"] }
chrono-tz = { version = "0.10.3", default-features = false }
clap = { version = "4.5.37", features = ["derive", "std"] }
croner = "3.0.0"
data-encoding = "2.6.0"
dialoguer = "0.11.0"
dirs = "6.0.0"
drm = "0.14.1"
drm-fourcc = "2.2.0"
gbm = { version = "0.17.0", default-features = false, features = ["drm-support"] }
calloop = { version = "0.14.2", features = ["executor"] }
input = "0.9.1"
libc = "0.2"
libseat = "0.2.4"
smithay = { version = "0.7.0", default-features = false, features = [
    "backend_drm",
    "backend_gbm",
    "backend_libinput",
    "backend_udev",
    "renderer_glow",
    "use_system_lib",
    "wayland_frontend",
] }
smithay-drm-extras = { version = "0.1.0", default-features = false }
embedded-hal = { version = "1.0.0" }
embedded-hal-async = { version = "1.0.0" }
enum-assoc = "1.2.4"
evdev = "0.13.1"
fdlimit = "0.3.0"
file-rotate = "0.7.6"
flate2 = { version = "1.0.30", default-features = false }
flume = { version = "0.11.1", default-features = false }
formato = "0.3.0"
fs-err = { version = "3.1.0", features = ["tokio"] }
futures = "0.3.31"
futures-util = "0.3.31"
get_if_addrs = "0.5.3"
glob = "0.3.2"
governor = "0.8.1"
hex = "0.4.3"
hickory-resolver = "0.25.2"
http = "1.3.1"
humantime-serde = "1.1.1"
hyper = "1.6.0"
iana-time-zone = "0.1.63"
idxgen-data = { path = "tooling/idxgen/idxgen-data" }
image = { version = "0.25.8", features = ["default-formats"] }
index-bmc = { path = "tooling/crates/index-bmc" }
index-common = { path = "tooling/crates/index-common" }
indexmap = { version = "2.10.0", default-features = false, features = ["serde", "std"] }
infer = "0.19.0"
itertools = "0.14.0"
log = "0.4.27"
markdown = "1.0.0-alpha.23"
maud = "0.27.0"
memmap2 = "0.9.4"
mime_guess = "2.0.5"
minerctl-defs = { path = "tooling/minerctl/minerctl-defs" }
minifb = "0.28.0"
nonzero_ext = "0.3.0"
parking_lot = "0.12.3"
pcap-file = "3.0.0-rc1"
pin-project = "1.1.10"
ping = "0.4.0"
pnet = "0.35.0"
proc-macro2 = "1.0.94"
prost = "0.13"
prost-types = "0.13"
pw_hash = "0.1.1"
qrcode-generator = { version = "5.0.0", default-features = false }
quote = "1.0.39"
rand = "0.9.0"
regex = "1.11.1"
reqwest = { version = "0.11", default-features = false }
resvg = "0.45.1"
ring = { version = "0.17.8", default-features = false }
schemars = "0.8.22"
semver = { version = "1.0.26", features = ["serde"] }
serde = { version = "1.0.218", features = ["derive", "rc"] }
serde_json = "1.0.140"
serde_with = { version = "3.14.0", default-features = false, features = ["macros"] }
sha2 = "0.10.9"
walkdir = "2.5.0"
zip = { version = "4.3.0", default-features = false }
slint = { version = "=1.13.1", default-features = false, features = ["compat-1-2", "image-default-formats", "log", "serde", "std"] }
slint-build = "=1.13.1"
smart-leds-trait = { version = "0.3.1" }
spidev = { version = "0.7.0" }
strum = { version = "0.27", default-features = false }
strum_macros = "0.27"
svg = "0.18.0"
syn = { version = "2.0.99", features = ["extra-traits", "full"] }
sync_wrapper = "1.0.2"
sysinfo = "0.35.0"
tap = "1.0.1"
tempfile = "3.21.0"
thiserror = "2.0.12"
time = { version = "0.3.41", default-features = false }
tokio = { version = "1.47.0", features = ["full"] }
tokio-cron-scheduler = { version = "0.19.0", registry = "braiins" }
tokio-stream = { version = "0.1.17", default-features = false }
tokio-util = "0.7"
tokio-retry = "0.3.0"
tokio-test = "0.4.2"
tokio-tungstenite = "0.24.0"
tonic = "0.13.1"
tonic-build = "0.13.1"
tonic-middleware = "0.3.0"
tonic-reflection = "0.13.1"
tonic-types = "0.13.1"
tonic-web = "0.13.1"
tooling-std = { path = "tooling/tooling-std" }
tooling-std-macros = { path = "tooling/tooling-std/macros" }
tower = { version = "0.5.2", default-features = false }
tower-cookies = "0.11.0"
tower-http = "0.6.2"
tracing = { version = "0.1.41", default-features = false }
tracing-subscriber = "0.3.19"
udev = "0.9"
url = { version = "2.5.4", features = ["serde"] }
uuid = { version = "1.15.1", features = ["fast-rng", "serde", "v4"] }
ux = { version = "0.1.6" }
wl-nl80211 = "0.3.2"
sysfs_gpio = "0.6.1"
gpiod = "0.2.3"
merge-streams = "0.1.2"
netlink-packet-route = "0.20.1"
netlink-sys = "0.8.5"
rtnetlink = { git = "https://github.com/rust-netlink/rtnetlink.git", rev = "d6e8b4c" } # FIXME: change to a crates.io version after they update netlink-packet-route
