#!/bin/sh
set -e
[ -f ~/.profile ] && exit 0
cat > ~/.profile <<'EOF'
export PATH=$PATH:/run/current-profile/bin:/nix/var/nix/profiles/per-user/root/profile/bin
EOF

cat > /etc/init.d/nix-mounter <<'INITEOF'
#!/bin/sh /etc/rc.common

START=99

boot() {
    mount --bind /mnt/data/nix /nix
}
INITEOF
chmod +x /etc/init.d/nix-mounter
/etc/init.d/nix-mounter enable
