[package]
name = "bmc-wasm-thin"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
libc = { workspace = true }
signal-hook = { workspace = true }
tracing = { workspace = true }

bmc-log = { workspace = true }
bmc-wasm-thin-protocol = { path = "../bmc-wasm-thin-protocol" }
bmc-widget-protocol = { workspace = true }

[dev-dependencies]
bmc-wasm-protocol = { path = "../bmc-wasm-runtime/protocol" }
tempfile = { workspace = true }

[[test]]
name = "host_connect"
path = "tests/host_connect.rs"

[[test]]
name = "idle_signal"
path = "tests/idle_signal.rs"
