[package]
name = "bmc-wasm-thin"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
libc = { workspace = true }
nix = { workspace = true }
rustix = { workspace = true }
signal-hook = { workspace = true }
tracing = { workspace = true }

bmc-log = { workspace = true }
bmc-wasm-thin-protocol = { path = "../bmc-wasm-thin-protocol" }

[dev-dependencies]
bmc-wasm-protocol = { path = "../bmc-wasm-runtime/protocol" }
tempfile = { workspace = true }

[[bin]]
name = "bmc-wasm-thin-fakehost"
path = "src/bin/bmc-wasm-thin-fakehost.rs"

[[test]]
name = "spawn_lock"
path = "tests/spawn_lock.rs"

[[test]]
name = "idle_signal"
path = "tests/idle_signal.rs"
