[package]
name = "fleet-management"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = { version = "0.22", default-features = false, features = ["alloc"] }
bmc-wasm-sdk = { path = "../../bmc-wasm-runtime/sdk" }
units = { path = "../lib/units" }

[lints]
workspace = true
