[package]
name = "bmc-storybook-api"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
bmc-render = { path = "../../bmc-render" }
bmc-render-keyboard = { path = "../../bmc-render/keyboard" }
bmc-storybook-macros = { path = "../storybook-macros" }
bmc-wasm-sdk = { path = "../../bmc-wasm-runtime/sdk" }
inventory.workspace = true
rodio = { workspace = true, features = ["mp3", "vorbis", "wav"] }
tracing.workspace = true

[lints]
workspace = true
