[package]
name = "bmc-shared-slint"
version = "0.1.0"
edition = "2024"

[features]
# Change `embed_resources` strategy to `EmbedFiles` instead of `EmbedForSoftwareRenderer`.
# This helps to avoid indexing issues in RustRover, because generated code is much smaller.
slint-embed-files = []

[dependencies]
bmc-shared-time.workspace = true
chrono.workspace = true
slint.workspace = true

[build-dependencies]
anyhow.workspace = true
serde.workspace = true
slint-build.workspace = true

[lints]
workspace = true
