[package]
name = "bmc-widget-femtovg-demo"
version = "0.1.0"
edition = "2024"

[features]
standalone = ["slint/backend-winit", "slint/renderer-femtovg"]

[dependencies]
clap = { workspace = true, features = ["derive"] }
slint = { workspace = true, features = ["backend-winit", "renderer-femtovg"] }
tracing.workspace = true

[build-dependencies]
slint-build.workspace = true

[lints]
workspace = true
