export global Images {
    in property <image> logo: @image-url("../assets/images/logo.png");
    in property <image> back-reset-button: @image-url("../assets/images/back-reset-button.svg");
    // Clocks
    in property <image> clock-dial-round: @image-url("../assets/images/clock/clocks-dial-round.svg");
    in property <image> clock-dial-round-small: @image-url("../assets/images/clock/clocks-dial-round-small.svg");
    in property <image> clock-dial-rect-full: @image-url("../assets/images/clock/clocks-dial-rectangular-full.svg");
    in property <image> clock-dial-rect-large: @image-url("../assets/images/clock/clocks-dial-rectangular-large.svg");
    in property <image> clock-dial-rect-medium: @image-url("../assets/images/clock/clocks-dial-rectangular-medium.svg");
    in property <image> clock-dial-rect-small: @image-url("../assets/images/clock/clocks-dial-rectangular-small.svg");
    in property <image> hand-hour: @image-url("../assets/images/clock/hand-hour.svg");
    in property <image> hand-hour-rect: @image-url("../assets/images/clock/hand-hour-rect.svg");
    in property <image> hand-minute: @image-url("../assets/images/clock/hand-minute.svg");
    in property <image> hand-minute-rect: @image-url("../assets/images/clock/hand-minute-rect.svg");
    in property <image> hand-second: @image-url("../assets/images/clock/hand-second.svg");
    in property <image> hand-second-rect: @image-url("../assets/images/clock/hand-second-rect.svg");
    in property <image> center-circle-white: @image-url("../assets/images/clock/center-circle-white.svg");
    in property <image> center-circle-black: @image-url("../assets/images/clock/center-circle-black.svg");
    in property <image> center-circle-orange: @image-url("../assets/images/clock/center-circle-orange.svg");
    in property <image> center-circle-stroke: @image-url("../assets/images/clock/center-circle-stroke.svg");
    // Errors
    in property <image> tools: @image-url("../assets/images/tools.svg");
    in property <image> error_circle: @image-url("../assets/images/error_circle.svg");
    in property <image> main_checkmark: @image-url("../assets/images/main_checkmark.svg");
    // hour hand
    out property <length> hour-hand-width: hand-hour.width * 1px;
    out property <length> hour-hand-height: hand-hour.height * 1px;
    out property <length> hour-hand-rect-width: hand-hour-rect.width * 1px;
    out property <length> hour-hand-rect-height: hand-hour-rect.height * 1px;
    // minute hand
    out property <length> minute-hand-width: hand-minute.width * 1px;
    out property <length> minute-hand-height: hand-minute.height * 1px;
    out property <length> minute-hand-rect-width: hand-minute-rect.width * 1px;
    out property <length> minute-hand-rect-height: hand-minute-rect.height * 1px;
    // second hand
    out property <length> second-hand-width: hand-second.width * 1px;
    out property <length> second-hand-height: hand-second.height * 1px;
    out property <length> second-hand-rect-width: hand-second-rect.width * 1px;
    out property <length> second-hand-rect-height: hand-second-rect.height * 1px;
    // circles
    out property <length> circle-white-width: center-circle-white.width * 1px;
    out property <length> circle-white-height: center-circle-white.height * 1px;
    out property <length> circle-black-width: center-circle-black.width * 1px;
    out property <length> circle-black-height: center-circle-black.height * 1px;
    out property <length> circle-orange-width: center-circle-orange.width * 1px;
    out property <length> circle-orange-height: center-circle-orange.height * 1px;
    out property <length> circle-stroke-width: center-circle-stroke.width * 1px;
    out property <length> circle-stroke-height: center-circle-stroke.height * 1px;
    // notification
    in property <image> notification_info: @image-url("../assets/images/notification/info.svg");
    in property <image> notification_unread: @image-url("../assets/images/notification/unread.svg");
    // init setup
    in property <image> wifi-connect: @image-url("../assets/images/init_setup/wifi_connect.svg");
    in property <image> wifi: @image-url("../assets/images/init_setup/wifi.svg");
    in property <image> wifi-error: @image-url("../assets/images/init_setup/wifi_error.svg");
    in property <image> refresh-big: @image-url("../assets/images/init_setup/refresh.svg");
    in property <image> success-big: @image-url("../assets/images/init_setup/success.svg");
    in property <image> desktop: @image-url("../assets/images/init_setup/desktop.svg");
    in property <image> bmc-icon: @image-url("../assets/images/init_setup/bmc_icon.svg");
    in property <image> gradient_left_small: @image-url("../assets/images/init_setup/gradient_left_small.svg");
    in property <image> desktop-clock: @image-url("../assets/images/init_setup/desktop_clock.svg");
    // Icons
    in property <image> btc-icon: @image-url("../assets/images/btc_icon.svg");
    in property <image> close-icon: @image-url("../assets/images/close-icon.svg");
    in property <image> alarm-bell: @image-url("../assets/images/alarm-bell-icon.svg");
    in property <image> braiins-pool-favicon: @image-url("../assets/images/braiins_pool_favicon.svg");
    in property <image> payout-btc: @image-url("../assets/images/payout_btc.svg");
    in property <image> payout-ln: @image-url("../assets/images/payout_ln.svg");
    in property <image> axe: @image-url("../assets/images/icon/axe.svg");
    in property <image> chart: @image-url("../assets/images/icon/chart.svg");
    in property <image> meter: @image-url("../assets/images/icon/meter.svg");
    in property <image> cube: @image-url("../assets/images/cube.svg");
    in property <image> x: @image-url("../assets/images/icon/x.svg");
    // Workers icons
    in property <image> worker-total: @image-url("../assets/images/icon/status/workers/total.svg");
    in property <image> worker-active: @image-url("../assets/images/icon/status/workers/active.svg");
    in property <image> worker-low: @image-url("../assets/images/icon/status/workers/low.svg");
    in property <image> worker-offline: @image-url("../assets/images/icon/status/workers/offline.svg");
    // WiFi signal strenght
    in property <image> wifi-problem: @image-url("../assets/images/wifi/signal-problem.svg");
    in property <image> wifi-low: @image-url("../assets/images/wifi/signal-low.svg");
    in property <image> wifi-fair: @image-url("../assets/images/wifi/signal-fair.svg");
    in property <image> wifi-strong: @image-url("../assets/images/wifi/signal-strong.svg");
}
