export global Palette {
    // primary
    out property <brush> white: #FFFFFF;
    out property <brush> black: #000000;

    // red
    out property <brush> red-40: #FF8384;
    out property <brush> red-50: #F95355;
    out property <brush> red-60: #D9222C;
    out property <brush> red-100: #2B0B0B;

    // green
    out property <brush> green-30: #5ADF88;
    out property <brush> green-50: #13A454;
    out property <brush> green-60: #168042;
    out property <brush> green-90: #102B19;
    out property <brush> green-100: #061912;

    // blue
    out property <brush> blue-30: #A9C7FF;
    out property <brush> blue-60: #2460FF;

    // violet
    out property <brush> violet-50: #8B7CFF;
    out property <brush> violet-60: #6B50FF;

    // gray
    out property <brush> gray-20: #E0E0E0;
    out property <brush> gray-30: #C6C6C6;
    out property <brush> gray-40: #A8A8A8;
    out property <brush> gray-50: #8D8D8D;
    out property <brush> gray-60: #6F6F6F;
    out property <brush> gray-80: #393939;
    out property <brush> gray-90: #262626;
    out property <brush> gray-100: #161616;

    // orange
    out property <brush> orange-30: #FFB689;
    out property <brush> orange-40: #FE8431;
    out property <brush> orange-50: #EB6307;

    // others
    out property <brush> purple-60: #A72DEA;
    out property <brush> teal-30: #56D8E0;
}
