import "../assets/fonts/BraiinsSans-Regular.otf";  // font weight: 400
import "../assets/fonts/BraiinsSans-SemiBold.otf"; // font weight: 600
import "../assets/fonts/BraiinsSans-Bold.otf";     // font weight: 700

export global Palette {
    // primary
    out property <brush> white: #FFFFFF;
    out property <brush> black: #000000;

    // red
    out property <brush> red-50: #F95355;
    out property <brush> red-60: #D9222C;
    out property <brush> red-100: #2B0B0B;

    // green
    out property <brush> green-50: #13A454;
    out property <brush> green-60: #168042;
    out property <brush> green-100: #061912;

    // blue
    out property <brush> blue-60: #2460FF;

    // violet
    out property <brush> violet-50: #8B7CFF;
    out property <brush> violet-60: #6B50FF;

    // gray
    out property <brush> gray-20: #E0E0E0;
    out property <brush> gray-30: #C6C6C6;
    out property <brush> gray-40: #A8A8A8;
    out property <brush> gray-50: #8D8D8D;
    out property <brush> gray-80: #393939;
    out property <brush> gray-100: #161616;

    // others
    out property <brush> purple-60: #A72DEA;
    out property <brush> orange-50: #EB6307;
    out property <brush> teal-30: #56D8E0;
}
