import "../assets/fonts/BraiinsSans-Regular.otf";  // font weight: 400
import "../assets/fonts/BraiinsSans-SemiBold.otf"; // font weight: 600
import "../assets/fonts/BraiinsSans-Bold.otf";     // font weight: 700
import "../assets/fonts/BraiinsDeckSans-Regular.otf";  // font weight: 400
import "../assets/fonts/BraiinsDeckSans-SemiBold.otf"; // font weight: 600
import "../assets/fonts/BraiinsDeckSans-Bold.otf";     // font weight: 700

struct FontWeight {
    regular: int,
    semi-bold: int,
    bold: int,
}

struct FontSize {
    common: {
        default: length,
    },
}

export struct Font {
    weight: FontWeight,
    size: FontSize,
}

export global Theme {
    out property <Font> font: {
        weight: {
            regular: 400,
            semi-bold: 600,
            bold: 700,
        },
        size: {
            common: {
                default: 20px,
            },
        }
    };
}
