[package]
name = "bmc-led"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[features]
default = ["driver"]
driver = ["dep:anyhow", "dep:tokio", "dep:tracing"]
apa102_spi = [
    "driver",
    "dep:apa102-spi",
    "dep:embedded-hal",
    "dep:smart-leds-trait",
    "dep:spidev",
    "dep:ux",
]

[dependencies]
anyhow = { workspace = true, optional = true }
apa102-spi = { workspace = true, optional = true }
embedded-hal = { workspace = true, optional = true }
smart-leds-trait = { workspace = true, optional = true }
spidev = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
ux = { workspace = true, optional = true }

[lints]
workspace = true
