[package]
name = "bmc-led"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
apa102-spi.workspace = true
async-trait.workspace = true
embedded-hal.workspace = true
embedded-hal-async.workspace = true
rand.workspace = true
smart-leds-trait.workspace = true
spidev.workspace = true
tokio.workspace = true
tracing.workspace = true
ux.workspace = true

[lints]
workspace = true

