[package]
name = "bmc-openwrt"
version = "0.1.0"
edition = "2024"
authors = ["Braiins <braiins@braiins.com>"]


[dependencies]
anyhow.workspace = true
apa102-spi.workspace = true
async-stream.workspace = true
async-trait.workspace = true
axum-extra.workspace = true
bmc.workspace = true
bmc-button.workspace = true
bmc-display.workspace = true
bmc-gpio.workspace = true
bmc-kobject.workspace = true
bmc-led.workspace = true
bmc-platform.workspace = true
bmc-shared-ii-net.workspace = true
bmc-shared-ii-net-drv.workspace = true
bmc-shared-time.workspace = true
bmc-support.workspace = true
bmc-upgrade.workspace = true
bmc-widget-protocol.workspace = true
calloop.workspace = true
clap.workspace = true
drm.workspace = true
drm-fourcc.workspace = true
embedded-hal.workspace = true
embedded-hal-async.workspace = true
evdev.workspace = true
file-rotate.workspace = true
flume.workspace = true
futures.workspace = true
get_if_addrs.workspace = true
gpiod.workspace = true
iana-time-zone.workspace = true
ii-stopwatch.workspace = true
log.workspace = true
memmap2.workspace = true
merge-streams.workspace = true
netlink-sys = { workspace = true, features = ["tokio_socket"] }
pnet.workspace = true
pw_hash.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
slint = { workspace = true, features = ["renderer-software"] }
smart-leds-trait.workspace = true
smithay.workspace = true
spidev.workspace = true
sysfs_gpio = { workspace = true, features = ["async-tokio"] }
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url.workspace = true
ux.workspace = true

[features]
profiling = ["ii-stopwatch/enabled"]

[lints]
workspace = true
