[package]
name = "bmc-openwrt"
version = "0.1.0"
edition = "2024"
authors = ["Braiins <braiins@braiins.com>"]


[dependencies]
anyhow.workspace = true
async-stream.workspace = true
async-trait.workspace = true
axum-extra.workspace = true
bmc.workspace = true
bmc-button.workspace = true
bmc-gpio.workspace = true
bmc-gpu-render-lock.workspace = true
bmc-kobject.workspace = true
bmc-led = { workspace = true, features = ["apa102_spi"] }
bmc-log.workspace = true
bmc-platform = { workspace = true, features = ["backlight", "linux-input"] }
bmc-shared-ii-net.workspace = true
bmc-shared-ii-net-drv.workspace = true
bmc-shared-time.workspace = true
bmc-support.workspace = true
bmc-widget-protocol.workspace = true
calloop.workspace = true
clap.workspace = true
deck-screen-edge-v1 = { workspace = true }
drm.workspace = true
flume.workspace = true
futures.workspace = true
get_if_addrs.workspace = true
gpiod.workspace = true
iana-time-zone.workspace = true
ii-stopwatch.workspace = true
input.workspace = true
libc.workspace = true
log.workspace = true
merge-streams.workspace = true
netlink-sys = { workspace = true, features = ["tokio_socket"] }
pw_hash.workspace = true
serde.workspace = true
serde_json.workspace = true
smithay.workspace = true
sysfs_gpio = { workspace = true, features = ["async-tokio"] }
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true

[features]
profiling = ["ii-stopwatch/enabled"]

[lints]
workspace = true
