[package]
name = "bmc-upgrade"
version = "0.1.0"
edition = "2024"
authors = ["Braiins <braiins@braiins.com>"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bmc-grpc = { workspace = true, features = ["server"] }
bmc-platform.workspace = true
bmc-scheduler.workspace = true
bmc-shared-time.workspace = true
bytes.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
croner.workspace = true
data-encoding.workspace = true
index-bmc.workspace = true
index-common.workspace = true
minerctl-defs.workspace = true
rand.workspace = true
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
ring.workspace = true
serde = { workspace = true, features = ["derive"] }
sysinfo = { workspace = true, features = ["linux-tmpfs"], optional = true }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

[features]
disk-check = ["sysinfo"]

[lints]
workspace = true
