import { Images } from "../../style/images.slint";
import { Palette } from "../../style/palette.slint";
import { Theme } from "../../style/theme.slint";
import { UpgradeDownloadAdapter } from "../../controls/adapters.slint";

import { ProgressIndicator } from "std-widgets.slint";

export component UpgradeDownload inherits Rectangle {
    background: Palette.black;
    in property <string> icon_text_content;
    VerticalLayout {
        padding-left: 120px;
        padding-right: 120px;
        spacing: 15px;
        alignment: center;
        HorizontalLayout {
            padding-top: 40px;
            padding-bottom: 15px;
            alignment: center;
            Rectangle {
                width: 80px;
                height: 80px;
                Image {
                    visible: true;
                    source: Images.tools;
                }
            }
        }

        Text {
            text: UpgradeDownloadAdapter.progress_text;
            color: Palette.white;
            font-size: 18px;
            font-weight: Theme.font.weight.regular;
            horizontal-alignment: center;
        }

        ProgressIndicator {
            height: 7px;
            progress: UpgradeDownloadAdapter.progress * 100%;
        }

        Text {
            text: UpgradeDownloadAdapter.downloaded_mb_text;
            color: Palette.gray-50;
            font-size: 18px;
            font-weight: Theme.font.weight.regular;
            horizontal-alignment: center;
        }
    }
}
