import { Palette } from "../style/palette.slint";

export component CircleIcon inherits Rectangle {
    in property <image> icon_source;
    in property <brush> circle_color: @linear-gradient(176deg, rgba(255, 255, 255, 0.30) 3.1%, rgba(255, 255, 255, 0.18) 98.54%);
    in property <brush> circle_color_pressed: @linear-gradient(176deg, rgba(255, 255, 255, 0.90) 3.1%, rgba(255, 255, 255, 0.54) 98.54%);
    in property <color> icon_color: Palette.white;
    in property <color> icon_color_pressed: Palette.black;
    in property <bool> disable_pressed_color: false;
    property <bool> is_pressed: touch.pressed;

    callback clicked;

    width: 112px;
    height: 112px;

    Rectangle {
        width: root.width;
        height: root.height;
        border-radius: self.width / 2;
        background: root.disable_pressed_color ? root.circle_color : root.is_pressed ? root.circle_color_pressed : root.circle_color;
    }

    Image {
        source: root.icon_source;
        x: (root.width - self.width) / 2;
        y: (root.height - self.height) / 2;
        colorize: root.is_pressed ? root.icon_color_pressed : root.icon_color;
    }

    touch := TouchArea {
        width: root.width;
        height: root.height;

        clicked => {
            root.clicked();
        }

        pointer-event(event) => {
            // Consume all pointer events to prevent them from propagating to parent TouchAreas
            return EventResult.accept;
        }
    }
}
