
export component Ring inherits Rectangle {
    // Properties provided from the parent
    in property <int> index;
    in property <int> ring_count;
    in property <duration> period;
    in property <duration> t_base;
    in property <length> start_r;
    in property <length> end_r;
    in property <length> fade_distance;
    in property <length> parent_width;
    in property <length> parent_height;

    // Internal properties
    property <duration> tt: mod(self.t_base + (self.index / self.ring_count) * self.period, self.period);
    property <float> p:  self.tt / self.period;
    property <length> r:  self.start_r + self.p * (self.end_r - self.start_r);
    property <length> d:  self.r - self.start_r;
    property <float> a:  max(0.0, 1.0 - (self.d / self.fade_distance));

    width: self.r * 2;
    height: self.width;
    x: (self.parent_width - self.width) / 2;
    y: (self.parent_height - self.height) / 2;
    border-width: 2px;
    border-color: rgba(254, 132, 49, self.a);
    border-radius: self.width / 2;
}
