import { UIScreen } from "common.slint";

export global UpgradeDownloadAdapter {
    in property <float> progress: 0.0;
    in property <string> progress_text: "Downloading firmware 0%...";
    in property <string> downloaded_mb_text: "0 MB of 0 MB";
}

export global ScreenAdapter {
    in property <UIScreen> screen-id: UIScreen.Void;
}

export global NotificationAdapter {
    in property <string> label: "LABEL";
    in property <string> message: "MESSAGE";
    in property <string> timestamp: "TIMESTAMP";
}

export global InitSetupWifiAdapter {
    in property <string> ssid;
}

export global ConnectionAdapter {
    in property <string> ip;
    in property <image> ip_qr_code;
}
