import { InitScreen, ConnectInfoScreen, UpgradeScreen, DateTime, SignalStrength } from "common.slint";

export global UpgradeDownloadAdapter {
    in property <float> progress: 0.0;
    in property <string> progress_text: "Downloading firmware 0%...";
    in property <string> downloaded_mb_text: "0 MB of 0 MB";
}

export global ScreenAdapter {
    in property <bool> scene-cycler;
    in property <UpgradeScreen> upgrade;
    in property <ConnectInfoScreen> connect-info;
    in property <bool> clock-alarm;
    in property <InitScreen> init;
}

export global StatusOverlayAdapter {
    in property <bool> has_unread_notification;
    in property <bool> is_wifi_offline;
}

export global NotificationAdapter {
    in property <string> label: "LABEL";
    in property <string> message: "MESSAGE";
    in property <string> timestamp: "TIMESTAMP";
}

export global WifiAdapter {
    in property <string> ssid;
    in property <SignalStrength> signal_strength;
    in property <string> ap_ip;
    in property <image> ap_ip_qr_code;
}

export global ConnectionAdapter {
    in property <string> ip;
    in property <image> ip_qr_code;
}

export global BitcoinAdapter {
    in property <string> price: "--";
    in property <string> price_change: "--";
    in property <bool> price_increase: false;
}

export global BlockHeightAdapter {
    in property <string> block-height: "--";
    in property <string> timestamp: "--";
}

export global DifficultyAdapter {
    in property <string> difficulty;
    in property <string> blocks-epoch;
    in property <string> epoch-block-time;
    in property <bool> prev-adjustment-increase;
    in property <string> prev-adjustment-change;
    in property <string> prev-adjustment-time;
    in property <bool> next-adjustment-increase;
    in property <string> next-adjustment-change;
    in property <string> next-adjustment-time;
}

export global HashrateAdapter {
    in property <string> avg-fees-per-block;
    in property <string> fees-percent;
    in property <string> current-hashrate;
    in property <string> hashprice;
    in property <string> total-revenue;
}

export global AlarmAdapter {
    in property <string> label;
    in property <bool> snooze-visible;
    in property <DateTime> next-alarm-time;
    in property <bool> next-alarm-is-defined;
    callback stop_alarm;
    callback snooze_alarm;
}

export global BrightnessAdapter {
    in property <int> brightness: 0;
    callback brightness_increase;
    callback brightness_decrease;
}

export global SoundAdapter {
    in property <int> volume: 0;
    callback volume_increase;
    callback volume_decrease;
}

export global NightModeAdapter {
    in property <bool> is-active: false;
    in property <string> status-text;
    callback toggle;
}

export global WifiReconfigAdapter {
    callback trigger_reconfig;
}
