export enum InitScreen {
    None,
    StartConnect,
    WifiConnectProgress,
    WifiConnectSuccess,
    WifiConnectFailed,
    SetupSuccess,
    GeneralError,
    DeviceSetupQr,
}

export enum ConnectInfoScreen {
    None,
    ConnectInfo,
    WifiConnectProgress,
    WifiConnectFailed
}

export enum UpgradeScreen {
    None,
    Download,
    Progress,
    Success,
    Failed
}

export struct DateTime {
    is-24-format: bool,
    hour24: int,
    hour12: int,
    is-pm: bool,
    minute: int,
    second: int,
    day: int,
    month: int,
    month-name: string,
    year: int,
    weekday: string,
    time-sec-24: string,
    time-sec-12: string,
    time-24: string,
    time-12: string,
    date: string,
    timezone: string,
}

export enum SignalStrength {
    Offline,
    Low,
    Fair,
    Strong,
}
