import { Scene } from "../widgets/scene.slint";
import { WidgetBuilder } from "widget-builder.slint";

export enum SceneCyclingTransition {
    Slide,
    Fade
}

export global SceneCyclingAdapter {
    in property <bool> automatic-cycling-enabled;
    in property <duration> automatic-cycling-default-duration;
    in property <SceneCyclingTransition> transition;
}

component SwipeHandler inherits Rectangle {
    in property <bool> enabled <=> swipe.enabled;
    in property <length> min-swipe-distance: self.width / 4;
    in property <bool> allow-swipe-right <=> swipe.handle-swipe-right;
    in property <bool> allow-swipe-left <=> swipe.handle-swipe-left;
    out property <bool> swiping <=> swipe.swiping;
    out property <Point> current-position <=> swipe.current-position;
    out property <Point> pressed-position <=> swipe.pressed-position;

    callback swiped_left();
    callback swiped_right();

    public function cancel() {
        swipe.cancel();
    }

    swipe := SwipeGestureHandler {
        swiped => {
            if (self.current-position.x > (self.pressed-position.x + root.min-swipe-distance)) {
                root.swiped_right();
            } else if (self.current-position.x < (self.pressed-position.x - root.min-swipe-distance)) {
                root.swiped_left();
            }
        }

        @children
    }
}

component AutomaticSceneCycler {
    in property <bool> enabled: true;
    in property <duration> duration;
    in property <int> scenes-count;
    in-out property <int> scene-index;

    changed scene-index => {
        if enabled {
          timer.restart();
        }
    }

    timer := Timer {
        in-out property <bool> restarting;

        running: !self.restarting && (root.enabled && root.scenes-count > 1);
        interval: Math.max(root.duration, 1s);

        public function restart() {
            self.restarting = true;

            // Run timer to revert self.restarting back to false in the next event loop cycle.
            // This is something like `setTimeout(callback, 0)` in JavaScript.
            restart_workaround_timer.running = true;
        }

        triggered() => {
            root.scene-index = Math.mod(root.scene-index + 1, root.scenes-count);
        }
    }

    // this is needed until https://github.com/slint-ui/slint/pull/8821 is released
    restart_workaround_timer := Timer {
        // triggered manually from timer.restart()
        running: false;
        interval: 0ms;

        triggered => {
            timer.restarting = false;

            // run only once when requested
            self.running = false;
        }
    }
}

component SceneCyclerSlide inherits Rectangle {
    in property <bool> enabled: true;
    in property <[Scene]> scenes;
    in-out property <int> scene-index;
    out property <bool> user-interacting <=> swipe.swiping;

    changed scene-index => {
        swipe.cancel();
    }

    swipe := SwipeHandler {
        enabled: root.enabled;
        allow-swipe-right: root.scene-index > 0;
        allow-swipe-left: root.scene-index < root.scenes.length - 1;

        swiped_left => {
            root.scene-index = Math.mod(root.scene-index + 1, root.scenes.length);
        }

        swiped_right => {
            root.scene-index = Math.mod(root.scene-index - 1, root.scenes.length);
        }

        HorizontalLayout {
            property <length> position: -(root.scene-index * root.width);
            animate position {
                duration: 300ms;
                easing: ease-in-out;
            }

            property <length> swipe-offset;
            x: position + swipe-offset;

            states [
                swiping when swipe.swiping: {
                    swipe-offset: swipe.current-position.x - swipe.pressed-position.x;
                    out {
                        animate swipe-offset {
                            duration: 300ms;
                            easing: ease-in-out;
                        }
                    }
                }
            ]

            for scene in root.scenes: WidgetBuilder {
                width: root.width;
                height: root.height;
                scene_id: scene.id;
                widgets: scene.widgets;
            }
        }
    }
}

component SceneCyclerFade inherits Rectangle {
    in property <bool> enabled: true;
    in property <[Scene]> scenes;
    in-out property <int> scene-index;
    out property <bool> user-interacting <=> swipe.swiping;

    changed scene-index => {
        swipe.cancel();
    }

    swipe := SwipeHandler {
        enabled: root.enabled;
        allow-swipe-right: root.scene-index > 0;
        allow-swipe-left: root.scene-index < root.scenes.length - 1;

        swiped_left => {
            root.scene-index = Math.mod(root.scene-index + 1, root.scenes.length);
        }

        swiped_right => {
            root.scene-index = Math.mod(root.scene-index - 1, root.scenes.length);
        }

        for scene[index] in root.scenes: WidgetBuilder {
            width: root.width;
            height: root.height;
            scene_id: scene.id;
            widgets: scene.widgets;
            opacity: 0;
            visible: false;

            states [
                active when root.scene-index == index: {
                    visible: true;
                    opacity: 1;
                    in {
                        animate opacity { duration: 250ms; }
                    }
                    out {
                        animate opacity { duration: 250ms; }
                    }
                }
            ]
        }
    }
}

export component SceneCycler inherits Rectangle {
    in property <bool> enabled: true;
    in property <bool> automatic-enabled: true;
    in property <[Scene]> scenes;
    in-out property <int> scene-index;
    property <bool> user-interacting;

    AutomaticSceneCycler {
        enabled: root.enabled && root.automatic-enabled && SceneCyclingAdapter.automatic-cycling-enabled && !root.user-interacting;
        duration: {
            if root.scenes[root.scene-index].cycle-duration > 0 {
                root.scenes[root.scene-index].cycle-duration
            } else {
                SceneCyclingAdapter.automatic-cycling-default-duration
            }
        };
        scenes-count: root.scenes.length;
        scene-index <=> root.scene-index;
    }

    if SceneCyclingAdapter.transition == SceneCyclingTransition.Slide: SceneCyclerSlide {
        enabled: root.enabled;
        scenes: root.scenes;
        scene-index <=> root.scene-index;

        init => {
            root.user-interacting = self.user-interacting;
        }

        changed user-interacting => {
            root.user-interacting = self.user-interacting;
        }
    }

    if SceneCyclingAdapter.transition == SceneCyclingTransition.Fade: SceneCyclerFade {
        enabled: root.enabled;
        scenes: root.scenes;
        scene-index <=> root.scene-index;

        init => {
            root.user-interacting = self.user-interacting;
        }

        changed user-interacting => {
            root.user-interacting = self.user-interacting;
        }
    }
}
