import { Images } from "../style/images.slint";
import { Palette } from "../style/palette.slint";
import { Theme } from "../style/theme.slint";
import { StandardButton } from "std-widgets.slint";
import { StatusOverlayAdapter } from "./adapters.slint";

component StatusBarItem {
    callback clicked <=> ta.clicked;

    ta := TouchArea { }

    Rectangle {
        background: Palette.black;

        // NOTE: padding works only on *Layout components (see https://github.com/slint-ui/slint/issues/8829#issuecomment-3026695648)
        HorizontalLayout {
            padding: 8px;

            @children
        }
    }
}

export component StatusBar {
    callback wifi_offline_clicked();

    // stop touch propagation (https://github.com/slint-ui/slint/discussions/8044)
    ta := TouchArea { }

    // NOTE: this is used to draw item separators, because *Layout does not have background property
    // and Rectangle does not have border-left/border-right properties
    Rectangle {
        background: Palette.gray-90;

        HorizontalLayout {
            spacing: 1px;

            if StatusOverlayAdapter.has_unread_notification: StatusBarItem {
                Image {
                    source: Images.notification_unread;
                }
            }

            if StatusOverlayAdapter.is_wifi_offline: StatusBarItem {
                clicked => {
                    root.wifi_offline_clicked();
                }

                HorizontalLayout {
                    padding-left: 16px;
                    padding-right: 16px;

                    Text {
                        text: "OFFLINE";
                        color: Palette.red-50;
                        font-size: 16px;
                        font-weight: Theme.font.weight.semi-bold;
                    }
                }
            }
        }
    }
}

export component StatusOverlay {
    preferred-width: 100%;
    preferred-height: 100%;

    bar := StatusBar {
        x: root.width - self.width;
        y: root.height - self.height;

        wifi_offline_clicked => {
            wifi_offline_popup.visible = true;
        }
    }

    wifi_offline_popup := Rectangle {
        x: 0;
        y: 0;
        width: root.width;
        height: root.height;
        visible: false;

        // stop touch propagation (https://github.com/slint-ui/slint/discussions/8044)
        ta := TouchArea {
            enabled: root.visible;
        }

        Rectangle {
            background: Palette.black;

            Rectangle {
                x: root.width - self.width;
                y: 0;
                width: 44px;
                height: 44px;
                border-color: Palette.gray-90;
                border-width: 1px;

                Image {
                    source: Images.close-icon;
                }

                TouchArea {
                    clicked => {
                        wifi_offline_popup.visible = false;
                    }
                }
            }

            VerticalLayout {
                width: 866px;
                height: 346px;
                spacing: 32px;

                Image {
                    source: Images.back-reset-button;
                }

                Text {
                    text: "First, check your router connection or signal range. If the issue continues, press and hold the reset button (back of device) for 8 seconds to reset to factory settings, then reconfigure your Wi-Fi.";
                    color: Palette.white;
                    font-size: 24px;
                    font-weight: Theme.font.weight.regular;
                    horizontal-alignment: center;
                    wrap: word-wrap;
                }
            }
        }
    }
}
