import { WidgetContainer, WidgetSlint, WidgetType } from "../widgets/widget.slint";
import { WidgetClockAnalogRound } from "../widgets/categories/clock.slint";

export component WidgetBuilder {
    in property <[WidgetSlint]> widgets;

    for widget[index] in widgets: WidgetContainer {
        size: widget.widget-size;
        position-row: widget.row;
        position-col: widget.col;
        visible: true;
        //
        if widget.widget-type == WidgetType.ClockAnalogRound: WidgetClockAnalogRound {
            widget-size: widget.widget-size;
        }
        // Conditions for other Widgets ...
    }
}
