import { WidgetContainer, WidgetSlint, WidgetType } from "../widgets/widget.slint";
import { WidgetClockAnalogRound, WidgetClockAnalogRect, WidgetClockDigital } from "../widgets/categories/clock.slint";

export component WidgetBuilder inherits Rectangle {
    in property <[WidgetSlint]> widgets;

    for widget[index] in widgets: WidgetContainer {
        size: widget.widget-size;
        position-row: widget.row;
        position-col: widget.col;
        visible: true;
        //
        if widget.widget-type == WidgetType.ClockAnalogRound: WidgetClockAnalogRound {
            widget-size: widget.widget-size;
            timezone: widget.widget-data;
        }
        if widget.widget-type == WidgetType.ClockAnalogRect: WidgetClockAnalogRect {
            widget-size: widget.widget-size;
            timezone: widget.widget-data;
        }
        if widget.widget-type == WidgetType.ClockDigital: WidgetClockDigital {
            widget-size: widget.widget-size;
            timezone: widget.widget-data;
        }
    }
}
