import { WidgetContainer, Widget, WidgetKind } from "../widgets/widget.slint";
import { WidgetClockAnalogRound, WidgetClockAnalogRect, WidgetClockDigital } from "../widgets/categories/clock.slint";

export component WidgetBuilder inherits Rectangle {
    in property <[Widget]> widgets;

    for widget[index] in widgets: WidgetContainer {
        size: widget.size;
        position-row: widget.row;
        position-col: widget.col;
        visible: true;
        //
        if widget.kind == WidgetKind.ClockAnalogRound: WidgetClockAnalogRound {
            size: widget.size;
            timezone: widget.widget-data;
        }
        if widget.kind == WidgetKind.ClockAnalogRect: WidgetClockAnalogRect {
            size: widget.size;
            timezone: widget.widget-data;
        }
        if widget.kind == WidgetKind.ClockDigital: WidgetClockDigital {
            size: widget.size;
            timezone: widget.widget-data;
        }
    }
}
