[package]
name = "bmc-wasm-sdk-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
bmc-icon-compiler = { path = "../icon-compiler" }
proc-macro2 = "1"
quote = "1"
syn = "2"

[lints.rust]
unused_must_use = "deny"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
doc_markdown = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"

# Keep this crate out of the main workspace
[workspace]
