[package]
name = "bmc-storybook-stories"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
toml.workspace = true

[dependencies]
bmc-render-keyboard = { path = "../../bmc-render/keyboard" }
bmc-render-skin = { path = "../../bmc-render/skin" }
bmc-storybook-api = { path = "../api" }
bmc-wasm-sdk = { path = "../../bmc-wasm-runtime/sdk" }
inventory.workspace = true

[lints]
workspace = true
