[package]
name = "bmc-mock-display"
version = "0.1.0"
edition = "2024"

[features]
winit = ["slint/backend-winit", "slint/renderer-winit-software"]
slint-embed-files = ["bmc-display/slint-embed-files"]

[dependencies]
anyhow.workspace = true
bmc-display.workspace = true
bmc-shared-time.workspace = true
chrono.workspace = true
flume.workspace = true
minifb.workspace = true
slint = { workspace = true, features = ["renderer-software"] }
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
