[package]
name = "bmc-mock-display"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
bmc-display.workspace = true
slint = { workspace = true, features = ["backend-winit", "renderer-winit-software"] }
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
