[package]
name = "bmc-display"
version = "0.1.0"
edition = "2024"

[features]
# Change `embed_resources` strategy to `EmbedFiles` instead of `EmbedForSoftwareRenderer`.
# This helps to avoid indexing issues in RustRover, because generated code is much smaller.
slint-embed-files = []

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bmc-shared-time.workspace = true
chrono.workspace = true
flume.workspace = true
humantime-serde.workspace = true
indexmap.workspace = true
num-format.workspace = true
qrcode-generator.workspace = true
resvg.workspace = true
serde.workspace = true
serde_json.workspace = true
slint.workspace = true
svg.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream = { workspace = true, features = ["sync", "time"] }
tracing.workspace = true
uuid.workspace = true

[build-dependencies]
anyhow.workspace = true
slint-build.workspace = true

[lints]
workspace = true
