// Copyright (C) 2025  Braiins Systems s.r.o.

use crate::time::Timezone;
use std::sync::LazyLock;

/// This array was taken from openwrt supported timezone variants
/// https://github.com/openwrt/luci/blob/05c7844389e36385aa64549a3cc449b9d1a552e7/modules/luci-base/ucode/zoneinfo.uc
pub(crate) static TIMEZONE_VARIANTS: LazyLock<Vec<Timezone>> = LazyLock::new(|| {
    vec![
        Timezone::new("Africa/Abidjan", "GMT0"),
        Timezone::new("Africa/Accra", "GMT0"),
        Timezone::new("Africa/Addis Ababa", "EAT-3"),
        Timezone::new("Africa/Algiers", "CET-1"),
        Timezone::new("Africa/Asmara", "EAT-3"),
        Timezone::new("Africa/Bamako", "GMT0"),
        Timezone::new("Africa/Bangui", "WAT-1"),
        Timezone::new("Africa/Banjul", "GMT0"),
        Timezone::new("Africa/Bissau", "GMT0"),
        Timezone::new("Africa/Blantyre", "CAT-2"),
        Timezone::new("Africa/Brazzaville", "WAT-1"),
        Timezone::new("Africa/Bujumbura", "CAT-2"),
        Timezone::new("Africa/Cairo", "EET-2EEST,M4.5.5/0,M10.5.4/24"),
        Timezone::new("Africa/Casablanca", "XXX-2<+01>-1,0/0,J365/23"),
        Timezone::new("Africa/Ceuta", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Africa/Conakry", "GMT0"),
        Timezone::new("Africa/Dakar", "GMT0"),
        Timezone::new("Africa/Dar es Salaam", "EAT-3"),
        Timezone::new("Africa/Djibouti", "EAT-3"),
        Timezone::new("Africa/Douala", "WAT-1"),
        Timezone::new("Africa/El Aaiun", "XXX-2<+01>-1,0/0,J365/23"),
        Timezone::new("Africa/Freetown", "GMT0"),
        Timezone::new("Africa/Gaborone", "CAT-2"),
        Timezone::new("Africa/Harare", "CAT-2"),
        Timezone::new("Africa/Johannesburg", "SAST-2"),
        Timezone::new("Africa/Juba", "CAT-2"),
        Timezone::new("Africa/Kampala", "EAT-3"),
        Timezone::new("Africa/Khartoum", "CAT-2"),
        Timezone::new("Africa/Kigali", "CAT-2"),
        Timezone::new("Africa/Kinshasa", "WAT-1"),
        Timezone::new("Africa/Lagos", "WAT-1"),
        Timezone::new("Africa/Libreville", "WAT-1"),
        Timezone::new("Africa/Lome", "GMT0"),
        Timezone::new("Africa/Luanda", "WAT-1"),
        Timezone::new("Africa/Lubumbashi", "CAT-2"),
        Timezone::new("Africa/Lusaka", "CAT-2"),
        Timezone::new("Africa/Malabo", "WAT-1"),
        Timezone::new("Africa/Maputo", "CAT-2"),
        Timezone::new("Africa/Maseru", "SAST-2"),
        Timezone::new("Africa/Mbabane", "SAST-2"),
        Timezone::new("Africa/Mogadishu", "EAT-3"),
        Timezone::new("Africa/Monrovia", "GMT0"),
        Timezone::new("Africa/Nairobi", "EAT-3"),
        Timezone::new("Africa/Ndjamena", "WAT-1"),
        Timezone::new("Africa/Niamey", "WAT-1"),
        Timezone::new("Africa/Nouakchott", "GMT0"),
        Timezone::new("Africa/Ouagadougou", "GMT0"),
        Timezone::new("Africa/Porto-Novo", "WAT-1"),
        Timezone::new("Africa/Sao Tome", "GMT0"),
        Timezone::new("Africa/Tripoli", "EET-2"),
        Timezone::new("Africa/Tunis", "CET-1"),
        Timezone::new("Africa/Windhoek", "CAT-2"),
        Timezone::new("America/Adak", "HST10HDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Anchorage", "AKST9AKDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Anguilla", "AST4"),
        Timezone::new("America/Antigua", "AST4"),
        Timezone::new("America/Araguaina", "<-03>3"),
        Timezone::new("America/Argentina/Buenos Aires", "<-03>3"),
        Timezone::new("America/Argentina/Catamarca", "<-03>3"),
        Timezone::new("America/Argentina/Cordoba", "<-03>3"),
        Timezone::new("America/Argentina/Jujuy", "<-03>3"),
        Timezone::new("America/Argentina/La Rioja", "<-03>3"),
        Timezone::new("America/Argentina/Mendoza", "<-03>3"),
        Timezone::new("America/Argentina/Rio Gallegos", "<-03>3"),
        Timezone::new("America/Argentina/Salta", "<-03>3"),
        Timezone::new("America/Argentina/San Juan", "<-03>3"),
        Timezone::new("America/Argentina/San Luis", "<-03>3"),
        Timezone::new("America/Argentina/Tucuman", "<-03>3"),
        Timezone::new("America/Argentina/Ushuaia", "<-03>3"),
        Timezone::new("America/Aruba", "AST4"),
        Timezone::new("America/Asuncion", "<-03>3"),
        Timezone::new("America/Atikokan", "EST5"),
        Timezone::new("America/Bahia", "<-03>3"),
        Timezone::new("America/Bahia Banderas", "CST6"),
        Timezone::new("America/Barbados", "AST4"),
        Timezone::new("America/Belem", "<-03>3"),
        Timezone::new("America/Belize", "CST6"),
        Timezone::new("America/Blanc-Sablon", "AST4"),
        Timezone::new("America/Boa Vista", "<-04>4"),
        Timezone::new("America/Bogota", "<-05>5"),
        Timezone::new("America/Boise", "MST7MDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Cambridge Bay", "MST7MDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Campo Grande", "<-04>4"),
        Timezone::new("America/Cancun", "EST5"),
        Timezone::new("America/Caracas", "<-04>4"),
        Timezone::new("America/Cayenne", "<-03>3"),
        Timezone::new("America/Cayman", "EST5"),
        Timezone::new("America/Chicago", "CST6CDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Chihuahua", "CST6"),
        Timezone::new("America/Ciudad Juarez", "MST7MDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Costa Rica", "CST6"),
        Timezone::new("America/Coyhaique", "<-03>3"),
        Timezone::new("America/Creston", "MST7"),
        Timezone::new("America/Cuiaba", "<-04>4"),
        Timezone::new("America/Curacao", "AST4"),
        Timezone::new("America/Danmarkshavn", "GMT0"),
        Timezone::new("America/Dawson", "MST7"),
        Timezone::new("America/Dawson Creek", "MST7"),
        Timezone::new("America/Denver", "MST7MDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Detroit", "EST5EDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Dominica", "AST4"),
        Timezone::new("America/Edmonton", "MST7MDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Eirunepe", "<-05>5"),
        Timezone::new("America/El Salvador", "CST6"),
        Timezone::new("America/Fort Nelson", "MST7"),
        Timezone::new("America/Fortaleza", "<-03>3"),
        Timezone::new("America/Glace Bay", "AST4ADT,M3.2.0,M11.1.0"),
        Timezone::new("America/Goose Bay", "AST4ADT,M3.2.0,M11.1.0"),
        Timezone::new("America/Grand Turk", "EST5EDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Grenada", "AST4"),
        Timezone::new("America/Guadeloupe", "AST4"),
        Timezone::new("America/Guatemala", "CST6"),
        Timezone::new("America/Guayaquil", "<-05>5"),
        Timezone::new("America/Guyana", "<-04>4"),
        Timezone::new("America/Halifax", "AST4ADT,M3.2.0,M11.1.0"),
        Timezone::new("America/Havana", "CST5CDT,M3.2.0/0,M11.1.0/1"),
        Timezone::new("America/Hermosillo", "MST7"),
        Timezone::new("America/Indiana/Indianapolis", "EST5EDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Indiana/Knox", "CST6CDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Indiana/Marengo", "EST5EDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Indiana/Petersburg", "EST5EDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Indiana/Tell City", "CST6CDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Indiana/Vevay", "EST5EDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Indiana/Vincennes", "EST5EDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Indiana/Winamac", "EST5EDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Inuvik", "MST7MDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Iqaluit", "EST5EDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Jamaica", "EST5"),
        Timezone::new("America/Juneau", "AKST9AKDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Kentucky/Louisville", "EST5EDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Kentucky/Monticello", "EST5EDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Kralendijk", "AST4"),
        Timezone::new("America/La Paz", "<-04>4"),
        Timezone::new("America/Lima", "<-05>5"),
        Timezone::new("America/Los Angeles", "PST8PDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Lower Princes", "AST4"),
        Timezone::new("America/Maceio", "<-03>3"),
        Timezone::new("America/Managua", "CST6"),
        Timezone::new("America/Manaus", "<-04>4"),
        Timezone::new("America/Marigot", "AST4"),
        Timezone::new("America/Martinique", "AST4"),
        Timezone::new("America/Matamoros", "CST6CDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Mazatlan", "MST7"),
        Timezone::new("America/Menominee", "CST6CDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Merida", "CST6"),
        Timezone::new("America/Metlakatla", "AKST9AKDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Mexico City", "CST6"),
        Timezone::new("America/Miquelon", "<-03>3<-02>,M3.2.0,M11.1.0"),
        Timezone::new("America/Moncton", "AST4ADT,M3.2.0,M11.1.0"),
        Timezone::new("America/Monterrey", "CST6"),
        Timezone::new("America/Montevideo", "<-03>3"),
        Timezone::new("America/Montserrat", "AST4"),
        Timezone::new("America/Nassau", "EST5EDT,M3.2.0,M11.1.0"),
        Timezone::new("America/New York", "EST5EDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Nome", "AKST9AKDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Noronha", "<-02>2"),
        Timezone::new("America/North Dakota/Beulah", "CST6CDT,M3.2.0,M11.1.0"),
        Timezone::new("America/North Dakota/Center", "CST6CDT,M3.2.0,M11.1.0"),
        Timezone::new("America/North Dakota/New Salem", "CST6CDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Nuuk", "<-02>2<-01>,M3.5.0/-1,M10.5.0/0"),
        Timezone::new("America/Ojinaga", "CST6CDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Panama", "EST5"),
        Timezone::new("America/Paramaribo", "<-03>3"),
        Timezone::new("America/Phoenix", "MST7"),
        Timezone::new("America/Port of Spain", "AST4"),
        Timezone::new("America/Port-au-Prince", "EST5EDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Porto Velho", "<-04>4"),
        Timezone::new("America/Puerto Rico", "AST4"),
        Timezone::new("America/Punta Arenas", "<-03>3"),
        Timezone::new("America/Rankin Inlet", "CST6CDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Recife", "<-03>3"),
        Timezone::new("America/Regina", "CST6"),
        Timezone::new("America/Resolute", "CST6CDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Rio Branco", "<-05>5"),
        Timezone::new("America/Santarem", "<-03>3"),
        Timezone::new("America/Santiago", "<-04>4<-03>,M9.1.6/24,M4.1.6/24"),
        Timezone::new("America/Santo Domingo", "AST4"),
        Timezone::new("America/Sao Paulo", "<-03>3"),
        Timezone::new("America/Scoresbysund", "<-02>2<-01>,M3.5.0/-1,M10.5.0/0"),
        Timezone::new("America/Sitka", "AKST9AKDT,M3.2.0,M11.1.0"),
        Timezone::new("America/St Barthelemy", "AST4"),
        Timezone::new("America/St Johns", "NST3:30NDT,M3.2.0,M11.1.0"),
        Timezone::new("America/St Kitts", "AST4"),
        Timezone::new("America/St Lucia", "AST4"),
        Timezone::new("America/St Thomas", "AST4"),
        Timezone::new("America/St Vincent", "AST4"),
        Timezone::new("America/Swift Current", "CST6"),
        Timezone::new("America/Tegucigalpa", "CST6"),
        Timezone::new("America/Thule", "AST4ADT,M3.2.0,M11.1.0"),
        Timezone::new("America/Tijuana", "PST8PDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Toronto", "EST5EDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Tortola", "AST4"),
        Timezone::new("America/Vancouver", "PST8PDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Whitehorse", "MST7"),
        Timezone::new("America/Winnipeg", "CST6CDT,M3.2.0,M11.1.0"),
        Timezone::new("America/Yakutat", "AKST9AKDT,M3.2.0,M11.1.0"),
        Timezone::new("Antarctica/Casey", "<+08>-8"),
        Timezone::new("Antarctica/Davis", "<+07>-7"),
        Timezone::new("Antarctica/DumontDUrville", "<+10>-10"),
        Timezone::new("Antarctica/Macquarie", "AEST-10AEDT,M10.1.0,M4.1.0/3"),
        Timezone::new("Antarctica/Mawson", "<+05>-5"),
        Timezone::new("Antarctica/McMurdo", "NZST-12NZDT,M9.5.0,M4.1.0/3"),
        Timezone::new("Antarctica/Palmer", "<-03>3"),
        Timezone::new("Antarctica/Rothera", "<-03>3"),
        Timezone::new("Antarctica/Syowa", "<+03>-3"),
        Timezone::new("Antarctica/Troll", "<+00>0<+02>-2,M3.5.0/1,M10.5.0/3"),
        Timezone::new("Antarctica/Vostok", "<+05>-5"),
        Timezone::new("Arctic/Longyearbyen", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Asia/Aden", "<+03>-3"),
        Timezone::new("Asia/Almaty", "<+05>-5"),
        Timezone::new("Asia/Amman", "<+03>-3"),
        Timezone::new("Asia/Anadyr", "<+12>-12"),
        Timezone::new("Asia/Aqtau", "<+05>-5"),
        Timezone::new("Asia/Aqtobe", "<+05>-5"),
        Timezone::new("Asia/Ashgabat", "<+05>-5"),
        Timezone::new("Asia/Atyrau", "<+05>-5"),
        Timezone::new("Asia/Baghdad", "<+03>-3"),
        Timezone::new("Asia/Bahrain", "<+03>-3"),
        Timezone::new("Asia/Baku", "<+04>-4"),
        Timezone::new("Asia/Bangkok", "<+07>-7"),
        Timezone::new("Asia/Barnaul", "<+07>-7"),
        Timezone::new("Asia/Beirut", "EET-2EEST,M3.5.0/0,M10.5.0/0"),
        Timezone::new("Asia/Bishkek", "<+06>-6"),
        Timezone::new("Asia/Brunei", "<+08>-8"),
        Timezone::new("Asia/Chita", "<+09>-9"),
        Timezone::new("Asia/Colombo", "<+0530>-5:30"),
        Timezone::new("Asia/Damascus", "<+03>-3"),
        Timezone::new("Asia/Dhaka", "<+06>-6"),
        Timezone::new("Asia/Dili", "<+09>-9"),
        Timezone::new("Asia/Dubai", "<+04>-4"),
        Timezone::new("Asia/Dushanbe", "<+05>-5"),
        Timezone::new("Asia/Famagusta", "EET-2EEST,M3.5.0/3,M10.5.0/4"),
        Timezone::new("Asia/Gaza", "EET-2EEST,M3.4.4/50,M10.4.4/50"),
        Timezone::new("Asia/Hebron", "EET-2EEST,M3.4.4/50,M10.4.4/50"),
        Timezone::new("Asia/Ho Chi Minh", "<+07>-7"),
        Timezone::new("Asia/Hong Kong", "HKT-8"),
        Timezone::new("Asia/Hovd", "<+07>-7"),
        Timezone::new("Asia/Irkutsk", "<+08>-8"),
        Timezone::new("Asia/Jakarta", "WIB-7"),
        Timezone::new("Asia/Jayapura", "WIT-9"),
        Timezone::new("Asia/Jerusalem", "IST-2IDT,M3.4.4/26,M10.5.0"),
        Timezone::new("Asia/Kabul", "<+0430>-4:30"),
        Timezone::new("Asia/Kamchatka", "<+12>-12"),
        Timezone::new("Asia/Karachi", "PKT-5"),
        Timezone::new("Asia/Kathmandu", "<+0545>-5:45"),
        Timezone::new("Asia/Khandyga", "<+09>-9"),
        Timezone::new("Asia/Kolkata", "IST-5:30"),
        Timezone::new("Asia/Krasnoyarsk", "<+07>-7"),
        Timezone::new("Asia/Kuala Lumpur", "<+08>-8"),
        Timezone::new("Asia/Kuching", "<+08>-8"),
        Timezone::new("Asia/Kuwait", "<+03>-3"),
        Timezone::new("Asia/Macau", "CST-8"),
        Timezone::new("Asia/Magadan", "<+11>-11"),
        Timezone::new("Asia/Makassar", "WITA-8"),
        Timezone::new("Asia/Manila", "PST-8"),
        Timezone::new("Asia/Muscat", "<+04>-4"),
        Timezone::new("Asia/Nicosia", "EET-2EEST,M3.5.0/3,M10.5.0/4"),
        Timezone::new("Asia/Novokuznetsk", "<+07>-7"),
        Timezone::new("Asia/Novosibirsk", "<+07>-7"),
        Timezone::new("Asia/Omsk", "<+06>-6"),
        Timezone::new("Asia/Oral", "<+05>-5"),
        Timezone::new("Asia/Phnom Penh", "<+07>-7"),
        Timezone::new("Asia/Pontianak", "WIB-7"),
        Timezone::new("Asia/Pyongyang", "KST-9"),
        Timezone::new("Asia/Qatar", "<+03>-3"),
        Timezone::new("Asia/Qostanay", "<+05>-5"),
        Timezone::new("Asia/Qyzylorda", "<+05>-5"),
        Timezone::new("Asia/Riyadh", "<+03>-3"),
        Timezone::new("Asia/Sakhalin", "<+11>-11"),
        Timezone::new("Asia/Samarkand", "<+05>-5"),
        Timezone::new("Asia/Seoul", "KST-9"),
        Timezone::new("Asia/Shanghai", "CST-8"),
        Timezone::new("Asia/Singapore", "<+08>-8"),
        Timezone::new("Asia/Srednekolymsk", "<+11>-11"),
        Timezone::new("Asia/Taipei", "CST-8"),
        Timezone::new("Asia/Tashkent", "<+05>-5"),
        Timezone::new("Asia/Tbilisi", "<+04>-4"),
        Timezone::new("Asia/Tehran", "<+0330>-3:30"),
        Timezone::new("Asia/Thimphu", "<+06>-6"),
        Timezone::new("Asia/Tokyo", "JST-9"),
        Timezone::new("Asia/Tomsk", "<+07>-7"),
        Timezone::new("Asia/Ulaanbaatar", "<+08>-8"),
        Timezone::new("Asia/Urumqi", "<+06>-6"),
        Timezone::new("Asia/Ust-Nera", "<+10>-10"),
        Timezone::new("Asia/Vientiane", "<+07>-7"),
        Timezone::new("Asia/Vladivostok", "<+10>-10"),
        Timezone::new("Asia/Yakutsk", "<+09>-9"),
        Timezone::new("Asia/Yangon", "<+0630>-6:30"),
        Timezone::new("Asia/Yekaterinburg", "<+05>-5"),
        Timezone::new("Asia/Yerevan", "<+04>-4"),
        Timezone::new("Atlantic/Azores", "<-01>1<+00>,M3.5.0/0,M10.5.0/1"),
        Timezone::new("Atlantic/Bermuda", "AST4ADT,M3.2.0,M11.1.0"),
        Timezone::new("Atlantic/Canary", "WET0WEST,M3.5.0/1,M10.5.0"),
        Timezone::new("Atlantic/Cape Verde", "<-01>1"),
        Timezone::new("Atlantic/Faroe", "WET0WEST,M3.5.0/1,M10.5.0"),
        Timezone::new("Atlantic/Madeira", "WET0WEST,M3.5.0/1,M10.5.0"),
        Timezone::new("Atlantic/Reykjavik", "GMT0"),
        Timezone::new("Atlantic/South Georgia", "<-02>2"),
        Timezone::new("Atlantic/St Helena", "GMT0"),
        Timezone::new("Atlantic/Stanley", "<-03>3"),
        Timezone::new("Australia/Adelaide", "ACST-9:30ACDT,M10.1.0,M4.1.0/3"),
        Timezone::new("Australia/Brisbane", "AEST-10"),
        Timezone::new("Australia/Broken Hill", "ACST-9:30ACDT,M10.1.0,M4.1.0/3"),
        Timezone::new("Australia/Darwin", "ACST-9:30"),
        Timezone::new("Australia/Eucla", "<+0845>-8:45"),
        Timezone::new("Australia/Hobart", "AEST-10AEDT,M10.1.0,M4.1.0/3"),
        Timezone::new("Australia/Lindeman", "AEST-10"),
        Timezone::new(
            "Australia/Lord Howe",
            "<+1030>-10:30<+11>-11,M10.1.0,M4.1.0",
        ),
        Timezone::new("Australia/Melbourne", "AEST-10AEDT,M10.1.0,M4.1.0/3"),
        Timezone::new("Australia/Perth", "AWST-8"),
        Timezone::new("Australia/Sydney", "AEST-10AEDT,M10.1.0,M4.1.0/3"),
        Timezone::new("Etc/GMT", "GMT0"),
        Timezone::new("Etc/GMT+1", "<-01>1"),
        Timezone::new("Etc/GMT+10", "<-10>10"),
        Timezone::new("Etc/GMT+11", "<-11>11"),
        Timezone::new("Etc/GMT+12", "<-12>12"),
        Timezone::new("Etc/GMT+2", "<-02>2"),
        Timezone::new("Etc/GMT+3", "<-03>3"),
        Timezone::new("Etc/GMT+4", "<-04>4"),
        Timezone::new("Etc/GMT+5", "<-05>5"),
        Timezone::new("Etc/GMT+6", "<-06>6"),
        Timezone::new("Etc/GMT+7", "<-07>7"),
        Timezone::new("Etc/GMT+8", "<-08>8"),
        Timezone::new("Etc/GMT+9", "<-09>9"),
        Timezone::new("Etc/GMT-1", "<+01>-1"),
        Timezone::new("Etc/GMT-10", "<+10>-10"),
        Timezone::new("Etc/GMT-11", "<+11>-11"),
        Timezone::new("Etc/GMT-12", "<+12>-12"),
        Timezone::new("Etc/GMT-13", "<+13>-13"),
        Timezone::new("Etc/GMT-14", "<+14>-14"),
        Timezone::new("Etc/GMT-2", "<+02>-2"),
        Timezone::new("Etc/GMT-3", "<+03>-3"),
        Timezone::new("Etc/GMT-4", "<+04>-4"),
        Timezone::new("Etc/GMT-5", "<+05>-5"),
        Timezone::new("Etc/GMT-6", "<+06>-6"),
        Timezone::new("Etc/GMT-7", "<+07>-7"),
        Timezone::new("Etc/GMT-8", "<+08>-8"),
        Timezone::new("Etc/GMT-9", "<+09>-9"),
        Timezone::new("Europe/Amsterdam", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Andorra", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Astrakhan", "<+04>-4"),
        Timezone::new("Europe/Athens", "EET-2EEST,M3.5.0/3,M10.5.0/4"),
        Timezone::new("Europe/Belgrade", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Berlin", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Bratislava", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Brussels", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Bucharest", "EET-2EEST,M3.5.0/3,M10.5.0/4"),
        Timezone::new("Europe/Budapest", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Busingen", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Chisinau", "EET-2EEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Copenhagen", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Dublin", "GMT0IST,M3.5.0/1,M10.5.0"),
        Timezone::new("Europe/Gibraltar", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Guernsey", "GMT0BST,M3.5.0/1,M10.5.0"),
        Timezone::new("Europe/Helsinki", "EET-2EEST,M3.5.0/3,M10.5.0/4"),
        Timezone::new("Europe/Isle of Man", "GMT0BST,M3.5.0/1,M10.5.0"),
        Timezone::new("Europe/Istanbul", "<+03>-3"),
        Timezone::new("Europe/Jersey", "GMT0BST,M3.5.0/1,M10.5.0"),
        Timezone::new("Europe/Kaliningrad", "EET-2"),
        Timezone::new("Europe/Kirov", "MSK-3"),
        Timezone::new("Europe/Kyiv", "EET-2EEST,M3.5.0/3,M10.5.0/4"),
        Timezone::new("Europe/Lisbon", "WET0WEST,M3.5.0/1,M10.5.0"),
        Timezone::new("Europe/Ljubljana", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/London", "GMT0BST,M3.5.0/1,M10.5.0"),
        Timezone::new("Europe/Luxembourg", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Madrid", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Malta", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Mariehamn", "EET-2EEST,M3.5.0/3,M10.5.0/4"),
        Timezone::new("Europe/Minsk", "<+03>-3"),
        Timezone::new("Europe/Monaco", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Moscow", "MSK-3"),
        Timezone::new("Europe/Oslo", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Paris", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Podgorica", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Prague", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Riga", "EET-2EEST,M3.5.0/3,M10.5.0/4"),
        Timezone::new("Europe/Rome", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Samara", "<+04>-4"),
        Timezone::new("Europe/San Marino", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Sarajevo", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Saratov", "<+04>-4"),
        Timezone::new("Europe/Simferopol", "MSK-3"),
        Timezone::new("Europe/Skopje", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Sofia", "EET-2EEST,M3.5.0/3,M10.5.0/4"),
        Timezone::new("Europe/Stockholm", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Tallinn", "EET-2EEST,M3.5.0/3,M10.5.0/4"),
        Timezone::new("Europe/Tirane", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Ulyanovsk", "<+04>-4"),
        Timezone::new("Europe/Vaduz", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Vatican", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Vienna", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Vilnius", "EET-2EEST,M3.5.0/3,M10.5.0/4"),
        Timezone::new("Europe/Volgograd", "MSK-3"),
        Timezone::new("Europe/Warsaw", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Zagreb", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Europe/Zurich", "CET-1CEST,M3.5.0,M10.5.0/3"),
        Timezone::new("Indian/Antananarivo", "EAT-3"),
        Timezone::new("Indian/Chagos", "<+06>-6"),
        Timezone::new("Indian/Christmas", "<+07>-7"),
        Timezone::new("Indian/Cocos", "<+0630>-6:30"),
        Timezone::new("Indian/Comoro", "EAT-3"),
        Timezone::new("Indian/Kerguelen", "<+05>-5"),
        Timezone::new("Indian/Mahe", "<+04>-4"),
        Timezone::new("Indian/Maldives", "<+05>-5"),
        Timezone::new("Indian/Mauritius", "<+04>-4"),
        Timezone::new("Indian/Mayotte", "EAT-3"),
        Timezone::new("Indian/Reunion", "<+04>-4"),
        Timezone::new("Pacific/Apia", "<+13>-13"),
        Timezone::new("Pacific/Auckland", "NZST-12NZDT,M9.5.0,M4.1.0/3"),
        Timezone::new("Pacific/Bougainville", "<+11>-11"),
        Timezone::new(
            "Pacific/Chatham",
            "<+1245>-12:45<+1345>,M9.5.0/2:45,M4.1.0/3:45",
        ),
        Timezone::new("Pacific/Chuuk", "<+10>-10"),
        Timezone::new("Pacific/Easter", "<-06>6<-05>,M9.1.6/22,M4.1.6/22"),
        Timezone::new("Pacific/Efate", "<+11>-11"),
        Timezone::new("Pacific/Fakaofo", "<+13>-13"),
        Timezone::new("Pacific/Fiji", "<+12>-12"),
        Timezone::new("Pacific/Funafuti", "<+12>-12"),
        Timezone::new("Pacific/Galapagos", "<-06>6"),
        Timezone::new("Pacific/Gambier", "<-09>9"),
        Timezone::new("Pacific/Guadalcanal", "<+11>-11"),
        Timezone::new("Pacific/Guam", "ChST-10"),
        Timezone::new("Pacific/Honolulu", "HST10"),
        Timezone::new("Pacific/Kanton", "<+13>-13"),
        Timezone::new("Pacific/Kiritimati", "<+14>-14"),
        Timezone::new("Pacific/Kosrae", "<+11>-11"),
        Timezone::new("Pacific/Kwajalein", "<+12>-12"),
        Timezone::new("Pacific/Majuro", "<+12>-12"),
        Timezone::new("Pacific/Marquesas", "<-0930>9:30"),
        Timezone::new("Pacific/Midway", "SST11"),
        Timezone::new("Pacific/Nauru", "<+12>-12"),
        Timezone::new("Pacific/Niue", "<-11>11"),
        Timezone::new("Pacific/Norfolk", "<+11>-11<+12>,M10.1.0,M4.1.0/3"),
        Timezone::new("Pacific/Noumea", "<+11>-11"),
        Timezone::new("Pacific/Pago Pago", "SST11"),
        Timezone::new("Pacific/Palau", "<+09>-9"),
        Timezone::new("Pacific/Pitcairn", "<-08>8"),
        Timezone::new("Pacific/Pohnpei", "<+11>-11"),
        Timezone::new("Pacific/Port Moresby", "<+10>-10"),
        Timezone::new("Pacific/Rarotonga", "<-10>10"),
        Timezone::new("Pacific/Saipan", "ChST-10"),
        Timezone::new("Pacific/Tahiti", "<-10>10"),
        Timezone::new("Pacific/Tarawa", "<+12>-12"),
        Timezone::new("Pacific/Tongatapu", "<+13>-13"),
        Timezone::new("Pacific/Wake", "<+12>-12"),
        Timezone::new("Pacific/Wallis", "<+12>-12"),
    ]
});

#[test]
fn all_timezone_variants_are_supported() {
    // Just to make sure Timezone::new() does not panic due to IANA normalization.
    // This is here just to invoke Deref on LazyLock.
    let _variants = LazyLock::force(&TIMEZONE_VARIANTS);
}
