[doc("Show available VM helper commands")]
help:
    @just --justfile /root/justfile --list --unsorted --color always

[doc("Follow bmc.log with ANSI intact")]
logs-bmc:
    . /etc/bmc-virt/paths.env && tail -n 200 -f "$BMC_LOG"

[doc("Follow syslog")]
logs-syslog:
    logread -f

[doc("Dump kernel messages")]
logs-dmesg:
    dmesg

[doc("Interactive process viewer")]
ps:
    htop
