import { Palette } from "../../style/palette.slint";
import { Theme } from "../../style/theme.slint";
import { Images } from "../../style/images.slint";
import { WidgetSize, BaseDimensions } from "../widget-shared.slint";

export enum BraiinsPoolStyle {
    Overview,
    BigChart,
}

export enum ChartFrame {
    Hours4,
    Hours12,
    Hours24,
    Days7,
}

export struct PoolWorkerStatus {
    total: string,
    active: string,
    low: string,
    offline: string,
}

export enum PoolPayoutType {
    Onchain,
    Lighting,
}

export struct BraiinsPoolPayouts {
    payout-time-fraction: percent,
    payout-type: PoolPayoutType,
}

export struct WidgetBraiinsPoolConfig {
    pool-style: BraiinsPoolStyle,
    chart-frame: ChartFrame,
    worker-states: bool,
}

export struct WidgetBraiinsPoolData {
    config: WidgetBraiinsPoolConfig,
    current-hashrate: string,
    current-hashrate-unit: string,
    reward-btc: string,
    reward-usd: string,
    hashrate-graph: image,
    workers-graph: image,
    worker-status: PoolWorkerStatus,
    pool-payouts: [BraiinsPoolPayouts],
    next-payout-estimate: string,
    last-payout: string,
    progress: percent,
    chart-overview-full: image,
    chart-overview-large: image,
    chart-bigchart-full: image,
    chart-bigchart-large: image,
    chart-bigchart-medium: image,
    chart-bigchart-small: image,
    hashrate-units: [string],
    hashrate-unit-label: string,
    workers-units: [string],
    timestamps: [string],
}

struct ImageDimensions {
  width: int,
  height: int,
}

export global PoolChartDimensions {
  public pure function get-dimensions(size: WidgetSize, pool-style: BraiinsPoolStyle) -> ImageDimensions {
    if pool-style == BraiinsPoolStyle.Overview {
        if size == WidgetSize.Large {
            return {
                width: 608,
                height: 121,
            };
        } else if size == WidgetSize.Full {
            return {
                width: 927,
                height: 214,
            };
        }
    } else if pool-style == BraiinsPoolStyle.BigChart {
        if size == WidgetSize.Small {
            return {
                width: 306,
                height: 132,
            };
        } else if size == WidgetSize.Medium {
            return {
                width: 488,
                height: 160,
            };
        } else if size == WidgetSize.Large {
            return {
                width: 488,
                height: 345,
            };
        } else if size == WidgetSize.Full {
            return {
                width: 1054,
                height: 370,
            };
        }
    }
    return {
        width: 0,
        height: 0,
    };
  }
}

component braiins-pool-icon-box inherits HorizontalLayout {
    in property <bool> show-account;
    in property <length> font-size: 24px;
    in property <length> top-padding: 16px;

    alignment: start;
    padding-left: 0px;
    padding-top: top-padding;
    padding-bottom: 16px;
    spacing: 8px;

    Image {
        width: 24px;
        height: 24px;
        source: Images.braiins-pool-favicon;
    }
    Text {
        text: "Braiins Pool";
        font-size: font-size;
        font-weight: Theme.font.weight.semi-bold;
        color: Palette.white;
    }
    if show-account: Text {
        text: "(user.braiins)";
        font-size: font-size;
        font-weight: Theme.font.weight.regular;
        color: Palette.gray-40;
    }
}

component progress-bar inherits Rectangle {
    in property <percent> progress;

    progress-bar-background := Rectangle {
        height: 8px;
        border-radius: 4px;
        background: Palette.gray-90;
    }
    Rectangle {
        x: progress-bar-background.x;
        width: progress;
        height: 8px;
        border-radius: 4px;
        background: Palette.green-50;
    }
}

component hashrate-box inherits VerticalLayout {
    in property <WidgetSize> size;
    in property <string> hashrate;
    in property <string> hashrate-unit;
    in property <length> hashrate-font-size;
    in property <bool> show-dot;

    padding-left: 0px;
    padding-right: 0px;
    padding-top: 0px;
    padding-bottom: 0px;
    alignment: space-between;
    HorizontalLayout {
        spacing: 8px;
        if show-dot: Rectangle {
            y: 12px;
            width: 8px;
            height: 8px;
            border-radius: 4px;
            border-width: 4px;
            border-color: Palette.violet-60;
        }
        Text {
            text: "Hashrate " + "(" + hashrate-unit + ")";
            font-size: 24px;
            font-weight: Theme.font.weight.regular;
            color: Palette.gray-40;
            horizontal-alignment: size == WidgetSize.Small ? center : left;
        }
    }
    Text {
        text: hashrate;
        font-size: hashrate-font-size;
        font-weight: Theme.font.weight.semi-bold;
        color: Palette.white;
        horizontal-alignment: size == WidgetSize.Small ? center : left;
    }
    Text {
        text: "5m Average";
        font-size: 24px;
        font-weight: Theme.font.weight.regular;
        color: Palette.gray-40;
        horizontal-alignment: size == WidgetSize.Small ? center : left;
    }
}

component reward-box inherits VerticalLayout {
    in property <WidgetSize> size;
    in property <string> reward-btc;
    in property <string> reward-usd;

    padding-left: 0px;
    padding-right: 0px;
    padding-top: 0px;
    padding-bottom: 0px;
    alignment: space-between;
    Text {
        text: "Today's Reward";
        font-size: 24px;
        font-weight: Theme.font.weight.regular;
        color: Palette.gray-40;
        horizontal-alignment: left;
    }
    Text {
        text: reward-btc;
        font-size: 32px;
        font-weight: Theme.font.weight.semi-bold;
        color: Palette.white;
        horizontal-alignment: left;
    }
    Text {
        text: reward-usd;
        font-size: 24px;
        font-weight: Theme.font.weight.regular;
        color: Palette.gray-40;
        horizontal-alignment: left;
    }
}

component payout-box inherits VerticalLayout {
    in property <percent> progress;
    in property <string> next-payout;
    in property <string> last-payout;

    padding-left: 0px;
    padding-right: 0px;
    padding-top: 0px;
    padding-bottom: 0px;
    HorizontalLayout {
        alignment: start;
        Text {
            text: "Next Payout In ~";
            font-size: 24px;
            font-weight: Theme.font.weight.regular;
            color: Palette.gray-40;
            horizontal-alignment: left;
        }
        Text {
            text: next-payout;
            font-size: 24px;
            font-weight: Theme.font.weight.semi-bold;
            color: Palette.white;
            horizontal-alignment: left;
        }
    }
    progress-bar {
        progress: progress;
    }
    HorizontalLayout {
        alignment: start;
        Text {
            text: "Last Payout: ";
            font-size: 24px;
            font-weight: Theme.font.weight.regular;
            color: Palette.gray-40;
            horizontal-alignment: left;
        }
        Text {
            text: last-payout;
            font-size: 24px;
            font-weight: Theme.font.weight.regular;
            color: Palette.white;
            horizontal-alignment: left;
        }
    }
}

component bordered-box inherits Rectangle {
    border-width: 1px;
    border-radius: 8px;
    border-color: Palette.gray-90;
    background: Palette.bordered-box-bg;
}

component workers-box inherits VerticalLayout {
    in property <bool> show-total;
    in property <length> rect-width;
    in property <length> rect-height;
    in property <length> padding-outer;
    in property <length> padding-inner;
    property <length> spacing-workers: 8px;

    in property <PoolWorkerStatus> worker-status;

    padding: padding-outer;
    Rectangle {
        width: rect-width;
        height: rect-height;
        border-width: 1px;
        border-radius: 8px;
        border-color: Palette.gray-90;
        background: Palette.bordered-box-bg;

        VerticalLayout {
            padding: padding-inner;
            alignment: space-between;
            Text {
                text: "Workers";
                font-size: 24px;
                font-weight: Theme.font.weight.regular;
                color: Palette.gray-40;
                vertical-alignment: center;
            }
            if show-total: HorizontalLayout {
                spacing: spacing-workers;
                    Image {
                        width: 32px;
                        source: Images.worker-total;
                    }
                Text {
                    text: worker-status.total;
                    font-size: 32px;
                    font-weight: Theme.font.weight.semi-bold;
                    color: Palette.white;
                    vertical-alignment: center;
                }
            }
            HorizontalLayout {
                spacing: spacing-workers;
                    Image {
                        width: 32px;
                        source: Images.worker-active;
                    }
                Text {
                    text: worker-status.active;
                    font-size: 32px;
                    font-weight: Theme.font.weight.semi-bold;
                    color: Palette.white;
                    vertical-alignment: center;
                }
            }
            HorizontalLayout {
                spacing: spacing-workers;
                    Image {
                        width: 32px;
                        source: Images.worker-low;
                    }
                Text {
                    text: worker-status.low;
                    font-size: 32px;
                    font-weight: Theme.font.weight.semi-bold;
                    color: Palette.white;
                    vertical-alignment: center;
                }
            }
            HorizontalLayout {
                spacing: spacing-workers;
                    Image {
                        width: 32px;
                        source: Images.worker-offline;
                    }
                Text {
                    text: worker-status.offline;
                    font-size: 32px;
                    font-weight: Theme.font.weight.semi-bold;
                    color: Palette.white;
                    vertical-alignment: center;
                }
            }
        }
    }
}

export component WidgetBraiinsPoolOverview inherits Rectangle {
    in property <WidgetSize> size;
    in property <WidgetBraiinsPoolData> data;

    background: Palette.black;
    width: BaseDimensions.widget-width(size);
    height: BaseDimensions.widget-height(size);

    if size == WidgetSize.Full: GridLayout {
        padding-left: 16px;
        padding-right: 16px;
        padding-bottom: 16px;
        spacing: 8px;
        Row {
            braiins-pool-icon-box {
                show-account: true;
            }
        }
        Row {
            bordered-box {
                height: 163px;
                hashrate-box {
                    padding-left: 32px;
                    padding-right: 32px;
                    padding-top: 24px;
                    padding-bottom: 24px;
                    size: size;
                    hashrate: data.current-hashrate;
                    hashrate-unit: data.current-hashrate-unit;
                    hashrate-font-size: 32px;
                    show-dot: true;
                }
            }
            bordered-box {
                height: 163px;
                payout-box {
                    padding-left: 24px;
                    padding-right: 24px;
                    padding-top: 16px;
                    padding-bottom: 16px;
                    next-payout: data.next-payout-estimate;
                    last-payout: data.last-payout;
                    progress: data.progress;
                }
            }
            bordered-box {
                height: 163px;
                reward-box {
                    padding-left: 24px;
                    padding-right: 24px;
                    padding-top: 16px;
                    padding-bottom: 16px;
                    size: size;
                    reward-btc: data.reward-btc;
                    reward-usd: data.reward-usd;
                }
            }
            workers-box {
                show-total: true;
                rowspan: 2;
                rect-width: 193px;
                rect-height: 397px;
                padding-inner: 24px;
                worker-status: data.worker-status;
            }
        }
        Row {
            HorizontalLayout {
                colspan: 3;
                VerticalLayout {
                    width: 60px;
                    alignment: space-between;
                    padding-right: 16px;
                    for hashrate-unit in data.hashrate-units:
                    Text {
                        text: hashrate-unit;
                        font-size: 24px;
                        font-weight: Theme.font.weight.regular;
                        color: Palette.gray-40;
                        horizontal-alignment: right;
                    }
                }
                Image {
                    height: PoolChartDimensions.get-dimensions(WidgetSize.Full, BraiinsPoolStyle.Overview).height * 1px;
                    source: data.chart-overview-full;
                }
                VerticalLayout {
                    width: 60px;
                    alignment: space-between;
                    for workers-unit in data.workers-units:
                    Text {
                        text: workers-unit;
                        font-size: 24px;
                        font-weight: Theme.font.weight.regular;
                        color: Palette.gray-40;
                        horizontal-alignment: right;
                    }
                }
            }
        }
    }
    if size == WidgetSize.Large: VerticalLayout {
        padding-left: 16px;
        padding-right: 16px;
        padding-bottom: 16px;
        spacing: 8px;
        braiins-pool-icon-box {
            padding-left: 0px;
            show-account: true;
        }
        bordered-box {
            height: 120px;
            payout-box {
                padding-left: 24px;
                padding-right: 24px;
                padding-top: 16px;
                padding-bottom: 16px;
                next-payout: data.next-payout-estimate;
                last-payout: data.last-payout;
                progress: data.progress;
            }
        }
        HorizontalLayout {
            spacing: 8px;
            bordered-box {
                height: 143px;
                hashrate-box {
                    padding-left: 24px;
                    padding-right: 24px;
                    padding-top: 16px;
                    padding-bottom: 16px;
                    size: size;
                    hashrate: data.current-hashrate;
                    hashrate-unit: data.current-hashrate-unit;
                    hashrate-font-size: 32px;
                    show-dot: true;
                }
            }
            bordered-box {
                height: 143px;
                reward-box {
                    padding-left: 24px;
                    padding-right: 24px;
                    padding-top: 16px;
                    padding-bottom: 16px;
                    size: size;
                    reward-btc: data.reward-btc;
                    reward-usd: data.reward-usd;
                }
            }
        }
        Rectangle {
            Image {
                source: data.chart-overview-large;
            }
        }
    }
    if size == WidgetSize.Medium: HorizontalLayout {
        VerticalLayout {
            braiins-pool-icon-box {
                padding-left: 16px;
                show-account: true;
            }

            HorizontalLayout {
                padding-top: 16px;
                padding-left: 16px;
                hashrate-box {
                    padding-bottom: 31px;
                    size: size;
                    hashrate: data.current-hashrate;
                    hashrate-unit: data.current-hashrate-unit;
                    hashrate-font-size: 32px;
                    show-dot: false;
                }
                reward-box {
                    padding-bottom: 31px;
                    size: size;
                    reward-btc: data.reward-btc;
                    reward-usd: data.reward-usd;
                }
            }
        }
        workers-box {
            show-total: false;
            padding-outer: 16px;
            padding-inner: 16px;
            rect-width: 149px;
            rect-height: 206px;
            worker-status: data.worker-status;
        }
    }
    if size == WidgetSize.Small: VerticalLayout {
        braiins-pool-icon-box {
            padding-left: 16px;
            show-account: false;
        }

        hashrate-box {
            padding-bottom: 31px;
            size: size;
            hashrate: data.current-hashrate;
            hashrate-unit: data.current-hashrate-unit;
            hashrate-font-size: 64px;
            show-dot: false;
        }
    }
}

export component WidgetBraiinsPoolBigChart inherits Rectangle {
    in property <WidgetSize> size;
    in property <WidgetBraiinsPoolData> data;

    background: Palette.black;
    width: BaseDimensions.widget-width(size);
    height: BaseDimensions.widget-height(size);

    if size == WidgetSize.Full: VerticalLayout {
        padding-left: 16px;
        padding-right: 16px;
        HorizontalLayout {
            alignment: start;
            spacing: 24px;
            braiins-pool-icon-box {
                show-account: true;
            }
            HorizontalLayout {
                spacing: 8px;
                padding-top: 16px;
                Text {
                    text: "5m HR " + "(" + data.current-hashrate-unit + "):";
                    font-size: 24px;
                    font-weight: Theme.font.weight.regular;
                    color: Palette.gray-40;
                }
                Text {
                    text: data.current-hashrate;
                    font-size: 24px;
                    font-weight: Theme.font.weight.bold;
                    color: Palette.violet-60;
                }
            }
            HorizontalLayout {
                spacing: 8px;
                padding-top: 16px;
                Text {
                    text: "Active Workers:";
                    font-size: 24px;
                    font-weight: Theme.font.weight.regular;
                    color: Palette.gray-40;
                }
                Text {
                    text: data.worker-status.active;
                    font-size: 24px;
                    font-weight: Theme.font.weight.bold;
                    color: Palette.teal-30;
                }
            }
        }
        HorizontalLayout {
            VerticalLayout {
                width: 120px;
                alignment: space-between;
                padding-right: 22px;
                for hashrate-unit in data.hashrate-units:
                Text {
                    text: hashrate-unit + " " + data.hashrate-unit-label;
                    font-size: 24px;
                    font-weight: Theme.font.weight.regular;
                    color: Palette.gray-40;
                    horizontal-alignment: right;
                }
            }
            Image {
                height: PoolChartDimensions.get-dimensions(WidgetSize.Full, BraiinsPoolStyle.BigChart).height * 1px;
                source: data.chart-bigchart-full;
            }
            VerticalLayout {
                width: 74px;
                alignment: space-between;
                for workers-unit in data.workers-units:
                Text {
                    text: workers-unit;
                    font-size: 24px;
                    font-weight: Theme.font.weight.regular;
                    color: Palette.gray-40;
                    horizontal-alignment: right;
                }
            }
        }
        HorizontalLayout {
            padding-left: 120px;
            padding-right: 74px;
            alignment: space-between;
            for timestamp in data.timestamps:
            Text {
                text: timestamp;
                font-size: 24px;
                font-weight: Theme.font.weight.regular;
                color: Palette.gray-40;
            }
        }
    }
    if size == WidgetSize.Large: VerticalLayout {
        padding-top: 8px;
        padding-left: 16px;
        padding-right: 16px;

        braiins-pool-icon-box {
            show-account: true;
            font-size: 20px;
        }
        HorizontalLayout {
            // Without max-height: 0px Slint sets the height of the HorizontalLayout way too big.
            max-height: 0px;
            spacing: 16px;
            alignment: start;
            HorizontalLayout {
                spacing: 8px;
                Text {
                    text: "5m HR " + "(" + data.current-hashrate-unit + "):";
                    font-size: 24px;
                    font-weight: Theme.font.weight.regular;
                    color: Palette.gray-40;
                }
                Text {
                    text: data.current-hashrate;
                    font-size: 24px;
                    font-weight: Theme.font.weight.bold;
                    color: Palette.violet-60;
                }
            }
            HorizontalLayout {
                spacing: 8px;
                Text {
                    text: "Active Workers:";
                    font-size: 24px;
                    font-weight: Theme.font.weight.regular;
                    color: Palette.gray-40;
                }
                Text {
                    text: data.worker-status.active;
                    font-size: 24px;
                    font-weight: Theme.font.weight.bold;
                    color: Palette.teal-30;
                }
            }
        }
        HorizontalLayout {
            padding-top: 21px;
            VerticalLayout {
                alignment: space-between;
                padding-right: 4px;
                for hashrate-unit in data.hashrate-units:
                Text {
                    text: hashrate-unit;
                    font-size: 24px;
                    font-weight: Theme.font.weight.regular;
                    color: Palette.gray-40;
                    horizontal-alignment: right;
                }
            }
            Rectangle {
                height: PoolChartDimensions.get-dimensions(WidgetSize.Large, BraiinsPoolStyle.BigChart).height * 1px;
                Image {
                    source: data.chart-bigchart-large;
                }
            }
            VerticalLayout {
                alignment: space-between;
                for workers-unit in data.workers-units:
                Text {
                    text: workers-unit;
                    font-size: 24px;
                    font-weight: Theme.font.weight.regular;
                    color: Palette.gray-40;
                    horizontal-alignment: right;
                }
            }
        }
    }
    if size == WidgetSize.Medium: VerticalLayout {
        padding-top: 8px;
        padding-left: 16px;
        padding-right: 16px;

        HorizontalLayout {
            alignment: space-between;
            braiins-pool-icon-box {
                show-account: false;
                top-padding: 0px;
                font-size: 20px;
            }
            HorizontalLayout {
                spacing: 20px;
                HorizontalLayout {
                    spacing: 5px;
                    Text {
                        text: data.current-hashrate;
                        font-size: 24px;
                        font-weight: Theme.font.weight.bold;
                        color: Palette.violet-60;
                    }
                    Text {
                        text: data.current-hashrate-unit;
                        font-size: 24px;
                        font-weight: Theme.font.weight.regular;
                        color: Palette.gray-40;
                    }
                }
                HorizontalLayout {
                    spacing: 5px;
                    Text {
                        text: data.worker-status.active;
                        font-size: 24px;
                        font-weight: Theme.font.weight.bold;
                        color: Palette.teal-30;
                    }
                    Text {
                        text: "Workers";
                        font-size: 24px;
                        font-weight: Theme.font.weight.regular;
                        color: Palette.gray-40;
                    }
                }
            }
        }
        HorizontalLayout {
            VerticalLayout {
                alignment: space-between;
                padding-right: 4px;
                for hashrate-unit in data.hashrate-units:
                Text {
                    text: hashrate-unit;
                    font-size: 24px;
                    font-weight: Theme.font.weight.regular;
                    color: Palette.gray-40;
                    horizontal-alignment: right;
                }
            }
            Image {
                height: PoolChartDimensions.get-dimensions(WidgetSize.Medium, BraiinsPoolStyle.BigChart).height * 1px;
                source: data.chart-bigchart-medium;
            }
            VerticalLayout {
                alignment: space-between;
                for workers-unit in data.workers-units:
                Text {
                    text: workers-unit;
                    font-size: 24px;
                    font-weight: Theme.font.weight.regular;
                    color: Palette.gray-40;
                    horizontal-alignment: right;
                }
            }
        }
    }
    if size == WidgetSize.Small: VerticalLayout {
        braiins-pool-icon-box {
            show-account: false;
            padding-left: 16px;
            top-padding: 8px;
            font-size: 20px;
        }
        HorizontalLayout {
            spacing: 8px;
            padding-left: 16px;
            alignment: start;
            Text {
                text: "5m HR " + "(" + data.current-hashrate-unit + "):";
                font-size: 24px;
                font-weight: Theme.font.weight.regular;
                color: Palette.gray-40;
            }
            Text {
                text: data.current-hashrate;
                font-size: 24px;
                font-weight: Theme.font.weight.bold;
                color: Palette.violet-60;
            }
        }
        Rectangle {
            Image {
                source: data.chart-bigchart-small;
            }
        }
    }
}

export component WidgetBraiinsPool {
    in property <WidgetSize> size;
    in property <WidgetBraiinsPoolData> data;

    if data.config.pool-style == BraiinsPoolStyle.Overview: WidgetBraiinsPoolOverview {
        size: root.size;
        data: root.data;
    }
    if data.config.pool-style == BraiinsPoolStyle.BigChart: WidgetBraiinsPoolBigChart {
        size: root.size;
        data: root.data;
    }
}
