import { Palette } from "../../style/palette.slint";
import { Theme } from "../../style/theme.slint";
import { Images } from "../../style/images.slint";
import { Backend } from "../../backend.slint";
import { WidgetSize, FontStyle, WidgetUtilsAdapter } from "../widget-shared.slint";
import { DateTime } from "../../controls/common.slint";
import { AlarmAdapter } from "../../controls/adapters.slint";

export enum ClockStyle {
  AnalogRound,
  AnalogRect,
  Digital,
}

export struct WidgetClockConfig {
    clock-style: ClockStyle,
    numbers-font-style: FontStyle,
    show-date: bool,
    show-seconds: bool,
    show-timezone: bool,
}

// Analog clock fix
export struct AnalogClockHands {
    second-hand-round: image,
    minute-hand-round: image,
    hour-hand-round: image,
    second-hand-rect: image,
    minute-hand-rect: image,
    hour-hand-rect: image,
}

export struct WidgetClockData {
    config: WidgetClockConfig,
    datetime: DateTime,
    analog-clock-hands: AnalogClockHands,
}

export component WidgetClockAnalogRound inherits Rectangle {
    property <length> base-width: 320px;
    property <length> base-height: 220px;
    in property <WidgetSize> size;
    in property <WidgetClockConfig> config;
    in property <DateTime> datetime;
    in property <WidgetClockData> data;

    property <percent> relative-size: (size == WidgetSize.Small || size == WidgetSize.Medium) ? 50% : 100%;

    property <image> clock-dial: (size == WidgetSize.Full || size == WidgetSize.Large) ? Images.clock-dial-round : Images.clock-dial-round-small;
    property <length> clock-dial-width: clock-dial.width * 1px;
    property <length> clock-dial-height: clock-dial.height * 1px;

    width: base-width * (size == WidgetSize.Small ? 1 : (size == WidgetSize.Medium || size == WidgetSize.Large) ? 2 : 4);
    height: base-height * ((size == WidgetSize.Small || size == WidgetSize.Medium) ? 1 : 2);

    Rectangle {
        width: 390px * relative-size;
        height: 390px * relative-size;

        dial := Image {
            // width: parent.width;
            // height: parent.height;
            width: clock-dial-width;
            height: clock-dial-height;
            source: clock-dial;
        }

        timezone := Text {
            visible: config.show-timezone;
            text: root.datetime.timezone;
            y: (size == WidgetSize.Full) ? 104px : (size == WidgetSize.Large) ? 112px : 53px;
            font-weight: Theme.font.weight.regular;
            font-size: (size == WidgetSize.Full || size == WidgetSize.Large) ? 24px : 16px;
            color: Palette.gray-40;
        }

        date-window := Rectangle {
            visible: (size == WidgetSize.Large || size == WidgetSize.Full) && config.show-date;
            width: 60px;
            height: 60px;
            x: parent.width / 2 - self.width / 2;
            y: 250px;
            border-radius: self.width / 2;
            border-width: 1px;
            border-color: Palette.gray-90;
            date := Text {
                text: root.datetime.day;
                font-size: 24px;
                font-weight: Theme.font.weight.regular;
                color: Palette.gray-40;
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }

        next_alarm := HorizontalLayout {
            visible: size == WidgetSize.Full && AlarmAdapter.next-alarm-is-defined;
            x: datetime.is-24-format ? -130px : -145px;
            y: 178px;
            spacing: 8px;

            Image {
                source: Images.alarm-bell;
                width: 24px;
                height: 24px;
                y: 5px;
                colorize: Palette.gray-40;
            }

            Text {
                text: AlarmAdapter.next-alarm-is-defined ? datetime.is-24-format ? AlarmAdapter.next-alarm-time.time-24 : (AlarmAdapter.next-alarm-time.time-12 + " " + (AlarmAdapter.next-alarm-time.is_pm ? "PM" : "AM")) : "";
                font-size: 24px;
                font-weight: Theme.font.weight.regular;
                color: Palette.gray-40;
            }
        }

        hour := Image {
            width: Images.hour-hand-width * relative-size;
            height: Images.hour-hand-height * relative-size;
            y: 74px * relative-size;
            // rotation-angle: hour-angle();
            // rotation-origin-y: 121px * relative-size;
            // source: Images.hand-hour;
            source: data.analog-clock-hands.hour-hand-round;
        }

        minute := Image {
            width: Images.minute-hand-width * relative-size;
            height: Images.minute-hand-height * relative-size;
            // y: 0px;
            // rotation-angle: minute-angle();
            // rotation-origin-y: 195px * relative-size;
            // source: Images.hand-minute;
            source: data.analog-clock-hands.minute-hand-round;
        }

        Image {
            width: Images.circle-white-width * relative-size;
            height: Images.circle-white-height * relative-size;
            x: 168px * relative-size;
            y: 168px * relative-size;
            source: Images.center-circle-white;
        }

        if config.show-seconds: second := Image {
            width: Images.second-hand-width * relative-size;
            height: Images.second-hand-height * relative-size;
            // y: 5px * relative-size;
            // rotation-angle: second-angle();
            // rotation-origin-y: 190px * relative-size;
            // source: Images.hand-second;
            source: data.analog-clock-hands.second-hand-round;
        }
        if config.show-seconds: Image {
            width: Images.circle-orange-width * relative-size;
            height: Images.circle-orange-height * relative-size;
            x: 187px * relative-size;
            y: 187px * relative-size;
            source: Images.center-circle-orange;
        }

        Image {
            width: Images.circle-black-width * relative-size;
            height: Images.circle-black-height * relative-size;
            x: 191px * relative-size;
            y: 191px * relative-size;
            source: Images.center-circle-black;
        }

        Image {
            width: Images.circle-stroke-width * relative-size;
            height: Images.circle-stroke-height * relative-size;
            x: 190px * relative-size;
            y: 190px * relative-size;
            source: Images.center-circle-stroke;
        }

        function second-angle() -> angle {
            return root.datetime.second * 6deg;
        }
        function minute-angle() -> angle {
            return root.datetime.minute * 6deg;
        }

        function hour-angle() -> angle {
            return (root.datetime.hour12 * 30deg) + (root.datetime.minute * 30deg / 60);
        }
    }
}

export component WidgetClockAnalogRect inherits Rectangle {
    property <length> base-width: 320px;
    property <length> base-height: 220px;
    in property <WidgetSize> size;
    in property <WidgetClockConfig> config;
    in property <DateTime> datetime;
    in property <WidgetClockData> data;

    property <percent> relative-size: (size == WidgetSize.Small || size == WidgetSize.Medium) ? 50% : 100%;
    property <percent> relative-width: (size == WidgetSize.Full) ? 100% : (size == WidgetSize.Small) ? 25% : 50%;
    property <percent> relative-height: (size == WidgetSize.Small || size == WidgetSize.Medium) ? 50% : 100%;

    property <image> clock-dial: (size == WidgetSize.Full) ? Images.clock-dial-rect-full : (size == WidgetSize.Large) ? Images.clock-dial-rect-large : (size == WidgetSize.Medium) ? Images.clock-dial-rect-medium : Images.clock-dial-rect-small;
    property <length> clock-dial-width: clock-dial.width * 1px;
    property <length> clock-dial-height: clock-dial.height * 1px;

    property <length> hour-font-size: (size == WidgetSize.Full) ? 64px : (size == WidgetSize.Large) ? 40px : (size == WidgetSize.Medium) ? 24px : 24px;
    property <int> hour-font-weight: (size == WidgetSize.Full) ? Theme.font.weight.bold : Theme.font.weight.semi-bold;

    width: base-width * (size == WidgetSize.Small ? 1 : (size == WidgetSize.Medium || size == WidgetSize.Large) ? 2 : 4);
    height: base-height * ((size == WidgetSize.Small || size == WidgetSize.Medium) ? 1 : 2);

    Rectangle {
        dial := Image {
            // width: parent.width;
            // height: parent.height;
            width: clock-dial-width;
            height: clock-dial-height;
            source: clock-dial;
        }

        twelve := Text {
            text: "12";
            font-size: hour-font-size;
            font-weight: hour-font-weight;
            color: Palette.white;
            y: twelve-vertical-offset(size);
        }

        three := Text {
            text: "3";
            font-size: hour-font-size;
            font-weight: hour-font-weight;
            color: Palette.white;
            x: three-horizontal-offset(size, root.width, self.width);
        }

        six := Text {
            text: "6";
            font-size: hour-font-size;
            font-weight: hour-font-weight;
            color: Palette.white;
            y: six-vertical-offset(size, root.height, self.height);
        }

        nine := Text {
            text: "9";
            font-size: hour-font-size;
            font-weight: hour-font-weight;
            color: Palette.white;
            x: nine-horizontal-offset(size);
        }

        date := Text {
            visible: size == WidgetSize.Full && config.show-date;
            text: root.datetime.weekday + " " + root.datetime.day;
            font-size: 40px;
            font-weight: Theme.font.weight.regular;
            color: Palette.gray-40;
            vertical-alignment: center;
            x: 870px;
        }

        timezone_element := Text {
            visible: config.show-timezone;
            text: root.datetime.timezone;
            y: (size == WidgetSize.Full) ? 265px : (size == WidgetSize.Large) ? 270px : (size == WidgetSize.Medium) ? 130px : 130px;
            font-weight: Theme.font.weight.regular;
            font-size: (size == WidgetSize.Small || size == WidgetSize.Medium) ? 16px : 24px;
            color: Palette.gray-40;
        }

        next_alarm := HorizontalLayout {
            visible: size == WidgetSize.Full && AlarmAdapter.next-alarm-is-defined;
            x: 250px;
            y: 195px;
            spacing: 6px;

            Image {
                source: Images.alarm-bell;
                width: 36px;
                height: 36px;
                y: 9px;
            }

            Text {
                text: AlarmAdapter.next-alarm-is-defined ? datetime.is-24-format ? AlarmAdapter.next-alarm-time.time-24 : (AlarmAdapter.next-alarm-time.time-12 + " " + (AlarmAdapter.next-alarm-time.is_pm ? "PM" : "AM")) : "";
                font-size: 40px;
                font-weight: Theme.font.weight.regular;
                color: Palette.gray-60;
            }
        }

        hour := Image {
            // width: 0.9 * Images.hour-hand-rect-width * relative-size;
            // height: 0.9 * Images.hour-hand-rect-height * relative-size;
            width: Images.hour-hand-rect-width * relative-size;
            height: Images.hour-hand-rect-height * relative-size;
            y: 95px * relative-size;
            // rotation-angle: hour-angle();
            // rotation-origin-y: 123px * relative-size;
            // source: Images.hand-hour-rect;
            source: data.analog-clock-hands.hour-hand-rect;
        }

        minute := Image {
            // width: 0.9 * Images.minute-hand-rect-width * relative-size;
            // height: 0.9 * Images.minute-hand-rect-height * relative-size;
            width: Images.minute-hand-rect-width * relative-size;
            height: Images.minute-hand-rect-height * relative-size;
            y: 2px;
            // rotation-angle: minute-angle();
            // rotation-origin-y: 217px * relative-size;
            // source: Images.hand-minute-rect;
            source: data.analog-clock-hands.minute-hand-rect;
        }

        Image {
            width: Images.circle-white-width * relative-size;
            height: Images.circle-white-height * relative-size;
            x: parent.width / 2 - (relative-size) * Images.circle-white-width / 2;
            y: parent.height / 2 - (relative-size) * Images.circle-white-height / 2;
            source: Images.center-circle-white;
        }

        if config.show-seconds: second := Image {
            // width: 0.9 * Images.second-hand-rect-width * relative-size;
            // height: 0.9 * Images.second-hand-rect-height * relative-size;
            width: Images.second-hand-rect-width * relative-size;
            height: Images.second-hand-rect-height * relative-size;
            y: 4px * relative-size;
            // rotation-angle: second-angle();
            // rotation-origin-y: 215px * relative-size;
            // source: Images.hand-second-rect;
            source: data.analog-clock-hands.second-hand-rect;
        }
        if config.show-seconds: Image {
            width: Images.circle-orange-width * relative-size;
            height: Images.circle-orange-height * relative-size;
            x: parent.width / 2 - (relative-size) * Images.circle-orange-width / 2;
            y: parent.height / 2 - (relative-size) * Images.circle-orange-height / 2;
            source: Images.center-circle-orange;
        }

        Image {
            width: Images.circle-black-width * relative-size;
            height: Images.circle-black-height * relative-size;
            x: parent.width / 2 - (relative-size) * Images.circle-black-width / 2;
            y: parent.height / 2 - (relative-size) * Images.circle-black-height / 2;
            source: Images.center-circle-black;
        }

        Image {
            width: Images.circle-stroke-width * relative-size;
            height: Images.circle-stroke-height * relative-size;
            x: parent.width / 2 - (relative-size) * Images.circle-stroke-width / 2;
            y: parent.height / 2 - (relative-size) * Images.circle-stroke-height / 2;
            source: Images.center-circle-stroke;
        }

        function second-angle() -> angle {
            return root.datetime.second * 6deg;
        }
        function minute-angle() -> angle {
            return root.datetime.minute * 6deg;
        }

        function hour-angle() -> angle {
            return (root.datetime.hour12 * 30deg) + (root.datetime.minute * 30deg / 60);
        }

        function twelve-vertical-offset(w-size: WidgetSize) -> length {
            return (w-size == WidgetSize.Full) ? 59px : (w-size == WidgetSize.Large) ? 80px : (w-size == WidgetSize.Medium) ? 35px
                // Small
                : 40px;
        }

        function three-horizontal-offset(w-size: WidgetSize, r-w: length, s-w: length) -> length {
            return (w-size == WidgetSize.Full) ? r-w - s-w - 105px : (w-size == WidgetSize.Large) ? r-w - s-w - 90px : (w-size == WidgetSize.Medium) ? r-w - s-w - 50px
                // Small
                : r-w - s-w - 50px;
        }

        function six-vertical-offset(w-size: WidgetSize, r-h: length, s-h: length) -> length {
            return (w-size == WidgetSize.Full) ? r-h - s-h - 59px : (w-size == WidgetSize.Large) ? r-h - s-h - 80px : (w-size == WidgetSize.Medium) ? r-h - s-h - 35px
                // Small
                : r-h - s-h - 40px;
        }

        function nine-horizontal-offset(w-size: WidgetSize) -> length {
            return (w-size == WidgetSize.Full) ? 105px : (w-size == WidgetSize.Large) ? 90px : (w-size == WidgetSize.Medium) ? 50px
                // Small
                : 50px;
        }
    }
}

export component WidgetClockDigital inherits Rectangle {
    property <length> base-width: 320px;
    property <length> base-height: 220px;
    in property <WidgetSize> size;
    in property <WidgetClockConfig> config;
    in property <DateTime> datetime;

    property <string> time: datetime.is-24-format ? (config.show-seconds ? datetime.time-sec-24 : datetime.time-24) : (config.show-seconds ? datetime.time-sec-12 : datetime.time-12);
    property <percent> relative-size: (size == WidgetSize.Small || size == WidgetSize.Medium) ? 50% : 100%;

    width: base-width * (size == WidgetSize.Small ? 1 : (size == WidgetSize.Medium || size == WidgetSize.Large) ? 2 : 4);
    height: base-height * ((size == WidgetSize.Small || size == WidgetSize.Medium) ? 1 : 2);

    pure function time-fontsize(size: WidgetSize) -> length {
        if (WidgetSize.Small == size) {
            return 64px;
        } else if (WidgetSize.Medium == size) {
            return 96px;
        } else if (WidgetSize.Large == size) {
            return 120px;
        } else {
            // WidgetSize.Full
            return 200px;
        }
    }

    if size == WidgetSize.Full: VerticalLayout {
        /// Date + TZ bar
        HorizontalLayout {
            alignment: start;
            padding-left: 32px;
            padding-right: 32px;
            padding-top: 48px;
            Text {
                visible: config.show-date;
                text: root.datetime.weekday + " " + root.datetime.day + ", " + root.datetime.year;
                font-size: 32px;
                font-weight: Theme.font.weight.regular;
                color: Palette.gray-60;
                horizontal-alignment: left;
                width: parent.width / 3 - 32px;
            }

            Text {
                visible: config.show-timezone;
                text: root.datetime.timezone;
                font-size: (size == WidgetSize.Full || size == WidgetSize.Large) ? 32px : 24px;
                font-weight: Theme.font.weight.regular;
                color: Palette.gray-60;
                horizontal-alignment: center;
                width: parent.width / 3;
            }

            Text {
                // Weather is not yet implemented
                visible: false;
                // visible: size == WidgetSize.Full;
                text: "29°C";
                font-size: 32px;
                font-weight: Theme.font.weight.regular;
                color: Palette.gray-60;
                horizontal-alignment: right;
                width: parent.width / 3 - 32px;
            }
        }

        /// Time
        HorizontalLayout {
            alignment: center;
            HorizontalLayout {
                width: 228px;
            }

            HorizontalLayout {
                Text {
                    text: root.time;
                    font-size: time-fontsize(size);
                    font-weight: WidgetUtilsAdapter.font-style-to-font-weight(config.numbers-font-style);
                    color: Palette.white;
                }
            }

            HorizontalLayout {
                width: 228px;
                padding-left: 25px;
                if !root.datetime.is-24-format: Text {
                    text: root.datetime.is_pm ? "PM" : "AM";
                    font-size: 32px;
                    font-weight: Theme.font.weight.regular;
                    color: Palette.gray-60;
                    vertical-alignment: center;
                }
            }
        }

        /// Alarm
        HorizontalLayout {
            alignment: center;
            padding-bottom: 32px;
            spacing: 6px;

            if AlarmAdapter.next-alarm-is-defined:Image {
                source: Images.alarm-bell;
            }

            Text {
                text: AlarmAdapter.next-alarm-is-defined ? datetime.is-24-format ? AlarmAdapter.next-alarm-time.time-24 : (AlarmAdapter.next-alarm-time.time-12 + " " + (AlarmAdapter.next-alarm-time.is_pm ? "PM" : "AM")) : "";
                font-size: 40px;
                font-weight: Theme.font.weight.regular;
                color: Palette.gray-60;
            }
        }
    }

    if size != WidgetSize.Full: GridLayout {
        padding-top: size == WidgetSize.Large ? 90px : size == WidgetSize.Medium ? 20px : 31px;
        padding-bottom: size == WidgetSize.Large ? 90px : size == WidgetSize.Medium ? 20px : 31px;
        Row {
            Text {
                visible: config.show-timezone;
                text: root.datetime.timezone;
                font-size: size == WidgetSize.Large ? 32px : 24px;
                font-weight: Theme.font.weight.regular;
                color: Palette.gray-60;
                horizontal-alignment: center;
            }
        }

        Row {
            Text {
                text: root.time;
                font-size: time-fontsize(size);
                font-weight: WidgetUtilsAdapter.font-style-to-font-weight(config.numbers-font-style);
                color: Palette.white;
                horizontal-alignment: center;
            }
        }

        Row {
            Text {
                visible: !root.datetime.is_24_format;
                text: root.datetime.is_pm ? "PM" : "AM";
                font-size: size == WidgetSize.Large ? 32px : 24px;
                font-weight: Theme.font.weight.regular;
                color: Palette.gray-60;
                horizontal-alignment: center;
            }
        }
    }
}

export component WidgetClock {
    in property <WidgetSize> size;
    in property <WidgetClockConfig> config;
    in property <DateTime> datetime;
    in property <WidgetClockData> data;

    if config.clock-style == ClockStyle.AnalogRound: WidgetClockAnalogRound {
        size: root.size;
        config: root.config;
        datetime: root.datetime;
        data: root.data;
    }
    if config.clock-style == ClockStyle.AnalogRect: WidgetClockAnalogRect {
        size: root.size;
        config: root.config;
        datetime: root.datetime;
        data: root.data;
    }
    if config.clock-style == ClockStyle.Digital: WidgetClockDigital {
        size: root.size;
        config: root.config;
        datetime: root.datetime;
    }
}
