import { Palette } from "../../style/palette.slint";
import { Theme } from "../../style/theme.slint";
import { WidgetSize } from "../widget-shared.slint";

export enum WidgetRemoteImageState {
    Initial,
    ConfigurationError,
    Loading,
    LoadingSuccess,
    LoadingError,
    UnexpectedError,
}

export struct WidgetRemoteImageData {
    image: image,
    state: WidgetRemoteImageState,
}

export component WidgetRemoteImage inherits Rectangle {
    in property <WidgetSize> size;
    in property <WidgetRemoteImageData> data;

    background: Palette.black;

    if root.data.image.width > 0 && root.data.image.height > 0: Image {
        width: root.width;
        height: root.height;
        source: root.data.image;
    }

    if root.data.state != WidgetRemoteImageState.Initial && root.data.state != WidgetRemoteImageState.LoadingSuccess: Rectangle {

        Rectangle {
            background: Palette.black;
            opacity: 80%;
        }

        if root.data.state == WidgetRemoteImageState.ConfigurationError: VerticalLayout {
            alignment: center;
            spacing: 8px;

            Text {
                color: Palette.white;
                font-size: 20px;
                font-weight: Theme.font.weight.bold;
                horizontal-alignment: center;
                text: "Invalid configuration";
            }

            Text {
                color: Palette.white;
                font-size: 16px;
                font-weight: Theme.font.weight.regular;
                horizontal-alignment: center;
                wrap: word-wrap;
                text: "Please check widget configuration";
            }
        }

        if root.data.state == WidgetRemoteImageState.Loading: Text {
            color: Palette.white;
            font-size: 20px;
            font-weight: Theme.font.weight.bold;
            horizontal-alignment: center;
            text: "Loading image";
        }

        if root.data.state == WidgetRemoteImageState.LoadingError: VerticalLayout {
            alignment: center;
            spacing: 8px;

            Text {
                color: Palette.white;
                font-size: 20px;
                font-weight: Theme.font.weight.bold;
                horizontal-alignment: center;
                text: "Failed to load image";
            }

            Text {
                color: Palette.white;
                font-size: 16px;
                font-weight: Theme.font.weight.regular;
                horizontal-alignment: center;
                wrap: word-wrap;
                text: "Please check widget configuration";
            }
        }

        if root.data.state == WidgetRemoteImageState.UnexpectedError: Text {
            color: Palette.white;
            font-size: 20px;
            font-weight: Theme.font.weight.bold;
            horizontal-alignment: center;
            text: "Unexpected error";
        }
    }
}
