import { Palette } from "../../style/palette.slint";
import { Theme } from "../../style/theme.slint";
import { WidgetSize } from "../widget-shared.slint";

export enum WidgetRemoteImageState {
    Initial,
    ConfigurationError,
    Loading,
    LoadingSuccess,
    LoadingError,
    UnexpectedError,
}

export struct WidgetRemoteImageData {
    image: image,
    state: WidgetRemoteImageState,
}

export component WidgetRemoteImage inherits Rectangle {
    in property <WidgetSize> size;
    in property <WidgetRemoteImageData> data;

    background: Palette.black;

    if root.data.image.width > 0 && root.data.image.height > 0: Image {
        width: root.width;
        height: root.height;
        source: root.data.image;
    }

    if root.data.state != WidgetRemoteImageState.Initial && root.data.state != WidgetRemoteImageState.LoadingSuccess: Rectangle {
        width: parent.width - 32px;
        height: parent.height - 32px;

        Rectangle {
            background: Palette.gray-100;
            opacity: 70%;
            border-radius: 8px;
            border-width: 1px;
            border-color: Palette.gray-90;
        }

        if root.data.state == WidgetRemoteImageState.ConfigurationError: VerticalLayout {
            alignment: center;
            spacing: 8px;

            Text {
                color: Palette.white;
                font-size: root.size == WidgetSize.Small ? 24px : 40px;
                font-weight: Theme.font.weight.bold;
                horizontal-alignment: center;
                text: "Invalid configuration";
            }

            Text {
                color: Palette.white;
                font-size: root.size == WidgetSize.Small ? 18px : 24px;
                font-weight: Theme.font.weight.regular;
                horizontal-alignment: center;
                wrap: word-wrap;
                text: "Please check widget configuration";
            }
        }

        if root.data.state == WidgetRemoteImageState.Loading: Text {
            color: Palette.white;
            font-size: root.size == WidgetSize.Small ? 24px : 40px;
            font-weight: Theme.font.weight.bold;
            horizontal-alignment: center;
            text: "Loading image";
        }

        if root.data.state == WidgetRemoteImageState.LoadingError: VerticalLayout {
            alignment: center;
            spacing: 8px;

            Text {
                color: Palette.white;
                font-size: root.size == WidgetSize.Small ? 24px : 40px;
                font-weight: Theme.font.weight.bold;
                horizontal-alignment: center;
                text: "Failed to load image";
            }

            Text {
                color: Palette.white;
                font-size: root.size == WidgetSize.Small ? 18px : 24px;
                font-weight: Theme.font.weight.regular;
                horizontal-alignment: center;
                wrap: word-wrap;
                text: "Please check widget configuration";
            }
        }

        if root.data.state == WidgetRemoteImageState.UnexpectedError: Text {
            color: Palette.white;
            font-size: root.size == WidgetSize.Small ? 24px : 40px;
            font-weight: Theme.font.weight.bold;
            horizontal-alignment: center;
            text: "Unexpected error";
        }
    }
}
