import { Palette } from "../../style/palette.slint";
import { Theme } from "../../style/theme.slint";
import { WidgetSize, RemoteWidgetState } from "../widget-shared.slint";

export struct RemoteWidgetData {
    image: image,
    state: RemoteWidgetState,
}

export component RemoteWidget inherits Rectangle {
    in property <WidgetSize> size;
    in property <RemoteWidgetData> data;

    background: Palette.black;

    if root.data.image.width > 0 && root.data.image.height > 0: Image {
        width: root.width;
        height: root.height;
        source: root.data.image;
    }

    if root.data.state != RemoteWidgetState.Initial && root.data.state != RemoteWidgetState.LoadingSuccess: Rectangle {

        Rectangle {
            background: Palette.black;
            opacity: 80%;
        }

        if root.data.state == RemoteWidgetState.ConfigurationError: VerticalLayout {
            alignment: center;
            spacing: 8px;

            Text {
                color: Palette.white;
                font-size: 20px;
                font-weight: Theme.font.weight.bold;
                horizontal-alignment: center;
                text: "Invalid configuration";
            }

            Text {
                color: Palette.white;
                font-size: 16px;
                font-weight: Theme.font.weight.regular;
                horizontal-alignment: center;
                wrap: word-wrap;
                text: "Please check widget configuration";
            }
        }

        if root.data.state == RemoteWidgetState.Loading: Text {
            color: Palette.white;
            font-size: 20px;
            font-weight: Theme.font.weight.bold;
            horizontal-alignment: center;
            text: "Loading widget";
        }

        if root.data.state == RemoteWidgetState.LoadingError: VerticalLayout {
            alignment: center;
            spacing: 8px;

            Text {
                color: Palette.white;
                font-size: 20px;
                font-weight: Theme.font.weight.bold;
                horizontal-alignment: center;
                text: "Failed to load widget";
            }

            Text {
                color: Palette.white;
                font-size: 16px;
                font-weight: Theme.font.weight.regular;
                horizontal-alignment: center;
                wrap: word-wrap;
                text: "Please check widget configuration";
            }
        }

        if root.data.state == RemoteWidgetState.UnexpectedError: Text {
            color: Palette.white;
            font-size: 20px;
            font-weight: Theme.font.weight.bold;
            horizontal-alignment: center;
            text: "Unexpected error";
        }
    }
}
