import { Palette } from "../../style/palette.slint";
import { Theme } from "../../style/theme.slint";
import { Images } from "../../style/images.slint";
import { WidgetSize, BaseDimensions, TickerTimeFrame } from "../widget-shared.slint";
import { BitcoinAdapter } from "../../controls/adapters.slint";

export struct WidgetBtcConfig {
    time-frame: TickerTimeFrame,
}

export struct WidgetBtcData {
    config: WidgetBtcConfig,
    btc-graph: image,
}

export component WidgetBtcGraph inherits Rectangle {
    background: Palette.black;

    in property <WidgetSize> size;
    in property <WidgetBtcData> data;

    width: BaseDimensions.widget-width(size);
    height: BaseDimensions.widget-height(size);

    in property <string> btc_price <=> BitcoinAdapter.price;
    in property <string> price-change <=> BitcoinAdapter.price_change;
    in property <bool> price-increase <=> BitcoinAdapter.price_increase;

    pure function btc-fontsize(size: WidgetSize) -> length {
        if (WidgetSize.Small == size) {
            return 64px;
        } else if (WidgetSize.Medium == size) {
            return 96px;
        } else if (WidgetSize.Large == size) {
            return 144px;
        } else {
            // WidgetSize.Full
            return 200px;
        }
    }
    in property <length> btc_font_size: btc-fontsize(size);

    property <length> bar-padding-left: 16px;
    property <length> bar-padding-right: (size == WidgetSize.Small) ? 9px : 16px;
    property <length> bar-padding-top: (size == WidgetSize.Full) ? 16px : 8px;

    property <length> trend-box-width: 91px;
    property <length> trend-box-height: 39px;
    property <length> trend-font-size: 24px;

    property <length> ticker_text_font_size: 24px;

    property <length> btc_icon_size: (size == WidgetSize.Full || size == WidgetSize.Large) ? 40px : 32px;

    VerticalLayout {
        HorizontalLayout {
            alignment: space-between;
            padding-left: bar-padding-left;
            padding-right: bar-padding-right;
            padding-top: bar-padding-top;
            HorizontalLayout {
                spacing: 12px;
                Rectangle {
                    Image {
                        source: Images.btc-icon;
                    }
                }
                Rectangle {
                    Text {
                        text: "BTC-USD";
                        color: Palette.white;
                        font-size: ticker_text_font_size;
                        font-weight: Theme.font.weight.semi-bold;
                    }
                }
            }
            HorizontalLayout {
                spacing: 8px;
                if (size != WidgetSize.Small): Rectangle {
                    Text {
                        text: "24h";
                        color: Palette.gray-40;
                        font-size: 24px;
                        font-weight: Theme.font.weight.regular;
                    }
                }
                Rectangle {
                    width: trend-box-width;
                    height: trend-box-height;
                    border-radius: 4px;
                    states [
                        positive when price-increase: {
                            background: Palette.green-90;
                        }
                        negative when !price-increase: {
                            background: Palette.red-100;
                        }
                    ]
                    Text {
                        text: price-change;
                        font-size: trend-font-size;
                        font-weight: Theme.font.weight.semi-bold;
                        states [
                            positive when price-increase: {
                                color: Palette.green-30;
                            }
                            negative when !price-increase: {
                                color: Palette.red-40;
                            }
                        ]
                    }
                }
            }
        }
    }
    Rectangle {
        Image {
            y: 0.4 * parent.height;
            width: parent.width + 1px;
            height: 0.6 * parent.height;
            source: data.btc-graph;
        }
        Text {
            text: btc_price;
            color: Palette.white;
            font-size: btc-fontsize(size);
            font-weight: Theme.font.weight.semi-bold;
            font-family: "Braiins Deck Sans";
        }
    }
}
