// bmc-video-play - Self-contained FFmpeg wrapper with embedded binary
// Copyright (C) 2026  Braiins Forge s.r.o.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Braiins Systems s.r.o. and Braiins Forge s.r.o. each reserve the right
// to grant any party a license to this program, or any part thereof,
// under any terms, and such a grant shall be considered distinct from
// the grant above.

//
// Usage: bmc-video-play <video.mp4> [alsa_device] [volume_0-100]
//
// Features:
// - Embedded ffmpeg (extracted to /tmp on first run)
// - Touch controls: tap = pause/resume, double-tap = skip
// - SK9822/APA102 LED effects over SPI
// - Cleans up on exit

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>
#include <signal.h>
#include <fcntl.h>
#include <errno.h>
#include <math.h>
#include <time.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include <linux/input.h>
#include <linux/spi/spidev.h>
#include <pthread.h>
#include <stdatomic.h>

// Embedded ffmpeg binary (generated by xxd -i)
#include "ffmpeg_embedded.h"

// Configuration
#define FFMPEG_TMP_PATH "/tmp/.bmc-ffmpeg"
#define FB_DEV "/dev/fb0"
#define TOUCH_DEV "/dev/input/event0"
#define LED_SPI_DEV "/dev/spidev0.0"
#define LED_COUNT 10
#define DOUBLE_TAP_MS 300
#define KNIGHT_RIDER_PERIOD 1.0f // seconds
#define PAUSE_PERIOD 2.0f // seconds

#define LED_BRIGHTNESS 200 // Static brightness, the LED changes color on brightness changes

// Global state
static pid_t g_ffmpeg_pid = -1;
static atomic_bool g_stop_requested = false;
static atomic_bool g_paused = false;
static atomic_bool g_led_stop = false;
static atomic_int g_brightness_factor_pct = 100;

// ============== LED Support ==============

typedef struct {
    uint8_t r, g, b;
} rgb_t;

static const rgb_t LED_COLOR = {107, 80, 255};  // Violet

typedef struct {
    int spi_fd;
    uint8_t *frame;
    size_t frame_len;
    int nled;
} led_ctx_t;

static int led_init(led_ctx_t *ctx)
{
    memset(ctx, 0, sizeof(*ctx));

    ctx->spi_fd = open(LED_SPI_DEV, O_WRONLY);
    if (ctx->spi_fd < 0) {
        fprintf(stderr, "LED: failed to open %s\n", LED_SPI_DEV);
        return -1;
    }

    uint8_t mode = SPI_MODE_0;
    uint8_t bits = 8;
    uint32_t speed = 4000000;
    ioctl(ctx->spi_fd, SPI_IOC_WR_MODE, &mode);
    ioctl(ctx->spi_fd, SPI_IOC_WR_BITS_PER_WORD, &bits);
    ioctl(ctx->spi_fd, SPI_IOC_WR_MAX_SPEED_HZ, &speed);

    ctx->nled = LED_COUNT;
    size_t start = 4, pixels = ctx->nled * 4, end = 4;
    ctx->frame_len = start + pixels + end;
    ctx->frame = calloc(1, ctx->frame_len);
    if (!ctx->frame) {
        close(ctx->spi_fd);
        return -1;
    }

    // End frame = 0xFF
    memset(ctx->frame + start + pixels, 0xFF, end);
    return 0;
}

static float get_brightness_factor()
{
    return ((float)atomic_load(&g_brightness_factor_pct)) / 100.0;
}

static void led_destroy(led_ctx_t *ctx)
{
    if (ctx->frame) free(ctx->frame);
    if (ctx->spi_fd >= 0) close(ctx->spi_fd);
}

static void led_flush(led_ctx_t *ctx)
{
    if (ctx->spi_fd >= 0 && ctx->frame)
        write(ctx->spi_fd, ctx->frame, ctx->frame_len);
}

static void led_set_all(led_ctx_t *ctx, float brightness_factor, rgb_t c)
{
    uint8_t *px = ctx->frame + 4;
    uint8_t b5 = LED_BRIGHTNESS >> 3;  // 0-255 -> 0-31

    if (b5 > 31) b5 = 31;
    for (int i = 0; i < ctx->nled; i++, px += 4) {
        px[0] = 0xE0 | b5;
        px[1] = c.b * brightness_factor;
        px[2] = c.g * brightness_factor;
        px[3] = c.r * brightness_factor;
    }
}

static void led_off(led_ctx_t *ctx)
{
    uint8_t *px = ctx->frame + 4;
    for (int i = 0; i < ctx->nled; i++, px += 4) {
        px[0] = 0xE0;
        px[1] = px[2] = px[3] = 0;
    }
    led_flush(ctx);
}

// Knight rider effect
static void led_knight_rider(led_ctx_t *ctx, float phase, float brightness_factor)
{
    uint8_t *px = ctx->frame + 4;
    uint8_t b5 = LED_BRIGHTNESS >> 3;
    if (b5 > 31) b5 = 31;

    float travel = (float)(ctx->nled - 1);
    float frac = fmodf(phase, 1.0f);
    float time = frac * 2.0f * travel;
    float head = (time <= travel) ? time : (2.0f * travel - time);

    for (int i = 0; i < ctx->nled; i++, px += 4) {
        int dist = abs(i - (int)head);
        float factor = ((dist <= 1) ? 1.0f : (dist <= 3) ? 0.3f : 0.05f) * brightness_factor;

        px[0] = 0xE0 | b5;
        px[1] = (uint8_t)(LED_COLOR.b * factor);
        px[2] = (uint8_t)(LED_COLOR.g * factor);
        px[3] = (uint8_t)(LED_COLOR.r * factor);
    }
}

static void *led_thread(void *arg)
{
    (void)arg;

    led_ctx_t ctx;
    if (led_init(&ctx) < 0) {
        fprintf(stderr, "LED: init failed, continuing without LEDs\n");
        return NULL;
    }

    fprintf(stderr, "LED: running on %s (%d LEDs)\n", LED_SPI_DEV, LED_COUNT);

    struct timespec start;
    clock_gettime(CLOCK_MONOTONIC, &start);

    float period = KNIGHT_RIDER_PERIOD;

    while (!atomic_load(&g_led_stop)) {
        struct timespec now;
        clock_gettime(CLOCK_MONOTONIC, &now);

        double elapsed = (now.tv_sec - start.tv_sec) +
                        (now.tv_nsec - start.tv_nsec) / 1e9;
        float phase = fmodf(elapsed / period, 1.0f);

        float brightness_factor = get_brightness_factor();

        if (atomic_load(&g_paused)) {
            period = PAUSE_PERIOD;
            // Breathing effect when paused
            float breath = 0.5f + 0.5f * sinf(phase * 2.0f * M_PI);
            led_set_all(&ctx, 0.5f * breath * brightness_factor, LED_COLOR);
        } else {
            period = KNIGHT_RIDER_PERIOD;
            // Knight rider when playing
            led_knight_rider(&ctx, phase, brightness_factor);
        }

        led_flush(&ctx);
        usleep(16000);  // ~60 FPS
    }

    led_off(&ctx);
    led_destroy(&ctx);
    return NULL;
}

// ============== FFmpeg Extraction ==============

static int extract_ffmpeg(void)
{
    struct stat st;
    if (stat(FFMPEG_TMP_PATH, &st) == 0 && st.st_size == (off_t)ffmpeg_bin_len) {
        return 0;  // Already extracted
    }

    fprintf(stderr, "Extracting ffmpeg (%zu bytes)...\n", ffmpeg_bin_len);

    int fd = open(FFMPEG_TMP_PATH, O_WRONLY | O_CREAT | O_TRUNC, 0755);
    if (fd < 0) {
        perror("Failed to create temp ffmpeg");
        return -1;
    }

    size_t written = 0;
    while (written < ffmpeg_bin_len) {
        ssize_t n = write(fd, ffmpeg_bin + written, ffmpeg_bin_len - written);
        if (n <= 0) {
            close(fd);
            unlink(FFMPEG_TMP_PATH);
            return -1;
        }
        written += n;
    }

    close(fd);
    fprintf(stderr, "Extracted to %s\n", FFMPEG_TMP_PATH);
    return 0;
}

// ============== Framebuffer ==============

static void clear_framebuffer(void)
{
    int fd = open(FB_DEV, O_WRONLY);
    if (fd < 0) return;

    char zeros[4096] = {0};
    for (int i = 0; i < 2500; i++) {
        if (write(fd, zeros, sizeof(zeros)) <= 0) break;
    }
    close(fd);
}

// ============== Touch Input ==============

static unsigned long now_ms(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec * 1000UL + ts.tv_nsec / 1000000UL;
}

static void *touch_thread(void *arg)
{
    (void)arg;
    pid_t pid = g_ffmpeg_pid;

    int fd = open(TOUCH_DEV, O_RDONLY | O_NONBLOCK);
    if (fd < 0) {
        fprintf(stderr, "Touch: failed to open %s\n", TOUCH_DEV);
        return NULL;
    }

    fprintf(stderr, "Touch: tap=pause/resume, double-tap=skip\n");

    // State machine
    bool finger_down = false;
    unsigned long tap_time = 0;      // Time of last completed tap (finger up)
    int tap_count = 0;               // Taps in current gesture
    unsigned long debounce_until = 0; // Ignore events until this time

    struct input_event ev;

    void double_tap() {
      bool was_paused = atomic_load(&g_paused);
      atomic_store(&g_paused, !was_paused);

      if (!was_paused) {
        fprintf(stderr, "Touch: PAUSE (double-tap)\n");
        kill(pid, SIGSTOP);
      } else {
        fprintf(stderr, "Touch: RESUME (double-tap)\n");
        kill(pid, SIGCONT);
      }
    }

    void single_tap() {
      bool was_paused = atomic_load(&g_paused);

      if (was_paused) {
          // Unpause if was paused
          fprintf(stderr, "Touch: RESUME (single-tap)\n");
          atomic_store(&g_paused, !was_paused);
          kill(pid, SIGCONT);
      } else {
        atomic_store(&g_stop_requested, true);
        fprintf(stderr, "Touch: SKIP (single-tap)\n");
        kill(pid, SIGCONT);  // Resume if paused
        kill(pid, SIGTERM);
      }
    }

    while (!atomic_load(&g_stop_requested)) {
        unsigned long now = now_ms();

        // Check for pending double-tap timeout
        if (tap_count == 1 && !finger_down && tap_time > 0) {
            if (now - tap_time >= DOUBLE_TAP_MS) {
                // Single tap confirmed - skip
                single_tap();

                tap_count = 0;
                tap_time = 0;
                debounce_until = now + 100;  // Short debounce after action
            }
        }

        // Non-blocking read
        ssize_t n = read(fd, &ev, sizeof(ev));
        if (n != sizeof(ev)) {
            if (errno == EAGAIN || errno == EWOULDBLOCK || errno == EINTR) {
                usleep(10000);  // 10ms poll interval
                continue;
            }
            break;
        }

        // Skip events during debounce period
        if (now < debounce_until)
            continue;

        // Detect touch down
        bool is_down = false;
        if (ev.type == EV_ABS && ev.code == ABS_MT_TRACKING_ID && ev.value >= 0)
            is_down = true;
        else if (ev.type == EV_KEY && ev.code == BTN_TOUCH && ev.value == 1)
            is_down = true;

        // Detect touch up
        bool is_up = false;
        if (ev.type == EV_ABS && ev.code == ABS_MT_TRACKING_ID && ev.value == -1)
            is_up = true;
        else if (ev.type == EV_KEY && ev.code == BTN_TOUCH && ev.value == 0)
            is_up = true;

        if (is_down && !finger_down) {
            finger_down = true;
        }
        else if (is_up && finger_down) {
            finger_down = false;
            now = now_ms();  // Refresh time

            // Check if this is second tap of a double-tap
            if (tap_count == 1 && tap_time > 0 && (now - tap_time) < DOUBLE_TAP_MS) {
                double_tap();
                tap_count = 0;
                tap_time = 0;
            } else {
                // First tap - wait to see if double-tap follows
                tap_count = 1;
                tap_time = now;
            }
        }
    }

    close(fd);
    return NULL;
}

// ============== Signal Handler ==============

static void sighandler(int sig)
{
    (void)sig;
    atomic_store(&g_stop_requested, true);
    atomic_store(&g_led_stop, true);
    pid_t pid = g_ffmpeg_pid;

    if (pid > 0) {
      kill(pid, SIGCONT);  // Resume if paused
      kill(pid, SIGTERM);
    }
}

// ============== Main ==============

int main(int argc, char *argv[])
{
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <video.mp4> [alsa_device] [volume] [brightness]\n", argv[0]);
        fprintf(stderr, "Embedded ffmpeg: %zu bytes\n", ffmpeg_bin_len);
        fprintf(stderr, "Controls: tap=pause, double-tap=skip\n");
        return 1;
    }

    const char *video = argv[1];
    const char *alsa = (argc > 2) ? argv[2] : "default";
    const char *alsa_out = (strcmp(alsa, "default") == 0) ? "plughw:0,0" : alsa;

    // Parse volume (0-100, default 30)
    int volume_pct = (argc > 3) ? atoi(argv[3]) : 30;
    if (volume_pct < 0) volume_pct = 0;
    if (volume_pct > 100) volume_pct = 100;
    char volume_filter[32];
    snprintf(volume_filter, sizeof(volume_filter), "volume=%.2f", volume_pct / 100.0);

    // Parse brightness factor
    int brightness_pct = (argc > 4) ? atoi(argv[4]) : 100;
    if (brightness_pct < 0) brightness_pct = 0;
    if (brightness_pct > 100) brightness_pct = 100;

    atomic_store(&g_brightness_factor_pct, brightness_pct);

    if (access(video, R_OK) != 0) {
        fprintf(stderr, "Error: cannot read %s\n", video);
        return 1;
    }

    if (extract_ffmpeg() != 0) return 1;

    // Fork ffmpeg
    pid_t pid = fork();

    if (pid < 0) {
      fprintf(stderr, "Could not start ffmpeg: %d\n", errno);
      return 1;
    }

    g_ffmpeg_pid = pid;

    signal(SIGINT, sighandler);
    signal(SIGTERM, sighandler);

    if (pid == 0) {
        // Child
        execl(FFMPEG_TMP_PATH, "ffmpeg",
              "-threads", "2",
              "-i", video,
              "-pix_fmt", "rgb565",
              "-f", "fbdev", FB_DEV,
              "-ac", "2",
              "-af", volume_filter,
              "-f", "alsa", alsa_out,
              NULL);
        _exit(127);
    }

    fprintf(stderr, "Playing: %s (pid %d)\n", video, pid);

    // Start LED thread
    pthread_t led_tid;
    pthread_create(&led_tid, NULL, led_thread, NULL);

    // Start touch thread
    pthread_t touch_tid;
    pthread_create(&touch_tid, NULL, touch_thread, NULL);

    // Wait for ffmpeg
    int status;
    while (waitpid(pid, &status, 0) < 0) {
        if (errno != EINTR) break;
    }
    fprintf(stderr, "FFmpeg exited with code %d.\n", status);

    // Cleanup
    atomic_store(&g_stop_requested, true);
    atomic_store(&g_led_stop, true);

    pthread_cancel(touch_tid);
    pthread_join(touch_tid, NULL);
    pthread_join(led_tid, NULL);

    // TODO: Fix this in the future. The last frame will be kept for now.
    // Since we use this only for splash animation with DECK logo at the end,
    // it's what we want for now. But if we play arbitrary videos, the
    // screen should be put to a deterministic state afterwards.
    /* clear_framebuffer(); */
    fprintf(stderr, "Done\n");
    return 0;
}
