[package]
name = "bmc-nix-init-openwrt"
version = "0.1.0"
edition = "2024"
authors = ["Braiins <braiins@braiins.com>"]

# Produce binary named "bmc-nix-init" to match the OpenWrt service
[[bin]]
name = "bmc-nix-init"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
bmc-led = { workspace = true, features = ["apa102_spi"] }
bmc-nix.workspace = true
bmc-nix-init.workspace = true
bmc-platform = { workspace = true, features = ["backlight"] }
bmc-shared-ii-net-drv = { workspace = true }
clap = { workspace = true, features = ["derive"] }
drm.workspace = true
evdev.workspace = true
flume = { workspace = true }
libc.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
slint = { workspace = true }
tokio = { workspace = true, features = ["macros", "process", "rt-multi-thread", "time"] }
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
