import { Palette } from "style/palette.slint";
import { Theme } from "style/theme.slint";
import { ScreenAdapter, UpgradeDownloadAdapter, NotificationAdapter, BitcoinAdapter, BlockHeightAdapter } from "controls/adapters.slint";
import { UIScreen, DateTime } from "controls/common.slint";
import { UpgradeDownload, UpgradeProgress, UpgradeSuccess, UpgradeFailed,
    InitStartConnect, InitWifiConnectProgress, InitWifiConnectSuccess, InitWifiConnectFailed, InitSetupSuccess, InitGeneralError, InitDeviceSetupQr, ConnectInfo
} from "screens/screens.slint";
import { WidgetSize, WidgetKind, Widget } from "widgets/widget.slint";
import { BaseDimensions } from "widgets/widget-shared.slint";
import { WidgetBuilder } from "controls/widget-builder.slint";
import { Scene } from "widgets/scene.slint";
import { SceneCycler, SceneCyclingAdapter } from "controls/scene-cycler.slint";
import { ScenePreview } from "controls/scene-preview.slint";
import { Backend } from "backend.slint";
import { Notification } from "components/notification.slint";
import { Images } from "style/images.slint";
import { InitSetupWifiAdapter, ConnectionAdapter } from "controls/adapters.slint";

export { ScreenAdapter, SceneCyclingAdapter, UpgradeDownloadAdapter, UIScreen, DateTime, NotificationAdapter, BitcoinAdapter, BlockHeightAdapter }
export { WidgetSize, WidgetKind, Widget }
export { Backend }
export { Palette, BaseDimensions }
export { InitSetupWifiAdapter, ConnectionAdapter }

export component MainWindow inherits Window {
    default-font-family: "Braiins Sans";
    background: Palette.black;
    width: 1280px;
    height: 480px;

    in property <UIScreen> screen-id <=> ScreenAdapter.screen-id;
    in property <bool> night-mode-enabled;

    // all (enabled & disabled) scenes
    in property <[Scene]> scenes;
    in property <int> preview-scene-index: -1;
    // only enabled scenes (derived from `scenes` using FilterModel)
    in property <[Scene]> cycler-scenes;
    in-out property <int> cycler-scene-index;

    if preview-scene-index < 0: Rectangle {
        z: 0.1;

        if root.cycler-scenes.length == 0: Text {
            text: "You don't have any scenes or all scenes are disabled";
            color: Palette.white;
            font-size: Theme.font.size.common.default;
            font-weight: Theme.font.weight.regular;
        }

        if root.cycler-scenes.length > 0: SceneCycler {
            scenes: root.cycler-scenes;
            scene-index <=> root.cycler-scene-index;
            enabled: root.screen_id == UIScreen.Void;
            automatic-enabled: !root.night-mode-enabled;
        }
    }

    if preview-scene-index >= 0: ScenePreview {
        z: 0.1;
        scene: root.scenes[root.preview-scene-index];
    }

    // Overlay screens
    UpgradeProgress {
        z: 0.3;
        visible: root.screen_id == UIScreen.UpgradeProgress;

        // stop touch propagation (https://github.com/slint-ui/slint/discussions/8044)
        TouchArea { }
    }

    UpgradeDownload {
        z: 0.3;
        visible: root.screen_id == UIScreen.UpgradeDownload;

        // stop touch propagation (https://github.com/slint-ui/slint/discussions/8044)
        TouchArea { }
    }

    UpgradeSuccess {
        z: 0.3;
        visible: root.screen_id == UIScreen.UpgradeSuccess;

        // stop touch propagation (https://github.com/slint-ui/slint/discussions/8044)
        TouchArea { }
    }

    UpgradeFailed {
        z: 0.3;
        visible: root.screen_id == UIScreen.UpgradeFailed;

        // stop touch propagation (https://github.com/slint-ui/slint/discussions/8044)
        TouchArea { }
    }

    InitStartConnect {
        z: 0.3;
        visible: root.screen_id == UIScreen.InitStartConnect;

        // stop touch propagation (https://github.com/slint-ui/slint/discussions/8044)
        TouchArea { }
    }

    InitWifiConnectProgress {
        z: 0.3;
        visible: root.screen_id == UIScreen.InitWifiConnectProgress;

        // stop touch propagation (https://github.com/slint-ui/slint/discussions/8044)
        TouchArea { }
    }

    InitWifiConnectSuccess {
        z: 0.3;
        visible: root.screen_id == UIScreen.InitWifiConnectSuccess;

        // stop touch propagation (https://github.com/slint-ui/slint/discussions/8044)
        TouchArea { }
    }

    InitWifiConnectFailed {
        z: 0.3;
        visible: root.screen_id == UIScreen.InitWifiConnectFailed;

        // stop touch propagation (https://github.com/slint-ui/slint/discussions/8044)
        TouchArea { }
    }

    InitSetupSuccess {
        z: 0.3;
        visible: root.screen_id == UIScreen.InitSetupSuccess;

        // stop touch propagation (https://github.com/slint-ui/slint/discussions/8044)
        TouchArea { }
    }

    InitGeneralError {
        z: 0.3;
        visible: root.screen_id == UIScreen.InitGeneralError;

        // stop touch propagation (https://github.com/slint-ui/slint/discussions/8044)
        TouchArea { }
    }

    InitDeviceSetupQr {
        z: 0.3;
        visible: root.screen_id == UIScreen.InitDeviceSetupQr;

        // stop touch propagation (https://github.com/slint-ui/slint/discussions/8044)
        TouchArea { }
    }

    ConnectInfo {
        z: 0.3;
        visible: root.screen_id == UIScreen.ConnectInfo;

        // stop touch propagation (https://github.com/slint-ui/slint/discussions/8044)
        TouchArea { }
    }
}
