import { Palette } from "style/palette.slint";
import { ScreenAdapter, UpgradeDownloadAdapter } from "controls/adapters.slint";
import { UIScreen } from "controls/common.slint";
import { UpgradeDownload, UpgradeProgress, UpgradeSuccess, UpgradeFailed } from "screens/screens.slint";
import { WidgetSize, WidgetType, WidgetSlint } from "widgets/widget.slint";
import { WidgetBuilder } from "controls/widget-builder.slint";
import { Backend } from "backend.slint";
import { DateTimeAdapter } from "controls/adapters.slint";

export { ScreenAdapter, UpgradeDownloadAdapter, UIScreen }
export { WidgetSize, WidgetType, WidgetSlint }
export { Backend }
export { DateTimeAdapter }

export component MainWindow inherits Window {
    default-font-family: "Braiins Sans";
    background: Palette.black;
    width: 1280px;
    height: 480px;

    in property <UIScreen> screen-id <=> ScreenAdapter.screen-id;

    in property <[WidgetSlint]> widgets;

    WidgetBuilder {
        width: parent.width;
        height: parent.height;
        widgets: widgets;
    }

    // Overlay screens
    UpgradeProgress {
        visible: root.screen_id == UIScreen.UpgradeProgress;
    }
    UpgradeDownload {
        visible: root.screen_id == UIScreen.UpgradeDownload;
    }
    UpgradeSuccess {
        visible: root.screen_id == UIScreen.UpgradeSuccess;
    }
    UpgradeFailed {
        visible: root.screen_id == UIScreen.UpgradeFailed;
    }
}
