import { Palette } from "style/palette.slint";
import { ScreenAdapter, UpgradeDownloadAdapter, NotificationAdapter } from "controls/adapters.slint";
import { UIScreen } from "controls/common.slint";
import { UpgradeDownload, UpgradeProgress, UpgradeSuccess, UpgradeFailed,
    InitStartConnect, InitWifiConnectProgress, InitWifiConnectSuccess, InitWifiConnectFailed, InitSetupSuccess, InitGeneralError, InitDeviceSetupQr, ConnectInfo
} from "screens/screens.slint";
import { WidgetSize, WidgetType, WidgetSlint } from "widgets/widget.slint";
import { WidgetBuilder } from "controls/widget-builder.slint";
import { Backend } from "backend.slint";
import { DateTimeAdapter } from "controls/adapters.slint";
import { Notification } from "components/notification.slint";
import { Images } from "style/images.slint";
import { DateTimeAdapter, InitSetupWifiAdapter, ConnectionAdapter } from "controls/adapters.slint";

export { ScreenAdapter, UpgradeDownloadAdapter, UIScreen, NotificationAdapter }
export { WidgetSize, WidgetType, WidgetSlint }
export { Backend }
export { DateTimeAdapter, InitSetupWifiAdapter, ConnectionAdapter }

export component MainWindow inherits Window {
    default-font-family: "Braiins Sans";
    background: Palette.black;
    width: 1280px;
    height: 480px;

    in property <UIScreen> screen-id <=> ScreenAdapter.screen-id;

    in property <[WidgetSlint]> widgets;

    // Status Bar
    Rectangle {
        width: parent.width;
        height: 40px;
        x: 0px;
        y: 0px;
        border-width: 2px;
        border-color: red;
        Text {
            text: "Wifi: Offline";
            font-size: 16px;
            color: Palette.red-50;
            vertical-alignment: center;
            x: parent.width - self.width - 10px;
        }
    }

    Notification {
        x: 0px;
        y: 40px;
        width: parent.width;
        icon: Images.notification_info;
        heigth_override: 100px;
        stripe_color: Palette.gray-80;
        padding_top_override: 12px;
    }

    WidgetBuilder {
        width: parent.width;
        height: parent.height;
        widgets: widgets;
    }

    // Overlay screens
    UpgradeProgress {
        visible: root.screen_id == UIScreen.UpgradeProgress;
    }

    UpgradeDownload {
        visible: root.screen_id == UIScreen.UpgradeDownload;
    }

    UpgradeSuccess {
        visible: root.screen_id == UIScreen.UpgradeSuccess;
    }

    UpgradeFailed {
        visible: root.screen_id == UIScreen.UpgradeFailed;
    }

    InitStartConnect {
        visible: root.screen_id == UIScreen.InitStartConnect;
    }

    InitWifiConnectProgress {
        visible: root.screen_id == UIScreen.InitWifiConnectProgress;
    }

    InitWifiConnectSuccess {
        visible: root.screen_id == UIScreen.InitWifiConnectSuccess;
    }

    InitWifiConnectFailed {
        visible: root.screen_id == UIScreen.InitWifiConnectFailed;
    }

    InitSetupSuccess {
        visible: root.screen_id == UIScreen.InitSetupSuccess;
    }

    InitGeneralError {
        visible: root.screen_id == UIScreen.InitGeneralError;
    }

    InitDeviceSetupQr {
        visible: root.screen_id == UIScreen.InitDeviceSetupQr;
    }

    ConnectInfo {
        visible: root.screen_id == UIScreen.ConnectInfo;
    }
}
