[package]
name = "bmc-system-overlay"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
authors = ["Braiins Systems s.r.o."]
description = "Framework for privileged wlr-layer-shell system overlays"

[dependencies]
anyhow.workspace = true
bmc-gpu-render-lock.workspace = true
bmc-net-observe.workspace = true
bmc-render.workspace = true
bmc-widget = { workspace = true, features = ["gpu"] }
deck-alarm-v1 = { workspace = true }
deck-device-info-v1 = { workspace = true }
deck-screen-edge-v1 = { workspace = true }
deck-settings-v1 = { workspace = true }
deck-upgrade-v1 = { workspace = true }
glow.workspace = true
libc.workspace = true
serde_json.workspace = true
taffy.workspace = true
tracing.workspace = true
wayland-backend.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
wayland-protocols-wlr = { workspace = true, features = ["client"] }

[dev-dependencies]
bmc-wasm-protocol.workspace = true

[lints]
workspace = true
