[package]
name = "bmc-system-overlay"
version = "0.1.0"
edition = "2024"
authors = ["Braiins Systems s.r.o."]
description = "Framework for privileged wlr-layer-shell system overlays"

[dependencies]
anyhow.workspace = true
bmc-gpu-render-lock.workspace = true
bmc-render.workspace = true
bmc-widget = { workspace = true, features = ["gpu"] }
deck-screen-edge-v1 = { workspace = true }
get_if_addrs.workspace = true
glow.workspace = true
libc.workspace = true
taffy.workspace = true
tracing.workspace = true
wayland-backend.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
wayland-protocols-wlr = { workspace = true, features = ["client"] }

[dev-dependencies]
bmc-wasm-protocol.workspace = true

[lints]
workspace = true
