[package]
name = "bmc-nix-init"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
axum.workspace = true
bmc-grpc.workspace = true
bmc-led.workspace = true
bmc-nix.workspace = true
bmc-platform.workspace = true
bmc-shared-ii-net = { workspace = true }
bmc-upgrade = { workspace = true, features = ["disk-check"] }
flume = { workspace = true }
http.workspace = true
mime_guess.workspace = true
qrcode-generator = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
slint = { workspace = true, features = ["renderer-software"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "macros", "net", "process", "rt", "time"] }
tokio-util.workspace = true
tonic.workspace = true
tonic-web.workspace = true
tower = { workspace = true, features = ["steer"] }
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
anyhow.workspace = true
slint-build.workspace = true

[features]
slint-embed-files = []

[lints]
workspace = true
