import { WidgetSize } from "widget-shared.slint";
import { WidgetClockData } from "./categories/clock.slint";
import { WidgetBtcData } from "./categories/ticker-btc.slint";
import { WidgetBlockHeightData } from "./categories/block-height.slint";
import { WidgetBraiinsPoolData } from "./categories/braiins-pool.slint";
export { WidgetSize }

export enum WidgetKind {
    Clock,
    TickerBtc,
    BlockHeight,
    BraiinsPool,
}

export struct Widget {
    id: string,
    row: int,
    col: int,
    size: WidgetSize,
    kind: WidgetKind,
    clock: WidgetClockData,
    ticker-btc: WidgetBtcData,
    blockheight: WidgetBlockHeightData,
    braiins-pool: WidgetBraiinsPoolData,
}
