import { WidgetSize } from "widget-shared.slint";
import { WidgetClockData } from "./categories/clock.slint";
import { WidgetBtcData } from "./categories/ticker-btc.slint";
import { WidgetBlockHeightData } from "./categories/block-height.slint";
import { WidgetBraiinsPoolData } from "./categories/braiins-pool.slint";
import { WidgetRemoteImageData } from "./categories/remote-image.slint";
import { BlockchainData } from "./categories/blockchain-data.slint";
import { RemoteWidgetData } from "./categories/remote-widget.slint";
import { WidgetHalvingCountdownData } from "./categories/halving-countdown.slint";
export { WidgetSize }

export enum WidgetKind {
    Clock,
    TickerBtc,
    BlockHeight,
    BraiinsPool,
    RemoteImage,
    BlockchainData,
    RemoteWidget,
    HalvingCountdown,
}

export struct Widget {
    id: string,
    row: int,
    col: int,
    size: WidgetSize,
    kind: WidgetKind,
    clock: WidgetClockData,
    ticker-btc: WidgetBtcData,
    blockheight: WidgetBlockHeightData,
    braiins-pool: WidgetBraiinsPoolData,
    remote-image: WidgetRemoteImageData,
    blockchain-data: BlockchainData,
    remote-widget: RemoteWidgetData,
    halving-countdown: WidgetHalvingCountdownData,
}
