import { Theme } from "../style/theme.slint";

export enum WidgetSize {
    Small,
    Medium,
    Large,
    Full,
}

export enum FontStyle {
  Light,
  Medium,
  Bold
}

export enum TickerTimeFrame {
  Day1,
  Week1,
  Week2,
  Month1,
  Month3,
  Month6,
  Year1,
  Year2,
  Year5,
  All
}

export global WidgetUtilsAdapter {
  pure public function font-style-to-font-weight(font-style: FontStyle) -> int {
    if font-style == FontStyle.Light {
      return Theme.font.weight.regular;
    } else if font-style == FontStyle.Medium {
      return Theme.font.weight.semi-bold;
    } else {
      return Theme.font.weight.bold;
    }
  }
}

export global BaseDimensions {
  pure callback widget-width-int(size: WidgetSize) -> int;

  public pure function widget-width(size: WidgetSize) -> length {
    return widget-width-int(size) * 1px;
  }

  pure callback widget-height-int(size: WidgetSize) -> int;

  public pure function widget-height(size: WidgetSize) -> length {
    return widget-height-int(size) * 1px;
  }
}
