@rust-attr(derive(serde::Serialize, serde::Deserialize))
export enum WidgetType {
    ClockAnalogRound,
    ClockAnalogRect,
    ClockDigital,
}

@rust-attr(derive(serde::Serialize, serde::Deserialize))
export enum WidgetSize {
    Small,
    Medium,
    Large,
    Full,
}

export struct Widget {
    widget-type: WidgetType,
    widget-size: WidgetSize,
    widget-data: [string],
    row: int,
    col: int,
}

export component WidgetContainer inherits Rectangle {
    property <length> widget-base-width: 320px;
    property <length> widget-base-height: 220px;
    property <length> top-bar-height: 40px;

    in property <WidgetSize> size;
    in property <int> position-row;
    in property <int> position-col;

    x: self.position-col * widget-base-width;
    y: self.position-row * widget-base-height + top-bar-height;
    width: self.get-col-span() * widget-base-width;
    height: self.get-row-span() * widget-base-height;

    background: black;

    @children

    pure function get-row-span() -> int {
        if self.size == WidgetSize.Small {
            return 1;
        }
        else if self.size == WidgetSize.Medium {
            return 1;
        }
        else if self.size == WidgetSize.Large {
            return 2;
        }
        // Full screen
        return 2;
    }

    pure function get-col-span() -> int {
        if self.size == WidgetSize.Small {
            return 1;
        }
        else if self.size == WidgetSize.Medium {
            return 2;
        }
        else if self.size == WidgetSize.Large {
            return 2;
        }
        // Full screen
        return 4;
    }
}
