// Copyright (C) 2026  Braiins Systems s.r.o.

// Shared story discovery logic — included by both `build.rs` (static mode)
// and `stories/build.rs` (hot-reload cdylib).

use std::fmt::Write;
use std::path::{Path, PathBuf};
use std::{env, fs};

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap_or_else(|_| panic!("OUT_DIR not set"));
    let workspace_root = find_workspace_root();

    let mut generated = String::from("// AUTO-GENERATED by build.rs — do not edit\n");
    let mut entries: Vec<(String, String)> = Vec::new();

    let workspace_toml = workspace_root.join("Cargo.toml");
    println!("cargo:rerun-if-changed={}", workspace_toml.display());

    // Each workspace member directory is its own crate; story discovery scans
    // them all so adding a new member never silently misses stories. Member
    // entries with overlapping prefixes (e.g. `bmc-render` and `bmc-render/macros`)
    // are deduplicated by inserting only roots that aren't already nested
    // under another scanned root — otherwise the same `*.stories.rs` shows up
    // twice in the generated module list.
    let mut members = workspace_members(&workspace_toml);
    members.sort();
    let mut roots: Vec<PathBuf> = Vec::new();
    for member in members {
        let dir = workspace_root.join(&member);
        if !dir.exists() {
            continue;
        }
        if roots.iter().any(|r| dir.starts_with(r)) {
            continue;
        }
        roots.push(dir);
    }

    for dir in &roots {
        scan_recursive(dir, &mut entries);
        println!("cargo:rerun-if-changed={}", dir.display());
    }

    entries.sort();

    for (mod_name, abs_path) in &entries {
        validate_mod_name(mod_name, abs_path);
        // `{:?}` produces a properly-escaped Rust string literal, neutralising
        // paths that contain `"` or `\` (rare on Linux, but legal filenames).
        writeln!(generated, "#[path = {abs_path:?}]").expect("BUG: write to string");
        writeln!(generated, "mod {mod_name}_stories;").expect("BUG: write to string");
    }

    fs::write(Path::new(&out_dir).join("stories.rs"), generated)
        .expect("BUG: failed to write stories.rs");
}

/// Parse the workspace `Cargo.toml` and return the list of `members`.
///
/// `[workspace] members = [...]` is the source of truth for what crates
/// exist; using it here means a newly added member crate's stories get
/// picked up automatically.
fn workspace_members(workspace_toml: &Path) -> Vec<String> {
    let content = fs::read_to_string(workspace_toml).unwrap_or_else(|e| {
        panic!(
            "BUG: failed to read workspace Cargo.toml at {}: {e}",
            workspace_toml.display()
        )
    });
    let parsed: toml::Value = content.parse().unwrap_or_else(|e| {
        panic!(
            "BUG: workspace Cargo.toml is not valid TOML at {}: {e}",
            workspace_toml.display()
        )
    });
    parsed
        .get("workspace")
        .and_then(|w| w.get("members"))
        .and_then(toml::Value::as_array)
        .map(|arr| {
            arr.iter()
                .filter_map(toml::Value::as_str)
                .map(str::to_owned)
                .collect()
        })
        .unwrap_or_default()
}

/// Walk up from `CARGO_MANIFEST_DIR` to find the workspace root
/// (directory containing a `Cargo.toml` with `[workspace]`).
fn find_workspace_root() -> std::path::PathBuf {
    let manifest_dir =
        env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| panic!("CARGO_MANIFEST_DIR not set"));
    let mut dir = Path::new(&manifest_dir).to_path_buf();
    loop {
        let toml = dir.join("Cargo.toml");
        if toml.exists() {
            let content = fs::read_to_string(&toml).unwrap_or_default();
            if content.contains("[workspace]") {
                return dir;
            }
        }
        assert!(
            dir.pop(),
            "BUG: workspace root not found from {manifest_dir}"
        );
    }
}

/// Panic if `mod_name` would not produce a valid Rust identifier when
/// suffixed with `_stories`. Without this check, an unusual filename
/// (e.g. `foo.bar.stories.rs` → `foo.bar`) would produce broken codegen
/// and the failure would surface as a parse error inside the generated
/// `stories.rs` rather than at the source.
fn validate_mod_name(mod_name: &str, source: &str) {
    let mut chars = mod_name.chars();
    let first_ok = chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_');
    let rest_ok = chars.all(|c| c.is_ascii_alphanumeric() || c == '_');
    assert!(
        first_ok && rest_ok,
        "story file `{source}` produces invalid Rust mod name `{mod_name}`; \
         filename stem must start with an ASCII letter or underscore and \
         contain only ASCII alphanumerics and underscores"
    );
}

/// Recursively scan `dir` for `*.stories.rs` files.
fn scan_recursive(dir: &Path, entries: &mut Vec<(String, String)>) {
    let read =
        fs::read_dir(dir).unwrap_or_else(|_| panic!("BUG: failed to read {}", dir.display()));

    for entry in read {
        let entry = entry.unwrap_or_else(|_| panic!("BUG: failed to iterate {}", dir.display()));
        let path = entry.path();

        if path.is_dir() {
            println!("cargo:rerun-if-changed={}", path.display());
            scan_recursive(&path, entries);
            continue;
        }

        let name = path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or_default();

        if name.ends_with(".stories.rs") {
            let mod_name = name
                .strip_suffix(".stories.rs")
                .expect("BUG: suffix already checked");
            entries.push((mod_name.to_owned(), path.display().to_string()));
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }
}
