#!/bin/sh /etc/rc.common

START=92

boot() {
    grep -q ' /nix ' /proc/mounts || return 0
    profile_dir="/nix/var/nix/gcroots/profiles/bmc"
    current="$profile_dir/current"
    if [ -L "$current" ]; then
        entrypoint="$(readlink -f "$current")/core/activation/entrypoint"
        if [ -x "$entrypoint" ]; then
            PROFILE_NEW_GENERATION="$(readlink -f "$current")" \
            PROFILE_OLD_GENERATION="" \
                "$entrypoint"
        fi
    fi
}
