[package]
name = "ii-net-drv"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bstr.workspace = true
esp32 = { path = "../esp32" }
ii-net = { path = "../ii-net" }
log.workspace = true
pnet.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
tokio = { workspace = true, features = ["full"] }

[[example]]
name = "get_mac_address"
path = "examples/get_mac_address.rs"

[[example]]
name = "get_ipv4_address"
path = "examples/get_ipv4_address.rs"

[package.metadata.cargo-machete]
ignored = ["strum"]

[lints]
workspace = true
