// Copyright (C) 2025  Braiins Systems s.r.o.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Braiins Systems s.r.o. and Braiins Forge s.r.o. each reserve the right
// to grant any party a license to this program, or any part thereof,
// under any terms, and such a grant shall be considered distinct from
// the grant above.

syntax = "proto3";

package braiins.bmc.web;

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";

// Request message to login
message LoginRequest {
  string password = 1;
}

// Response message for login
message LoginResponse {
  // Token to be used for authentication
  string token = 1;
  // Authentication token validity/timeout in seconds.
  // Token validity refreshed to this value with each request.
  uint32 timeout_s = 2;
}

service AuthenticationService {
  // Method to check if the client is currently authenticated
  rpc IsAuthenticated(google.protobuf.Empty) returns (google.protobuf.BoolValue);
  // Method to login and retrieve authentication token
  rpc Login(LoginRequest) returns (LoginResponse);
  // Method to logout
  rpc Logout(google.protobuf.Empty) returns (google.protobuf.Empty);
}
