syntax = "proto3";

package braiins.bmc.web;

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";

// Request message to login
message LoginRequest {
  string password = 1;
}

// Response message for login
message LoginResponse {
  // Token to be used for authentication
  string token = 1;
  // Authentication token validity/timeout in seconds.
  // Token validity refreshed to this value with each request.
  uint32 timeout_s = 2;
}

service AuthenticationService {
  // Method to check if the client is currently authenticated
  rpc IsAuthenticated(google.protobuf.Empty) returns (google.protobuf.BoolValue);
  // Method to login and retrieve authentication token
  rpc Login(LoginRequest) returns (LoginResponse);
}
