syntax = "proto3";

package braiins.bmc.web;

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";

message Scene {
  // required
  string id = 1;
  // required
  bool enabled = 2;
  // required, minimum 1
  uint32 duration_sec = 3;
  // required
  oneof kind {
    Fullscreen fullscreen = 4;
    Combined combined = 5;
  }

  message Fullscreen {
    // required
    Widget widget = 1;
  }

  message Combined {
    repeated Widget widgets = 1;
  }
}

message GetScenesResponse {
  // sorted by position, asc
  repeated Scene scenes = 1;
}

message AddFullscreenSceneRequest {
  // required
  // backend cares only about kind discriminant, frontend can send "empty" message with default values
  WidgetKind widget_kind = 1;
}

message UpdateSceneRequest {
  // required
  string id = 1;
  // required
  bool enabled = 2;
  // required, minimum 1
  uint32 duration_sec = 3;
}

message MoveSceneRequest {
  // required
  string id = 1;
  // required, zero based
  uint32 index = 2;
}

message SceneRequest {
  // required
  string id = 1;
}

message SceneResponse {
  // required
  Scene scene = 1;
}

// Position of the widget on the combined scene grid
// Full screen widget position is row: 0, col: 0
message WidgetPosition {
  uint32 row = 1;
  uint32 col = 2;
}

enum WidgetSize {
  WIDGET_SIZE_UNSPECIFIED = 0;
  WIDGET_SIZE_SMALL = 1;
  WIDGET_SIZE_MEDIUM = 2;
  WIDGET_SIZE_LARGE = 3;
  WIDGET_SIZE_FULL = 4;
}

message Widget {
  // required
  string id = 1;
  // required
  WidgetPosition position = 2;
  // required
  WidgetSize size = 3;
  // required
  WidgetKind kind = 4;
}

message AddWidgetRequest {
  // required
  string scene_id = 1;
  // required
  WidgetPosition position = 2;
  // required
  WidgetSize size = 3;
  // required
  // backend cares only about kind discriminant, frontend can send "empty" message with default values
  WidgetKind kind = 4;
}

message UpdateWidgetRequest {
  // required
  string id = 1;
  // required
  string scene_id = 2;
  // required
  WidgetPosition position = 3;
  // required
  WidgetSize size = 4;
  // required
  // not allowed to switch kind, only update inner values
  WidgetKind kind = 5;
}

message WidgetRequest {
  // required
  string id = 1;
  // required
  string scene_id = 2;
}

message WidgetResponse {
  // required
  Widget widget = 1;
}

message WidgetKind {
  // required
  oneof value {
    ClockWidget clock = 1;
  }
}

message ClockWidget {
  // required
  ClockStyle clock_style = 1;
  // required
  FontStyle numbers_font_style = 2;
  // required, used only in fullscreen size
  bool show_date = 3;
  // required, used only in digital style
  bool show_seconds = 4;
  // required
  bool show_timezone = 5;
  // optional, empty value means - use system timezone
  optional string timezone = 6;

  enum ClockStyle {
    CLOCK_STYLE_UNSPECIFIED = 0;
    CLOCK_STYLE_ANALOG_ROUND = 1;
    CLOCK_STYLE_ANALOG_RECT = 2;
    CLOCK_STYLE_DIGITAL = 3;
  }
}

// Font style
enum FontStyle {
  FONT_STYLE_UNSPECIFIED = 0;
  FONT_STYLE_LIGHT = 1;
  FONT_STYLE_MEDIUM = 2;
  FONT_STYLE_BOLD = 3;
}

message BrightnessInfo {
  uint32 value = 1;
  uint32 min = 2;
  uint32 max = 3;
  uint32 step = 4;
}

message DisplaySettingsResponse {
  BrightnessInfo brightness = 1;
}

// Configures scenes & widgets for individual scenes.
// CQRS pattern, commands only modify state, queries only return state.
// FE should fetch scene(s) after executing command to get into proper state.
service ConfigurationService {
  // Get all scenes
  rpc GetScenes(google.protobuf.Empty) returns (GetScenesResponse);
  // Get single scene by ID. This is an optimization for FE to avoid fetching all scenes
  rpc GetScene(SceneRequest) returns (SceneResponse);
  // Add fullscreen scene. It contains single fullscreen widget at position (0,0).
  // It will use default values for widget kind specific params.
  // Returns ID of thew new scene.
  rpc AddFullscreenScene(AddFullscreenSceneRequest) returns (google.protobuf.StringValue);
  // Add combined screen without any widget in it.
  // Returns ID of thew new scene.
  rpc AddCombinedScene(google.protobuf.Empty) returns (google.protobuf.StringValue);
  // Update only common properties for fullscreen and combined scene, not widgets.
  rpc UpdateScene(UpdateSceneRequest) returns (google.protobuf.Empty);
  // Move scene to different index
  rpc MoveScene(MoveSceneRequest) returns (google.protobuf.Empty);
  // Add copy of a scene, right next to it (index + 1).
  // Returns ID of thew new scene.
  rpc CloneScene(SceneRequest) returns (google.protobuf.StringValue);
  // Remove scene by ID.
  rpc RemoveScene(SceneRequest) returns (google.protobuf.Empty);
  // Keep preview screen shown on the display while stream is open.
  // This should be called:
  //   fullscreen scene - while modal is open, on the list page
  //   combined scene - whole time on the grid page
  rpc PreviewScene(SceneRequest) returns (stream google.protobuf.Empty);
  // Add widget into the scene. You need to specify size, position, kind.
  // It will use default values for widget kind specific params.
  // Returns ID of the new widget.
  rpc AddWidget(AddWidgetRequest) returns (google.protobuf.StringValue);
  // Update widget by ID. You need to specify size, position, kind.
  // It will use passed values for widget kind specific params.
  rpc UpdateWidget(UpdateWidgetRequest) returns (google.protobuf.Empty);
  // Remove widget by ID.
  rpc RemoveWidget(WidgetRequest) returns (google.protobuf.Empty);
  rpc SetBrightness(google.protobuf.UInt32Value) returns (google.protobuf.Empty);
  rpc GetDisplaySettings(google.protobuf.Empty) returns (DisplaySettingsResponse);
}
