syntax = "proto3";

package braiins.bmc.web;

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";
import "web/shared.proto";

message BrightnessInfo {
  uint32 value = 1;
  uint32 min = 2;
  uint32 max = 3;
  uint32 step = 4;
}

message DisplaySettingsResponse {
  BrightnessInfo brightness = 1;
  BrightnessInfo brightness_nightmode = 2;
  bool nightmode_enabled = 3;
  TimeInterval nightmode_interval = 4;
}

message TimeInterval {
  string from = 1; // Expected format: HH:MM, Range 00:00 - 23:59
  string to = 2; // Expected format: HH:MM, Range 00:00 - 23:59
}

message SoundVolume {
  uint32 value = 1;
  uint32 min = 2;
  uint32 max = 3;
  uint32 step = 4;
}

message SoundVolumeSettingsResponse {
  SoundVolume volume = 1;
  SoundVolume volume_nightmode = 2;
}

message ListSoundsResponse {
  repeated braiins.bmc.web.SoundInfo sounds = 1;
}

message PlaySoundRequest {
  string sound_id = 1;
}

message GeneralSettingsDataResponse {
  braiins.bmc.web.TimeFormat time_format = 1;
  braiins.bmc.web.DateFormat date_format = 2;
  braiins.bmc.web.NumberFormat number_format = 3;
  google.protobuf.BoolValue data_collection = 4;
  google.protobuf.BoolValue show_seconds_status_bar = 5;
  braiins.bmc.web.Weekday first_day_of_week = 6;
  braiins.bmc.web.TemperatureUnit temperature_unit = 7;
  braiins.bmc.web.UnitSystem unit_system = 8;
}

message SetTimeFormatRequest {
  braiins.bmc.web.TimeFormat time_format = 1;
}

message SetDateFormatRequest {
  braiins.bmc.web.DateFormat date_format = 1;
}

message SetNumberFormatRequest {
  braiins.bmc.web.NumberFormat number_format = 1;
}

message SetTemperatureUnitRequest {
  braiins.bmc.web.TemperatureUnit temperature_unit = 1;
}

message SetFirstDayOfWeekRequest {
  braiins.bmc.web.Weekday first_day_of_week = 1;
}

message SetUnitSystemRequest {
  braiins.bmc.web.UnitSystem unit_system = 1;
}

message LedSettingsResponse {
  bool led_enabled = 1;
  bool led_enabled_nightmode = 2;
}

message BootSoundSettingsResponse {
  bool boot_sound_enabled = 1;
}

service ConfigurationService {
  rpc SetBrightness(google.protobuf.UInt32Value) returns (google.protobuf.Empty);
  rpc GetDisplaySettings(google.protobuf.Empty) returns (DisplaySettingsResponse);
  rpc SetBrightnessNightmode(google.protobuf.UInt32Value) returns (google.protobuf.Empty);
  rpc SetNightmodeEnabled(google.protobuf.BoolValue) returns (google.protobuf.Empty);
  rpc SetNightmodeInterval(TimeInterval) returns (google.protobuf.Empty);
  rpc GetSoundVolumeSettings(google.protobuf.Empty) returns (SoundVolumeSettingsResponse);
  rpc SetSoundVolume(google.protobuf.UInt32Value) returns (google.protobuf.Empty);
  rpc SetSoundVolumeNightmode(google.protobuf.UInt32Value) returns (google.protobuf.Empty);
  rpc ListSounds(google.protobuf.Empty) returns (ListSoundsResponse);
  rpc PlaySound(PlaySoundRequest) returns (google.protobuf.Empty);
  rpc GetGeneralSettingsData(google.protobuf.Empty) returns (GeneralSettingsDataResponse);
  rpc SetTimeFormat(SetTimeFormatRequest) returns (google.protobuf.Empty);
  rpc SetDateFormat(SetDateFormatRequest) returns (google.protobuf.Empty);
  rpc SetNumberFormat(SetNumberFormatRequest) returns (google.protobuf.Empty);
  rpc SetDataCollection(google.protobuf.BoolValue) returns (google.protobuf.Empty);
  rpc ShowSecondsInStatusBar(google.protobuf.BoolValue) returns (google.protobuf.Empty);
  rpc SetFirstDayOfWeek(SetFirstDayOfWeekRequest) returns (google.protobuf.Empty);
  rpc SetTemperatureUnit(SetTemperatureUnitRequest) returns (google.protobuf.Empty);
  rpc SetUnitSystem(SetUnitSystemRequest) returns (google.protobuf.Empty);
  rpc GetLedSettings(google.protobuf.Empty) returns (LedSettingsResponse);
  rpc SetLedEnabled(google.protobuf.BoolValue) returns (google.protobuf.Empty);
  rpc SetLedEnabledNightmode(google.protobuf.BoolValue) returns (google.protobuf.Empty);
  rpc GetBootSoundSettings(google.protobuf.Empty) returns (BootSoundSettingsResponse);
  rpc SetBootSoundEnabled(google.protobuf.BoolValue) returns (google.protobuf.Empty);
}
