syntax = "proto3";

package braiins.bmc.web;

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";
import "web/network.proto";
import "web/shared.proto";

message SettingsRequest {
  braiins.bmc.web.TimeFormat time_format = 1;
  string timezone_id = 2;
  braiins.bmc.web.DateFormat date_format = 3;
  braiins.bmc.web.NumberFormat number_format = 4;
  optional string password = 5;
  bool data_collection = 6;
  braiins.bmc.web.TemperatureUnit temperature_unit = 7;
  braiins.bmc.web.UnitSystem unit_system = 8;
}

message SettingsDataResponse {
  braiins.bmc.web.TimeFormat time_format = 1;
  repeated braiins.bmc.web.Timezone timezones = 2;
  string timezone_id = 3;
  braiins.bmc.web.DateFormat date_format = 4;
  braiins.bmc.web.NumberFormat number_format = 5;
  google.protobuf.BoolValue data_collection = 6;
  braiins.bmc.web.TemperatureUnit temperature_unit = 7;
  braiins.bmc.web.UnitSystem unit_system = 8;
}

service InitialSetupService {
  rpc SetWifi(SetWifiRequest) returns (google.protobuf.Empty);
  rpc ScanWifi(google.protobuf.Empty) returns (ScanWifiResponse);
  rpc GetSettingsData(google.protobuf.Empty) returns (SettingsDataResponse);
  rpc SetupDevice(SettingsRequest) returns (google.protobuf.Empty);
}
