syntax = "proto3";

package braiins.bmc.web;

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";

message Scene {
  // required
  string id = 1;
  // required
  bool enabled = 2;
  // optional, empty value means - use default cycle duration, minimum 1
  optional uint32 cycle_duration_sec = 3;
  // required
  oneof kind {
    Fullscreen fullscreen = 4;
    Combined combined = 5;
  }

  message Fullscreen {
    // required
    Widget widget = 1;
  }

  message Combined {
    repeated Widget widgets = 1;
  }
}

message GetScenesResponse {
  // sorted by position, asc
  repeated Scene scenes = 1;
}

message AddFullscreenSceneRequest {
  // required
  // backend cares only about kind discriminant, frontend can send "empty" message with default values
  WidgetKind widget_kind = 1;
}

message UpdateSceneRequest {
  // required
  string id = 1;
  // required
  bool enabled = 2;
  // optional, empty value means - use default cycle duration, minimum 1
  optional uint32 cycle_duration_sec = 3;
}

message MoveSceneRequest {
  // required
  string id = 1;
  // required, zero based
  uint32 index = 2;
}

message SceneResponse {
  // required
  Scene scene = 1;
}

// Position of the widget on the combined scene grid
// Full screen widget position is row: 0, col: 0
message WidgetPosition {
  uint32 row = 1;
  uint32 col = 2;
}

enum WidgetSize {
  WIDGET_SIZE_UNSPECIFIED = 0;
  WIDGET_SIZE_SMALL = 1;
  WIDGET_SIZE_MEDIUM = 2;
  WIDGET_SIZE_LARGE = 3;
  WIDGET_SIZE_FULL = 4;
}

message Widget {
  // required
  string id = 1;
  // required
  WidgetPosition position = 2;
  // required
  WidgetSize size = 3;
  // required
  WidgetKind kind = 4;
}

message AddWidgetRequest {
  // required
  string scene_id = 1;
  // required
  WidgetPosition position = 2;
  // required
  WidgetSize size = 3;
  // required
  // backend cares only about kind discriminant, frontend can send "empty" message with default values
  WidgetKind kind = 4;
}

message UpdateWidgetRequest {
  // required
  string id = 1;
  // required
  string scene_id = 2;
  // required
  WidgetPosition position = 3;
  // required
  WidgetSize size = 4;
  // required
  // not allowed to switch kind, only update inner values
  WidgetKind kind = 5;
}

message RemoveWidgetRequest {
  // required
  string id = 1;
  // required
  string scene_id = 2;
}

message WidgetResponse {
  // required
  Widget widget = 1;
}

message WidgetKind {
  // required
  oneof value {
    ClockWidget clock = 1;
    TickerBtcWidget ticker_btc = 2;
    BlockHeightWidget block_height = 3;
  }
}

message ClockWidget {
  // required
  ClockStyle clock_style = 1;
  // required
  FontStyle numbers_font_style = 2;
  // required, used only in fullscreen size
  bool show_date = 3;
  // required, used only in digital style
  bool show_seconds = 4;
  // required
  bool show_timezone = 5;
  // optional, empty value means - use system timezone
  optional string timezone = 6;

  enum ClockStyle {
    CLOCK_STYLE_UNSPECIFIED = 0;
    CLOCK_STYLE_ANALOG_ROUND = 1;
    CLOCK_STYLE_ANALOG_RECT = 2;
    CLOCK_STYLE_DIGITAL = 3;
  }
}

message TickerBtcWidget {
  // required
  TimeFrame time_frame = 1;

  enum TimeFrame {
    TIME_FRAME_UNSPECIFIED = 0;
    TIME_FRAME_DAY_1 = 1;
    TIME_FRAME_WEEK_1 = 2;
    TIME_FRAME_WEEK_2 = 3;
    TIME_FRAME_MONTH_1 = 4;
    TIME_FRAME_MONTH_3 = 5;
    TIME_FRAME_MONTH_6 = 6;
    TIME_FRAME_YEAR_1 = 7;
    TIME_FRAME_YEAR_2 = 8;
    TIME_FRAME_YEAR_5 = 9;
    TIME_FRAME_ALL = 10;
  }
}

message BlockHeightWidget {
  // required
  bool show_timestamp = 1;
  // required
  FontStyle numbers_font_style = 2;
}

// Font style
enum FontStyle {
  FONT_STYLE_UNSPECIFIED = 0;
  FONT_STYLE_LIGHT = 1;
  FONT_STYLE_MEDIUM = 2;
  FONT_STYLE_BOLD = 3;
}

enum SceneCyclingTransition {
  SCENE_CYCLING_TRANSITION_UNSPECIFIED = 0;
  SCENE_CYCLING_TRANSITION_SLIDE = 1;
  SCENE_CYCLING_TRANSITION_FADE = 2;
}

message SceneCycling {
  // required
  bool automatic_cycling_enabled = 1;
  // required, minimum 1
  uint32 automatic_cycling_default_duration_sec = 2;
  // required
  SceneCyclingTransition transition = 3;
}

message GetSceneCyclingResponse {
  // required
  SceneCycling scene_cycling = 1;
}

message SetSceneCyclingRequest {
  // required
  SceneCycling scene_cycling = 1;
}

// Configures scenes & widgets for individual scenes.
// CQRS pattern, commands only modify state, queries only return state.
// FE should fetch scene(s) after executing command to get into proper state.
//
// FE implementation tips:
//
// add new scene:
// - combined:
//   - call `AddCombinedScene`
//     - creates empty scene without any widgets
//     - response contains ID of newly created scene
//   - redirect user to page with grid
//   - call `GetScene`
//   - call `PreviewScene` & keep stream open while user is on grid page
// - fullscreen:
//   - call `AddFullscreenScene` - you *don't need* to specify inner values for widget kind (BE ignores them)
//     - creates scene with single fullscreen widget (with default values, decided by BE)
//     - response contains ID of newly created scene
//   - call `GetScene` & show modal to edit fullscreen widget
//   - call `PreviewScene` & keep stream open while modal is open
//
// update scene:
// - combined & fullscreen:
//   - call `UpdateScene`
//   - call `GetScene`
//
// move scene:
// - combined & fullscreen:
//   - call `MoveScene`
//   - call `GetScenes`
//
// clone scene:
// - combined & fullscreen:
//   - call `CloneScene`
//   - call `GetScenes`
//
// remove scene:
// - combined & fullscreen:
//   - call `RemoveScene`
//   - call `GetScenes`
//
// add widget:
// - combined:
//   - call `AddWidget` - you *don't need* to specify inner values for widget kind (BE ignores them)
//     - response contains ID of newly created widget
//   - call `GetScene` & show modal to edit new widget
//
// update widget:
// - combined & fullscreen:
//   - call `UpdateWidget` - you *must* specify all inner values for widget kind
//   - call `GetScene`
//
// remove widget:
// - combined & fullscreen:
//   - call `RemoveWidget`
//   - call `GetScene`
service SceneManagementService {
  // Get all scenes
  rpc GetScenes(google.protobuf.Empty) returns (GetScenesResponse);
  // Get single scene by ID. This is an optimization for FE to avoid fetching all scenes
  rpc GetScene(google.protobuf.StringValue) returns (SceneResponse);
  // Add fullscreen scene. It contains single fullscreen widget at position (0,0).
  // It will use default values for widget kind specific params.
  // Returns ID of thew new scene.
  rpc AddFullscreenScene(AddFullscreenSceneRequest) returns (google.protobuf.StringValue);
  // Add combined screen without any widget in it.
  // Returns ID of thew new scene.
  rpc AddCombinedScene(google.protobuf.Empty) returns (google.protobuf.StringValue);
  // Update only common properties for fullscreen and combined scene, not widgets.
  // This is not patch, but rather full update.
  rpc UpdateScene(UpdateSceneRequest) returns (google.protobuf.Empty);
  // Move scene to different index
  rpc MoveScene(MoveSceneRequest) returns (google.protobuf.Empty);
  // Add copy of a scene by ID, placed right next to it (index + 1).
  // Returns ID of thew new scene.
  rpc CloneScene(google.protobuf.StringValue) returns (google.protobuf.StringValue);
  // Remove scene by ID.
  rpc RemoveScene(google.protobuf.StringValue) returns (google.protobuf.Empty);
  // Keep preview screen shown on the display while stream is open. Takes scene ID as an argument.
  rpc PreviewScene(google.protobuf.StringValue) returns (stream google.protobuf.Empty);
  // Add widget into the scene. You need to specify size, position, kind.
  // It will use default values for widget kind specific params.
  // Returns ID of the new widget.
  rpc AddWidget(AddWidgetRequest) returns (google.protobuf.StringValue);
  // Update widget by ID. You need to specify size, position, kind.
  // It will use passed values for widget kind specific params.
  // This is not patch, but rather full update.
  rpc UpdateWidget(UpdateWidgetRequest) returns (google.protobuf.Empty);
  // Remove widget by ID.
  rpc RemoveWidget(RemoveWidgetRequest) returns (google.protobuf.Empty);
  // Get scene cycling
  rpc GetSceneCycling(google.protobuf.Empty) returns (GetSceneCyclingResponse);
  // Set scene cycling
  rpc SetSceneCycling(SetSceneCyclingRequest) returns (google.protobuf.Empty);
}
