syntax = "proto3";

package braiins.bmc.web;

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";
import "web/shared.proto";

message CreatePasswordRequest {
  string password = 1;
}

message ChangePasswordRequest {
  string current_password = 1;
  string new_password = 2;
}

message RemovePasswordRequest {
  string password = 1;
}

// Response containing the current timezone
message GetTimezoneResponse {
  // Current timezone
  braiins.bmc.web.Timezone timezone = 1;
}

// Request to set the timezone
message SetTimezoneRequest {
  // Timezone to set
  string id = 1;
}

// Response containing the list of available timezones
message GetTimezoneListResponse {
  // List of available timezones
  repeated braiins.bmc.web.Timezone timezones = 1;
}

// Service to provide information about system
service SystemService {
  rpc HasPassword(google.protobuf.Empty) returns (google.protobuf.BoolValue);
  rpc CreatePassword(CreatePasswordRequest) returns (google.protobuf.Empty);
  rpc ChangePassword(ChangePasswordRequest) returns (google.protobuf.Empty);
  rpc RemovePassword(RemovePasswordRequest) returns (google.protobuf.Empty);
  // Get the current timezone
  rpc GetTimezone(google.protobuf.Empty) returns (GetTimezoneResponse);
  // Set the timezone
  rpc SetTimezone(SetTimezoneRequest) returns (google.protobuf.Empty);
  // Get the list of available timezones
  rpc GetTimezoneList(google.protobuf.Empty) returns (GetTimezoneListResponse);
  rpc FactoryReset(google.protobuf.Empty) returns (google.protobuf.Empty);
}
