syntax = "proto3";

package braiins.bmc.web;

// Structure to handle system details
message Metadata {
  // OS version
  string version = 1;
}

message GetSystemMetadataRequest {}

// Request for set password action.
message SetPasswordRequest {
  optional string password = 1;
}

// Response for set password action.
message SetPasswordResponse {}

// Service to provide information about system
service SystemService {
  // Get detailed information about the system
  rpc GetMetadata(GetSystemMetadataRequest) returns (Metadata);
  // Method to set password
  rpc SetPassword(SetPasswordRequest) returns (SetPasswordResponse);
}
