syntax = "proto3";

package braiins.bmc.web;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

message UpgradeMetadata {
  string hash = 1;
  string version = 2;
  google.protobuf.Timestamp release_date = 3;
  string description = 4;
}

message ReleaseInfo {
  string version = 1;
  string description = 2;
}

message CheckForUpgradeResponse {
  UpgradeMetadata latest_release = 1;
  repeated ReleaseInfo previous_releases = 2;
}

message DownloadFirmwareRequest {
  string hash = 1;
}

message DownloadProgress {
  float downloaded_mb = 1;
  float total_mb = 2;
}

message DownloadFinished {
  string hash = 1;
}

message DownloadFirmwareResponse {
  oneof state {
    DownloadProgress download_progress = 1;
    DownloadFinished download_finished = 2;
  }
}

message UpgradeRequest {
  string hash = 1;
}

service UpgradeService {
  rpc CheckForUpgrade(google.protobuf.Empty) returns (CheckForUpgradeResponse);
  rpc DownloadFirmware(DownloadFirmwareRequest) returns (stream DownloadFirmwareResponse);
  rpc Upgrade(UpgradeRequest) returns (google.protobuf.Empty);
}
