[package]
name = "bmc-wasm-thin-protocol"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
bincode = { workspace = true }
bmc-wasm-protocol = { path = "../bmc-wasm-runtime/protocol" }
nix = { workspace = true }

[dev-dependencies]
libc = { workspace = true }
serial_test = { workspace = true }
