[package]
name = "bmc"
version = "0.1.0"
edition = "2024"
authors = ["Braiins <braiins@braiins.com>"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
axum-extra = { workspace = true, features = [
    "cookie",
    "form",
    "multipart",
    "typed-header",
] }
bmc-audio.workspace = true
bmc-button.workspace = true
bmc-display.workspace = true
bmc-grpc.workspace = true
bmc-ipc.workspace = true
bmc-led.workspace = true
bmc-platform.workspace = true
bmc-scheduler.workspace = true
bmc-shared-ii-net.workspace = true
bmc-shared-time.workspace = true
bmc-shared-utils.workspace = true
bmc-support.workspace = true
bmc-upgrade = { workspace = true, features = ["disk-check"] }
bmc-widget.workspace = true
bmc-widget-protocol.workspace = true
chrono = { workspace = true }
chrono-tz.workspace = true
futures.workspace = true
http.workspace = true
humantime-serde.workspace = true
hyper.workspace = true
image.workspace = true
indexmap.workspace = true
itertools.workspace = true
mime_guess.workspace = true
prost-types.workspace = true
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
tap.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-stream.workspace = true
tokio-util = { workspace = true, features = ["full"] }
tonic.workspace = true
tonic-middleware.workspace = true
tonic-reflection.workspace = true
tonic-types.workspace = true
tonic-web.workspace = true
tooling-std.workspace = true
tower = { workspace = true, features = ["steer"] }
tower-cookies.workspace = true
tower-http = { workspace = true, features = [
    "compression-br",
    "compression-deflate",
    "compression-gzip",
    "compression-zstd",
    "normalize-path",
] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
