import { Images } from "../../style/images.slint";
import { AlarmAdapter } from "../../controls/adapters.slint";
import { Palette } from "../../style/palette.slint";
import { DateTime } from "../../controls/common.slint";
import { Ring } from "../../components/ring.slint";

export component Alarm inherits Rectangle {
    background: Palette.black;
    in property <DateTime> datetime;
    in property <string> alarm-label <=> AlarmAdapter.label;
    in property <bool> show_snooze <=> AlarmAdapter.snooze-visible;

    property <string> time: datetime.is-24-format ? datetime.time-24 : datetime.time-12;

    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            alignment: center;
            Rectangle {
                width: root.width;
                height: root.height;
                background: Palette.black;
                border-radius: 16px;
                clip: true;

                // Geometry & animation parameters
                property <length> spacing: 75px; // exact gap between ring radii
                property <int> ring_count: 3;  // five simultaneous rings
                property <duration> period: 2000ms;  // center -> edge (then wrap)

                // Smallest ring radius = 350px (diameter 700px)
                property <length> start_r: 350px;
                property <length> end_r:   self.start_r + self.ring_count * self.spacing;
                property <length> fade_distance: self.end_r - self.start_r;

                property <duration> t_base: mod(animation-tick(), self.period);

                Ring {
                    index: 0;
                    ring_count: parent.ring_count;
                    period: parent.period;
                    t_base: parent.t_base;
                    start_r: parent.start_r;
                    end_r: parent.end_r;
                    fade_distance: parent.fade_distance;
                    parent_width: parent.width;
                    parent_height: parent.height;
                }

                Ring {
                    index: 1;
                    ring_count: parent.ring_count;
                    period: parent.period;
                    t_base: parent.t_base;
                    start_r: parent.start_r;
                    end_r: parent.end_r;
                    fade_distance: parent.fade_distance;
                    parent_width: parent.width;
                    parent_height: parent.height;
                }

                Ring {
                    index: 2;
                    ring_count: parent.ring_count;
                    period: parent.period;
                    t_base: parent.t_base;
                    start_r: parent.start_r;
                    end_r: parent.end_r;
                    fade_distance: parent.fade_distance;
                    parent_width: parent.width;
                    parent_height: parent.height;
                }

                VerticalLayout {
                    width: parent.width;
                    height: parent.height;
                    alignment: center;
                    Text {
                        text: root.alarm-label;
                        font-size: 48px;
                        color: Palette.orange-30;
                        horizontal-alignment: center;
                    }

                    Text {
                        text: root.time;
                        font-size: 200px;
                        color: Palette.white;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }

                    HorizontalLayout {
                        alignment: center;
                        spacing: 32px;
                        Rectangle {
                            background: Palette.orange-50;
                            width: 218px;
                            HorizontalLayout {
                                padding-left: 48px;
                                padding-right: 48px;
                                padding-top: 15px;
                                padding-bottom: 15px;
                                alignment: center;
                                Text {
                                    text: "Stop Alarm";
                                    color: Palette.white;
                                    font-size: 24px;
                                }
                            }
                        }

                        if show_snooze:  Rectangle {
                            background: Palette.black;
                            border-width: 1px;
                            border-color: Palette.white;
                            width: 218px;

                            HorizontalLayout {
                                padding-left: 48px;
                                padding-right: 48px;
                                padding-top: 15px;
                                padding-bottom: 15px;
                                alignment: center;
                                Text {
                                    text: "Snooze";
                                    color: Palette.white;
                                    font-size: 24px;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
