import { InitSetupTemplate } from "../templates/init_setup.slint";
import { Images } from "../../style/images.slint";
import { ConnectionAdapter } from "../../controls/adapters.slint";
import { Palette } from "../../style/palette.slint";
import { Theme } from "../../style/theme.slint";

export component ConnectQr inherits Rectangle {
    background: Palette.black;
    in property <string> connect_text;
    in property <string> ip <=> ConnectionAdapter.ip;
    in property <image> ip_qr_code <=> ConnectionAdapter.ip_qr_code;

    HorizontalLayout {
        padding-top: 65px;
        padding-bottom: 79px;
        padding-left: 92.5px;
        padding-right: 122px;
        spacing: 119px;

        VerticalLayout {
            spacing: 48px;

            Image {
                width: 284px;
                height: 80px;
                source: Images.desktop-clock;
            }

            VerticalLayout {
                padding-left: 7.5px;
                width: 483px;
                alignment: start;

                Text {
                    text: connect_text;
                    color: Palette.white;
                    font-size: 40px;
                    font-weight: Theme.font.weight.bold;
                    wrap: word-wrap;
                }

                Text {
                    text: "http://" + ip + "/";
                    color: Palette.violet-50;
                    font-size: 40px;
                    font-weight: Theme.font.weight.bold;
                }

                Text {
                    text: "or scan QR code";
                    color: Palette.white;
                    font-size: 40px;
                    font-weight: Theme.font.weight.bold;
                }
            }
        }

        Rectangle {
            width: 1px;
            background: Palette.gray-80;
        }

        Rectangle {
            background: Palette.white;
            width: 336px;
            height: 336px;

            Image {
                source: ip_qr_code;
                width: 320px;
                height: 320px;
            }
        }
    }
}
