import { Palette } from "../../style/palette.slint";
import { Theme } from "../../style/theme.slint";

export component IconAndTextTemplate inherits Rectangle {
    background: black;
    in property <image> icon_text_image;
    in property <bool> icon_text_image_visible;
    in property <string> icon_text_title;
    in property <string> icon_text_content;
    in property <length> icon_text_image_padding_top: 40px;
    VerticalLayout {
        spacing: 15px;
        alignment: center;
        HorizontalLayout {
            padding-top: root.icon_text_image_padding_top;
            padding-bottom: 15px;
            alignment: center;
            Rectangle {
                width: 80px;
                height: 80px;
                Image {
                    visible: root.icon_text_image_visible;
                    source: root.icon_text_image;
                }
            }
        }

        Text {
            text: root.icon_text_title;
            color: Palette.white;
            font-size: 24px;
            font-weight: Theme.font.weight.bold;
            horizontal-alignment: center;
        }

        Text {
            text: root.icon_text_content;
            color: Palette.gray-50;
            font-size: 18px;
            font-weight: Theme.font.weight.regular;
            horizontal-alignment: center;
        }
    }
}
