import { Palette } from "../../style/palette.slint";
import { Theme } from "../../style/theme.slint";

export component InitSetupTemplate inherits Rectangle {
    background: Palette.black;
    in property <image> icon_text_image;
    in property <bool> icon_text_image_visible;
    in property <string> icon_text_header_title;
    in property <string> icon_text_title;
    in property <string> icon_text_content;
    in property <string> icon_text_subtitle;
    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            padding-top: 40px;
            Text {
                text: root.icon_text_header_title;
                color: Palette.gray-40;
                font-size: 24px;
                font-weight: Theme.font.weight.regular;
                horizontal-alignment: center;
            }
        }

        HorizontalLayout {
            padding-top: 32px;
            alignment: center;
            Rectangle {
                Image {
                    visible: root.icon_text_image_visible;
                    source: root.icon_text_image;
                }
            }
        }

        HorizontalLayout {
            padding-top: 32px;
            Text {
                text: root.icon_text_title;
                color: Palette.white;
                font-size: 40px;
                font-weight: Theme.font.weight.semi-bold;
                horizontal-alignment: center;
            }
        }

        HorizontalLayout {
            padding-top: 24px;
            Text {
                text: root.icon_text_content;
                color: Palette.gray-40;
                font-size: 24px;
                font-weight: Theme.font.weight.regular;
                horizontal-alignment: center;
            }
        }

        Text {
            text: root.icon_text_subtitle;
            color: Palette.violet-50;
            font-size: 40px;
            font-weight: Theme.font.weight.regular;
            horizontal-alignment: center;
        }

        @children
    }
}
