import { InitSetupTemplate } from "../templates/init_setup.slint";
import { Images } from "../../style/images.slint";
import { Palette } from "../../style/palette.slint";
import { Theme } from "../../style/theme.slint";
import { WifiAdapter, WifiReconfigAdapter } from "../../controls/adapters.slint";

export component WifiConnectFailed inherits InitSetupTemplate {
    in property <string> header_title;
    in property <string> main_title: "Problem with connection.";

    icon_text_header_title: self.header_title;
    icon_text_title: self.main_title;
    icon_text_content: "WiFi SSID";
    icon_text_subtitle: WifiAdapter.ssid;
    icon_text_image_visible: true;
    icon_text_image: Images.wifi-error;

    HorizontalLayout {
        padding-top: 24px;
        padding-bottom: 80px;
        alignment: center;

        TouchArea {
            width: 280px;
            height: 56px;
            clicked => {
                WifiReconfigAdapter.trigger_reconfig();
            }

            Rectangle {
                width: 100%;
                height: 100%;
                background: Palette.violet-50;
                border-radius: 8px;

                Text {
                    text: "Reconfigure WiFi";
                    color: Palette.white;
                    font-size: 24px;
                    font-weight: Theme.font.weight.semi-bold;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }
            }
        }
    }
}
