import { InitSetupTemplate } from "../templates/init_setup.slint";
import { Images } from "../../style/images.slint";
import { WifiAdapter } from "../../controls/adapters.slint";

export component WifiConnectProgress inherits InitSetupTemplate {
    in property <string> header_title;

    icon_text_header_title: self.header_title;
    icon_text_title: "Connecting...";
    icon_text_content: "WiFi SSID";
    icon_text_subtitle: WifiAdapter.ssid;
    icon_text_image_visible: true;
    icon_text_image: Images.wifi;
}
