settle_delay = 5

[fixtures.bmc100-full]
path = "fixtures/bmc100-full.jsonl.gz"
targets = ["bmc100:full"]

[fixtures.bmc100-large]
path = "fixtures/bmc100-large.jsonl.gz"
targets = ["bmc100:large"]

[fixtures.bmc100-medium]
path = "fixtures/bmc100-medium.jsonl.gz"
targets = ["bmc100:medium"]

[fixtures.bmc100-small]
path = "fixtures/bmc100-small.jsonl.gz"
targets = ["bmc100:small"]
