import "../assets/fonts/BraiinsSans-Regular.otf";
import "../assets/fonts/BraiinsSans-SemiBold.otf";
import "../assets/fonts/BraiinsSans-Bold.otf";
import "../assets/fonts/BraiinsDeckSans-Regular.otf";
import "../assets/fonts/BraiinsDeckSans-SemiBold.otf";
import "../assets/fonts/BraiinsDeckSans-Bold.otf";

struct FontWeight {
    regular: int,
    semi-bold: int,
    bold: int,
}

struct FontSize {
    common: {
        default: length,
    },
}

export struct Font {
    weight: FontWeight,
    size: FontSize,
}

export global Theme {
    out property <Font> font: { weight: {
        regular: 400,
        semi-bold: 600,
        bold: 700,
    }, size: {
        common: {
            default: 20px,
        },
    } };
}
