import { Theme } from "theme.slint";

export enum WidgetSize {
    Small,
    Medium,
    Large,
    Full,
}

export enum FontStyle {
    Light,
    Medium,
    Bold,
}

export struct DateTime {
    is-24-format: bool,
    hour24: int,
    hour12: int,
    is-pm: bool,
    minute: int,
    second: int,
    day: int,
    month: int,
    year: int,
    weekday: string,
    time-sec-24: string,
    time-sec-12: string,
    time-24: string,
    time-12: string,
    date: string,
    timezone: string,
}

export global WidgetUtils {
    pure public function font-style-to-font-weight(font-style: FontStyle) -> int {
        if font-style == FontStyle.Light {
            return Theme.font.weight.regular;
        } else if font-style == FontStyle.Medium {
            return Theme.font.weight.semi-bold;
        } else {
            return Theme.font.weight.bold;
        }
    }
}
