too-many-lines-threshold = 150
too-many-arguments-threshold = 10
disallowed-types = [
    # fs-err for std::fs
    { path = "std::fs::DirEntry", reason = "use `fs_err::DirEntry` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::File", reason = "use `fs_err::File` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::OpenOptions", reason = "use `fs_err::OpenOptions` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::ReadDir", reason = "use `fs_err::ReadDir` or import whole `fs-err` using `use fs_err as fs;`" },
    # fs-err for tokio::fs
    { path = "tokio::fs::DirBuilder", reason = "use `fs_err::tokio::DirBuilder` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::DirEntry", reason = "use `fs_err::tokio::DirEntry` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::File", reason = "use `fs_err::tokio::File` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::OpenOptions", reason = "use `fs_err::tokio::OpenOptions` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::ReadDir", reason = "use `fs_err::tokio::ReadDir` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    # NonZeroT --> NonZero<T>
    { path = "core::num::NonZeroI8", reason = "`NonZero<T>` is preferred over `NonZeroT`" },
    { path = "core::num::NonZeroI16", reason = "`NonZero<T>` is preferred over `NonZeroT`" },
    { path = "core::num::NonZeroI32", reason = "`NonZero<T>` is preferred over `NonZeroT`" },
    { path = "core::num::NonZeroI64", reason = "`NonZero<T>` is preferred over `NonZeroT`" },
    { path = "core::num::NonZeroI128", reason = "`NonZero<T>` is preferred over `NonZeroT`" },
    { path = "core::num::NonZeroIsize", reason = "`NonZero<T>` is preferred over `NonZeroT`" },
    { path = "core::num::NonZeroU8", reason = "`NonZero<T>` is preferred over `NonZeroT`" },
    { path = "core::num::NonZeroU16", reason = "`NonZero<T>` is preferred over `NonZeroT`" },
    { path = "core::num::NonZeroU32", reason = "`NonZero<T>` is preferred over `NonZeroT`" },
    { path = "core::num::NonZeroU64", reason = "`NonZero<T>` is preferred over `NonZeroT`" },
    { path = "core::num::NonZeroU128", reason = "`NonZero<T>` is preferred over `NonZeroT`" },
    { path = "core::num::NonZeroUsize", reason = "`NonZero<T>` is preferred over `NonZeroT`" },
]
disallowed-methods = [
    { path = "url::Url::join", reason = "this method has a weird behavior, you probably want to use our custom `.join_path()` instead" },
    # fs-err for std::fs
    { path = "std::fs::canonicalize", reason = "use `fs_err::canonicalize` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::copy", reason = "use `fs_err::copy` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::create_dir", reason = "use `fs_err::create_dir` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::create_dir_all", reason = "use `fs_err::create_dir_all` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::hard_link", reason = "use `fs_err::hard_link` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::metadata", reason = "use `fs_err::metadata` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::read", reason = "use `fs_err::read` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::read_dir", reason = "use `fs_err::read_dir` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::read_link", reason = "use `fs_err::read_link` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::read_to_string", reason = "use `fs_err::read_to_string` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::remove_dir", reason = "use `fs_err::remove_dir` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::remove_dir_all", reason = "use `fs_err::remove_dir_all` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::remove_file", reason = "use `fs_err::remove_file` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::rename", reason = "use `fs_err::rename` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::set_permissions", reason = "use `fs_err::set_permissions` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::symlink_metadata", reason = "use `fs_err::symlink_metadata` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::write", reason = "use `fs_err::write` or import whole `fs-err` using `use fs_err as fs;`" },
    { path = "std::fs::Path::metadata", reason = "use `fs_err_metadata` from `fs_err::PathExt`" },
    { path = "std::fs::Path::symlink_metadata", reason = "use `fs_err_symlink_metadata` from `fs_err::PathExt`" },
    { path = "std::fs::Path::canonicalize", reason = "use `fs_err_canonicalize` from `fs_err::PathExt`" },
    { path = "std::fs::Path::read_link", reason = "use `fs_err_read_link` from `fs_err::PathExt`" },
    { path = "std::fs::Path::read_dir", reason = "use `fs_err_read_dir` from `fs_err::PathExt`" },
    # fs-err for tokio::fs
    { path = "tokio::fs::canonicalize", reason = "use `fs_err::tokio::canonicalize` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::copy", reason = "use `fs_err::tokio::copy` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::create_dir", reason = "use `fs_err::tokio::create_dir` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::create_dir_all", reason = "use `fs_err::tokio::create_dir_all` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::hard_link", reason = "use `fs_err::tokio::hard_link` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::metadata", reason = "use `fs_err::tokio::metadata` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::read", reason = "use `fs_err::tokio::read` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::read_dir", reason = "use `fs_err::tokio::read_dir` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::read_link", reason = "use `fs_err::tokio::read_link` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::read_to_string", reason = "use `fs_err::tokio::read_to_string` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::remove_dir", reason = "use `fs_err::tokio::remove_dir` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::remove_dir_all", reason = "use `fs_err::tokio::remove_dir_all` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::remove_file", reason = "use `fs_err::tokio::remove_file` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::rename", reason = "use `fs_err::tokio::rename` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::set_permissions", reason = "use `fs_err::tokio::set_permissions` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::symlink", reason = "use `fs_err::tokio::symlink` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::symlink_metadata", reason = "use `fs_err::tokio::symlink_metadata` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
    { path = "tokio::fs::write", reason = "use `fs_err::tokio::write` or import whole `fs-err` using `use fs_err::tokio as fs;`" },
]
