import { UpgradeDownload } from "upgrade/upgrade_download.slint";
import { UpgradeProgress } from "upgrade/upgrade_progress.slint";
import { UpgradeSuccess } from "upgrade/upgrade_success.slint";
import { UpgradeFailed } from "upgrade/upgrade_failed.slint";
import { InitStartConnect } from "init_setup/init_start_connect.slint";
import { InitWifiConnectProgress } from "init_setup/init_wifi_connect_progress.slint";
import { InitWifiConnectSuccess } from "init_setup/init_wifi_connect_success.slint";
import { InitWifiConnectFailed } from "init_setup/init_wifi_connect_failed.slint";
import { InitSetupSuccess } from "init_setup/init_setup_success.slint";
import { InitGeneralError } from "init_setup/init_general_error.slint";
import { InitDeviceSetupQr } from "init_setup/init_device_setup_qr.slint";
import { ConnectInfo } from "general/connect_info.slint";
import { WifiConnectFailed } from "templates/wifi_connect_failed.slint";
import { WifiConnectProgress } from "templates/wifi_connect_progress.slint";

export { UpgradeDownload, UpgradeProgress, UpgradeSuccess, UpgradeFailed }
export { InitStartConnect, InitWifiConnectProgress, InitWifiConnectSuccess, InitWifiConnectFailed, InitSetupSuccess, InitGeneralError, InitDeviceSetupQr, ConnectInfo }
export { WifiConnectFailed, WifiConnectProgress }
