[package]
name = "bmc-net-drv"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bmc-net-observe = { path = "../bmc-net-observe" }
bmc-net-types = { path = "../bmc-net-types" }
bstr.workspace = true
futures.workspace = true
get_if_addrs.workspace = true
log.workspace = true
pnet.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
strum = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["fs", "net", "process", "rt", "sync", "time"] }
wl-nl80211.workspace = true

[[example]]
name = "get_mac_address"
path = "examples/get_mac_address.rs"

[[example]]
name = "get_ipv4_address"
path = "examples/get_ipv4_address.rs"

[package.metadata.cargo-machete]
ignored = ["strum"]
